; Saved by version: 2.5.8

[EventBackDoorLockedReadPage1Base]
buttons=2
event1=EventBackDoorLockedReadPage1BasePass
event2=EventBackDoorLockedReadPage1BaseFail

[EventBackDoorLockedReadPage1BasePass]
operations=testEventBackDoorLockedReadPage1BasePass,=,1 @backdoorLockedPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage1TestEnd EventBackDoorLockedReadPage1End

[EventBackDoorLockedReadPage1BaseFail]
operations=testEventBackDoorLockedReadPage1BaseFail,=,1 @backdoorLockedFail,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage1TestEnd EventBackDoorLockedReadPage1End

[EventBackDoorLockedReadPage1TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage1End

[EventBackDoorLockedReadPage1End]
operations=readBackDoorLockedPage1,=,1 readBackDoorLockedPreviousPage,=,1
display=false
buttons=1
event1=EventBackDoorLockedStart

[EventBackDoorLockedReadPage1]
display=false
buttons=1
event1=EventBackDoorLockedReadPage1Base

[EventBackDoorLockedReadPage2Base]
buttons=2
event1=EventBackDoorLockedReadPage2BasePass
event2=EventBackDoorLockedReadPage2BaseFail

[EventBackDoorLockedReadPage2BasePass]
operations=testEventBackDoorLockedReadPage2BasePass,=,1 @backdoorLockedPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage2TestEnd EventBackDoorLockedReadPage2End

[EventBackDoorLockedReadPage2BaseFail]
operations=testEventBackDoorLockedReadPage2BaseFail,=,1 @backdoorLockedFail,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage2TestEnd EventBackDoorLockedReadPage2End

[EventBackDoorLockedReadPage2TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage2End

[EventBackDoorLockedReadPage2End]
operations=readBackDoorLockedPage2,=,1 readBackDoorLockedPreviousPage,=,2
display=false
buttons=1
event1=EventBackDoorLockedStart

[EventBackDoorLockedReadPage2]
display=false
buttons=1
event1=EventBackDoorLockedReadPage2Base

[EventBackDoorLockedReadPage3Base]
buttons=2
event1=EventBackDoorLockedReadPage3BasePass
event2=EventBackDoorLockedReadPage3BaseFail

[EventBackDoorLockedReadPage3BasePass]
operations=testEventBackDoorLockedReadPage3BasePass,=,1 @backdoorLockedPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage3TestEnd EventBackDoorLockedReadPage3End

[EventBackDoorLockedReadPage3BaseFail]
operations=testEventBackDoorLockedReadPage3BaseFail,=,1 @backdoorLockedFail,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage3TestEnd EventBackDoorLockedReadPage3End

[EventBackDoorLockedReadPage3TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage3End

[EventBackDoorLockedReadPage3End]
operations=readBackDoorLockedPage3,=,1 readBackDoorLockedPreviousPage,=,3
display=false
buttons=1
event1=EventBackDoorLockedStart

[EventBackDoorLockedReadPage3]
display=false
buttons=1
event1=EventBackDoorLockedReadPage3Base

[EventBackDoorLockedReadPage4Base]
buttons=2
event1=EventBackDoorLockedReadPage4BasePass
event2=EventBackDoorLockedReadPage4BaseFail

[EventBackDoorLockedReadPage4BasePass]
operations=testEventBackDoorLockedReadPage4BasePass,=,1 @backdoorLockedPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage4TestEnd EventBackDoorLockedReadPage4End

[EventBackDoorLockedReadPage4BaseFail]
operations=testEventBackDoorLockedReadPage4BaseFail,=,1 @backdoorLockedFail,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage4TestEnd EventBackDoorLockedReadPage4End

[EventBackDoorLockedReadPage4TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage4End

[EventBackDoorLockedReadPage4End]
operations=readBackDoorLockedPage4,=,1 readBackDoorLockedPreviousPage,=,4
display=false
buttons=1
event1=EventBackDoorLockedStart

[EventBackDoorLockedReadPage4]
display=false
buttons=1
event1=EventBackDoorLockedReadPage4Base

[EventBackDoorLockedReadPage5Base]
buttons=2
event1=EventBackDoorLockedReadPage5BasePass
event2=EventBackDoorLockedReadPage5BaseFail

[EventBackDoorLockedReadPage5BasePass]
operations=testEventBackDoorLockedReadPage5BasePass,=,1 @backdoorLockedPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage5TestEnd EventBackDoorLockedReadPage5End

[EventBackDoorLockedReadPage5BaseFail]
operations=testEventBackDoorLockedReadPage5BaseFail,=,1 @backdoorLockedFail,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPage5TestEnd EventBackDoorLockedReadPage5End

[EventBackDoorLockedReadPage5TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage5End

[EventBackDoorLockedReadPage5End]
operations=readBackDoorLockedPage5,=,1 readBackDoorLockedPreviousPage,=,5
display=false
buttons=1
event1=EventBackDoorLockedStart

[EventBackDoorLockedReadPage5]
display=false
buttons=1
event1=EventBackDoorLockedReadPage5Base

[EventBackDoorLockedReadPage6Base]
buttons=1
event1=EventBackDoorLockedReadPage6TestEnd EventBackDoorLockedReadPage6End

[EventBackDoorLockedReadPage6TestEnd]
operations=readBackDoorLockedFinished,=,1
vartests=VarOperation:readBackDoorLockedFinished,==,0 VarOperation:readBackDoorLockedPage1,>,0 VarOperation:readBackDoorLockedPage2,>,0 VarOperation:readBackDoorLockedPage3,>,0 VarOperation:readBackDoorLockedPage4,>,0 VarOperation:readBackDoorLockedPage5,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPage6End

[EventBackDoorLockedReadPage6End]
operations=readBackDoorLockedPage6,=,1 readBackDoorLockedPreviousPage,=,6
display=false
buttons=1
event1=EventBackDoorLockedEnd

[EventBackDoorLockedReadPage6]
display=false
buttons=1
event1=EventBackDoorLockedReadPage6Base

[EventBackDoorLockedReadPage1Proxy]
vartests=VarOperation:readBackDoorLockedPage1,==,0 
buttons=2
event1=EventBackDoorLockedReadPage1
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPage2Proxy]
vartests=VarOperation:readBackDoorLockedPage2,==,0 
buttons=2
event1=EventBackDoorLockedReadPage2
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPage3Proxy]
vartests=VarOperation:readBackDoorLockedPage3,==,0 
buttons=2
event1=EventBackDoorLockedReadPage3
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPage4Proxy]
vartests=VarOperation:readBackDoorLockedPage4,==,0 
buttons=2
event1=EventBackDoorLockedReadPage4
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPage5Proxy]
vartests=VarOperation:readBackDoorLockedPage5,==,0 
buttons=2
event1=EventBackDoorLockedReadPage5
event2=EventBackDoorLockedEnd

[EventBackDoorLockedStart]
display=false
buttons=1
event1=EventBackDoorLockedReadPage1Proxy EventBackDoorLockedReadPage2Proxy EventBackDoorLockedReadPage3Proxy EventBackDoorLockedReadPage4Proxy EventBackDoorLockedReadPage5Proxy

[EventBackDoorLockedEnd]
display=false
buttons=0
