; Saved by version: 3.0.2

[EventStart]
display=false
buttons=0
add=TokenBackyardBenBefore TokenBackDoorLocked TokenJournal TokenDvmRescueBoy
trigger=EventStart

[EventPlaceDiningRoom]
operations=exploredDiningRoom,=,1
vartests=VarOperation:talkedToBenCount,>=,2 
buttons=1
event1=
trigger=VarTalkedToBackyardBen
