; Saved by version: 3.0.2
[Quest]
format=19
hidden=False
type=MoM
defaultlanguage=English
defaultmusicon=True


[QuestText]
Localization.English.txt

[QuestData]
BackDoorLocked.events.ini
BackyardBenBefore.events.ini
DvmRescueBoy.events.ini
Journal.events.ini
events.ini
tokens.ini
