; Saved by version: 3.0.2

[TokenBackyardBenBefore]
xposition=0
yposition=1.75
buttons=1
event1=EventBackyardBenBeforeStart
type=TokenPurpleMan

[TokenBackDoorLocked]
xposition=0
yposition=-1.75
buttons=1
event1=EventBackDoorLockedStart
type=TokenExplore

[TokenJournal]
xposition=0
yposition=0
buttons=1
event1=EventJournalStart
type=TokenUniqueOldJournal

[TokenDvmRescueBoy]
xposition=1.75
yposition=0
buttons=1
event1=EventDVMRescueBoyStart
type=TokenCommonArcaneManuscript
