; Saved by version: 3.0.4

[EventBackyardBenAfterStart]
operations=BackyardBenAfterTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBackyardBenAfterInit

[EventBackyardBenAfterInit]
operations=EventBackyardBenAfterExit,=,1
display=false
buttons=1
event1=EventBackyardBenAfterFirstTimeInitializer EventBackyardBenAfterToc

[EventBackyardBenAfterFirstTimeInitializer]
operations=EventBackyardBenAfterInitialized,=,1 BackyardBenAfterDirtVisible,=,1 BackyardBenAfterFootprintsVisible,=,1 BackyardBenAfterAnythingElseVisible,=,1
vartests=VarOperation:EventBackyardBenAfterInitialized,==,0 
display=false
buttons=1
event1=EventBackyardBenAfterToc

[EventBackyardBenAfterToc]
display=false
buttons=1
event1=EventBackyardBenAfterTocSelector

[EventBackyardBenAfterTocSelector]
display=false
buttons=1
event1=EventBackyardBenAfterToc0 EventBackyardBenAfterToc1 EventBackyardBenAfterToc2 EventBackyardBenAfterToc3 EventBackyardBenAfterTocTiePoint

[EventBackyardBenAfterToc0]
vartests=VarOperation:readBackyardBenAfterPreviousPage,==,0 
buttons=4
event1=EventBackyardBenAfterReadPageDirt
event1Condition=VarOperation:BackyardBenAfterDirtVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBackyardBenAfterReadPageFootprints
event2Condition=VarOperation:BackyardBenAfterFootprintsVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBackyardBenAfterReadPageAnythingElse
event3Condition=VarOperation:BackyardBenAfterAnythingElseVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBackyardBenAfterReadPageDirt]
display=false
buttons=1
event1=EventBackyardBenAfterExpr2

[EventBackyardBenAfterExpr2]
comment=@(21, 15)
operations=EventBackyardBenAfterExpr2Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBackyardBenAfterExpr3 EventBackyardBenAfterExpr4

[EventBackyardBenAfterExpr3]
comment=@(21, 11)
operations=EventBackyardBenAfterExpr2Temp,=,1
vartests=VarOperation:EventBackyardBenAfterExpr2Temp,==,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageDirtDisplay

[EventBackyardBenAfterReadPageDirtDisplay]
display=false
buttons=1
event1=EventBackyardBenAfterReadPageDirtOverload1 EventBackyardBenAfterReadPageDirtBase

[EventBackyardBenAfterReadPageDirtOverload1]
operations=readBackyardBenAfterDirt,=,1
vartests=VarOperation:EventBackyardBenAfterExpr2Temp,>,0 
buttons=1
event1=EventBackyardBenAfterReadPageDirtTiePoint

[EventBackyardBenAfterReadPageDirtTiePoint]
operations=readBackyardBenAfterPreviousPage,=,1 readBackyardBenAfterDirt,=,1 readBackyardBenAfterPreviousPage,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageDirtTestEnd EventBackyardBenAfterReadPageDirtEnd

[EventBackyardBenAfterReadPageDirtTestEnd]
operations=readBackyardBenAfterFinished,=,1
vartests=VarOperation:readEventBackyardBenAfterReadPageDirtFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageDirtEnd

[EventBackyardBenAfterReadPageDirtEnd]
display=false
buttons=1
event1=EventBackyardBenAfterTiePoint

[EventBackyardBenAfterTiePoint]
display=false
buttons=1
event1=EventBackyardBenAfterClearTrigger

[EventBackyardBenAfterClearTrigger]
operations=BackyardBenAfterTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBackyardBenAfterLoopBack EventBackyardBenAfterEnd

[EventBackyardBenAfterLoopBack]
vartests=VarOperation:EventBackyardBenAfterExit,==,0 
display=false
buttons=1
event1=EventBackyardBenAfterInit

[EventBackyardBenAfterEnd]
display=false
buttons=1
event1=

[EventBackyardBenAfterReadPageDirtBase]
buttons=1
event1=EventBackyardBenAfterReadPageDirtTiePoint

[EventBackyardBenAfterExpr4]
comment=@(21, 11)
operations=EventBackyardBenAfterExpr2Temp,=,0
display=false
buttons=1
event1=EventBackyardBenAfterReadPageDirtDisplay

[EventBackyardBenAfterReadPageFootprints]
display=false
buttons=1
event1=EventBackyardBenAfterExpr5

[EventBackyardBenAfterExpr5]
comment=@(35, 15)
operations=EventBackyardBenAfterExpr5Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBackyardBenAfterExpr6 EventBackyardBenAfterExpr7

[EventBackyardBenAfterExpr6]
comment=@(35, 11)
operations=EventBackyardBenAfterExpr5Temp,=,1
vartests=VarOperation:EventBackyardBenAfterExpr5Temp,==,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsDisplay

[EventBackyardBenAfterReadPageFootprintsDisplay]
display=false
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsOverload1 EventBackyardBenAfterReadPageFootprintsBase

[EventBackyardBenAfterReadPageFootprintsOverload1]
operations=readBackyardBenAfterFootprints,=,1
vartests=VarOperation:EventBackyardBenAfterExpr5Temp,>,0 
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsTiePoint

[EventBackyardBenAfterReadPageFootprintsTiePoint]
operations=readBackyardBenAfterPreviousPage,=,2 readBackyardBenAfterFootprints,=,1 readBackyardBenAfterPreviousPage,=,2
display=false
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsTestEnd EventBackyardBenAfterReadPageFootprintsEnd

[EventBackyardBenAfterReadPageFootprintsTestEnd]
operations=readBackyardBenAfterFinished,=,1
vartests=VarOperation:readEventBackyardBenAfterReadPageFootprintsFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsEnd

[EventBackyardBenAfterReadPageFootprintsEnd]
display=false
buttons=1
event1=EventBackyardBenAfterTiePoint

[EventBackyardBenAfterReadPageFootprintsBase]
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsTiePoint

[EventBackyardBenAfterExpr7]
comment=@(35, 11)
operations=EventBackyardBenAfterExpr5Temp,=,0
display=false
buttons=1
event1=EventBackyardBenAfterReadPageFootprintsDisplay

[EventBackyardBenAfterReadPageAnythingElse]
display=false
buttons=1
event1=EventBackyardBenAfterExpr8

[EventBackyardBenAfterExpr8]
comment=@(58, 15)
operations=EventBackyardBenAfterExpr8Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBackyardBenAfterExpr9 EventBackyardBenAfterExpr10

[EventBackyardBenAfterExpr9]
comment=@(58, 11)
operations=EventBackyardBenAfterExpr8Temp,=,1
vartests=VarOperation:EventBackyardBenAfterExpr8Temp,==,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseAddRemoveBefore1

[EventBackyardBenAfterReadPageAnythingElseAddRemoveBefore1]
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseAddRemoveBefore2
remove=TokenBackyardBenAfter

[EventBackyardBenAfterReadPageAnythingElseAddRemoveBefore2]
display=false
buttons=1
event1=EventBackyardBenAfterExpr11
add=TokenExploreBackDoorLocked TokenInvestigatorsDiningRoom

[EventBackyardBenAfterExpr11]
comment=@(72, 21)
operations=EventBackyardBenAfterExpr11Temp,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseLetBefore3

[EventBackyardBenAfterReadPageAnythingElseLetBefore3]
operations=$MythosKey,=,EventBackyardBenAfterExpr11Temp
display=false
buttons=1
event1=EventBackyardBenAfterExpr12

[EventBackyardBenAfterExpr12]
comment=@(73, 34)
operations=EventBackyardBenAfterExpr12Temp,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseLetBefore4

[EventBackyardBenAfterReadPageAnythingElseLetBefore4]
operations=talkedToBenAnythingElse,=,EventBackyardBenAfterExpr12Temp
display=false
buttons=1
event1=EventBackyardBenAfterExpr13

[EventBackyardBenAfterExpr13]
comment=@(74, 27)
operations=EventBackyardBenAfterExpr13Temp,=,talkedToBenCount
display=false
buttons=1
event1=EventBackyardBenAfterExpr14

[EventBackyardBenAfterExpr14]
comment=@(74, 46)
operations=EventBackyardBenAfterExpr14Temp,=,1
display=false
buttons=1
event1=EventBackyardBenAfterExpr15

[EventBackyardBenAfterExpr15]
comment=@(74, 27)
operations=EventBackyardBenAfterExpr13Temp,+,EventBackyardBenAfterExpr14Temp
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseLetBefore5

[EventBackyardBenAfterReadPageAnythingElseLetBefore5]
operations=talkedToBenCount,=,EventBackyardBenAfterExpr13Temp
display=false
buttons=1
event1=EventBackyardBenAfterExpr16

[EventBackyardBenAfterExpr16]
comment=@(76, 41)
operations=EventBackyardBenAfterExpr16Temp,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseLetBefore6

[EventBackyardBenAfterReadPageAnythingElseLetBefore6]
operations=@removeDiningRoomInvestigators,=,EventBackyardBenAfterExpr16Temp
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseTriggerBefore7

[EventBackyardBenAfterReadPageAnythingElseTriggerBefore7]
operations=@TalkedToBackyardBen,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseDisplay

[EventBackyardBenAfterReadPageAnythingElseDisplay]
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseOverload1 EventBackyardBenAfterReadPageAnythingElseBase

[EventBackyardBenAfterReadPageAnythingElseOverload1]
operations=readBackyardBenAfterAnythingElse,=,1
vartests=VarOperation:EventBackyardBenAfterExpr8Temp,>,0 
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseTiePoint

[EventBackyardBenAfterReadPageAnythingElseTiePoint]
operations=readBackyardBenAfterPreviousPage,=,3 readBackyardBenAfterAnythingElse,=,1 readBackyardBenAfterPreviousPage,=,3
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseExitAfter1

[EventBackyardBenAfterReadPageAnythingElseExitAfter1]
operations=EventBackyardBenAfterExit,=,1
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseTestEnd EventBackyardBenAfterReadPageAnythingElseEnd

[EventBackyardBenAfterReadPageAnythingElseTestEnd]
operations=readBackyardBenAfterFinished,=,1
vartests=VarOperation:readEventBackyardBenAfterReadPageAnythingElseFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseEnd

[EventBackyardBenAfterReadPageAnythingElseEnd]
display=false
buttons=1
event1=EventBackyardBenAfterTiePoint

[EventBackyardBenAfterReadPageAnythingElseBase]
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseTiePoint

[EventBackyardBenAfterExpr10]
comment=@(58, 11)
operations=EventBackyardBenAfterExpr8Temp,=,0
display=false
buttons=1
event1=EventBackyardBenAfterReadPageAnythingElseAddRemoveBefore1

[EventBackyardBenAfterToc1]
vartests=VarOperation:readBackyardBenAfterPreviousPage,==,1 
buttons=4
event1=EventBackyardBenAfterReadPageDirt
event1Condition=VarOperation:BackyardBenAfterDirtVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBackyardBenAfterReadPageFootprints
event2Condition=VarOperation:BackyardBenAfterFootprintsVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBackyardBenAfterReadPageAnythingElse
event3Condition=VarOperation:BackyardBenAfterAnythingElseVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBackyardBenAfterToc2]
vartests=VarOperation:readBackyardBenAfterPreviousPage,==,2 
buttons=4
event1=EventBackyardBenAfterReadPageDirt
event1Condition=VarOperation:BackyardBenAfterDirtVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBackyardBenAfterReadPageFootprints
event2Condition=VarOperation:BackyardBenAfterFootprintsVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBackyardBenAfterReadPageAnythingElse
event3Condition=VarOperation:BackyardBenAfterAnythingElseVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBackyardBenAfterToc3]
vartests=VarOperation:readBackyardBenAfterPreviousPage,==,3 
buttons=4
event1=EventBackyardBenAfterReadPageDirt
event1Condition=VarOperation:BackyardBenAfterDirtVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBackyardBenAfterReadPageFootprints
event2Condition=VarOperation:BackyardBenAfterFootprintsVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBackyardBenAfterReadPageAnythingElse
event3Condition=VarOperation:BackyardBenAfterAnythingElseVisible,==,0 VarTestsLogicalOperator:OR VarOperation:readBackyardBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBackyardBenAfterTocTiePoint]
display=false
buttons=1
event1=EventBackyardBenAfterTocIsFinished EventBackyardBenAfterClearTrigger

[EventBackyardBenAfterTocIsFinished]
operations=readBackyardBenAfterFinished,=,1
vartests=VarOperation:readBackyardBenAfterProlog,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBackyardBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBackyardBenAfterClearTrigger
