; Saved by version: 3.0.4

[EventBackDoorLockedStart]
operations=BackDoorLockedTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBackDoorLockedInit

[EventBackDoorLockedInit]
operations=EventBackDoorLockedExit,=,0
display=false
buttons=1
event1=EventBackDoorLockedFirstTimeInitializer EventBackDoorLockedToc

[EventBackDoorLockedFirstTimeInitializer]
operations=EventBackDoorLockedInitialized,=,1 BackDoorLockedTurnKnobVisible,=,1 BackDoorLockedShakeDoorVisible,=,1 BackDoorLockedHitDoorVisible,=,1 BackDoorLockedPickLockVisible,=,1 BackDoorLockedUnlockDoorVisible,=,1
vartests=VarOperation:EventBackDoorLockedInitialized,==,0 
display=false
buttons=1
event1=EventBackDoorLockedToc

[EventBackDoorLockedToc]
display=false
buttons=1
event1=EventBackDoorLockedTocSelector

[EventBackDoorLockedTocSelector]
display=false
buttons=1
event1=EventBackDoorLockedTocPrologTurnKnob EventBackDoorLockedTocPrologShakeDoor EventBackDoorLockedTocPrologHitDoor EventBackDoorLockedTocPrologPickLock EventBackDoorLockedTocPrologUnlockDoor EventBackDoorLockedTocPrologEpilog

[EventBackDoorLockedTocPrologTurnKnob]
vartests=VarOperation:readBackDoorLockedTurnKnob,==,0 VarTestsLogicalOperator:AND VarOperation:BackDoorLockedTurnKnobVisible,>,0 
buttons=2
event1=EventBackDoorLockedReadPageTurnKnob
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPageTurnKnob]
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobDisplay

[EventBackDoorLockedReadPageTurnKnobDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobBase

[EventBackDoorLockedReadPageTurnKnobBase]
buttons=2
event1=EventBackDoorLockedReadPageTurnKnobBasePassTest
event2=EventBackDoorLockedReadPageTurnKnobBaseFailTest
quota=20

[EventBackDoorLockedReadPageTurnKnobBasePassTest]
operations=testBackDoorLockedTurnKnobPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobTiePoint

[EventBackDoorLockedReadPageTurnKnobTiePoint]
operations=readBackDoorLockedPreviousPage,=,1 readBackDoorLockedTurnKnob,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobPostTest

[EventBackDoorLockedReadPageTurnKnobPostTest]
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobPostTestPass EventBackDoorLockedReadPageTurnKnobPostTestFail

[EventBackDoorLockedReadPageTurnKnobPostTestPass]
vartests=VarOperation:testBackDoorLockedTurnKnobPass,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobEnd

[EventBackDoorLockedReadPageTurnKnobEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint

[EventBackDoorLockedTiePoint]
display=false
buttons=1
event1=EventBackDoorLockedClearTrigger

[EventBackDoorLockedClearTrigger]
operations=BackDoorLockedTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBackDoorLockedLoopBack EventBackDoorLockedEnd

[EventBackDoorLockedLoopBack]
vartests=VarOperation:EventBackDoorLockedExit,==,0 
display=false
buttons=1
event1=EventBackDoorLockedInit

[EventBackDoorLockedEnd]
display=false
buttons=1
event1=

[EventBackDoorLockedReadPageTurnKnobPostTestFail]
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobEnd

[EventBackDoorLockedReadPageTurnKnobBaseFailTest]
operations=testBackDoorLockedTurnKnobPass,=,0
display=false
buttons=1
event1=EventBackDoorLockedReadPageTurnKnobTiePoint

[EventBackDoorLockedTocPrologShakeDoor]
vartests=VarOperation:readBackDoorLockedShakeDoor,==,0 VarTestsLogicalOperator:AND VarOperation:BackDoorLockedShakeDoorVisible,>,0 
buttons=2
event1=EventBackDoorLockedReadPageShakeDoor
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPageShakeDoor]
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorDisplay

[EventBackDoorLockedReadPageShakeDoorDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorBase

[EventBackDoorLockedReadPageShakeDoorBase]
buttons=2
event1=EventBackDoorLockedReadPageShakeDoorBasePassTest
event2=EventBackDoorLockedReadPageShakeDoorBaseFailTest
quota=20

[EventBackDoorLockedReadPageShakeDoorBasePassTest]
operations=testBackDoorLockedShakeDoorPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorTiePoint

[EventBackDoorLockedReadPageShakeDoorTiePoint]
operations=readBackDoorLockedPreviousPage,=,2 readBackDoorLockedShakeDoor,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorPostTest

[EventBackDoorLockedReadPageShakeDoorPostTest]
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorPostTestPass EventBackDoorLockedReadPageShakeDoorPostTestFail

[EventBackDoorLockedReadPageShakeDoorPostTestPass]
vartests=VarOperation:testBackDoorLockedShakeDoorPass,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorEnd

[EventBackDoorLockedReadPageShakeDoorEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint

[EventBackDoorLockedReadPageShakeDoorPostTestFail]
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorEnd

[EventBackDoorLockedReadPageShakeDoorBaseFailTest]
operations=testBackDoorLockedShakeDoorPass,=,0
display=false
buttons=1
event1=EventBackDoorLockedReadPageShakeDoorTiePoint

[EventBackDoorLockedTocPrologHitDoor]
vartests=VarOperation:readBackDoorLockedHitDoor,==,0 VarTestsLogicalOperator:AND VarOperation:BackDoorLockedHitDoorVisible,>,0 
buttons=2
event1=EventBackDoorLockedReadPageHitDoor
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPageHitDoor]
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorDisplay

[EventBackDoorLockedReadPageHitDoorDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorBase

[EventBackDoorLockedReadPageHitDoorBase]
buttons=2
event1=EventBackDoorLockedReadPageHitDoorBasePassTest
event2=EventBackDoorLockedReadPageHitDoorBaseFailTest
quota=20

[EventBackDoorLockedReadPageHitDoorBasePassTest]
operations=testBackDoorLockedHitDoorPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorTiePoint

[EventBackDoorLockedReadPageHitDoorTiePoint]
operations=readBackDoorLockedPreviousPage,=,3 readBackDoorLockedHitDoor,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorPostTest

[EventBackDoorLockedReadPageHitDoorPostTest]
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorPostTestPass EventBackDoorLockedReadPageHitDoorPostTestFail

[EventBackDoorLockedReadPageHitDoorPostTestPass]
vartests=VarOperation:testBackDoorLockedHitDoorPass,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorEnd

[EventBackDoorLockedReadPageHitDoorEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint

[EventBackDoorLockedReadPageHitDoorPostTestFail]
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorEnd

[EventBackDoorLockedReadPageHitDoorBaseFailTest]
operations=testBackDoorLockedHitDoorPass,=,0
display=false
buttons=1
event1=EventBackDoorLockedReadPageHitDoorTiePoint

[EventBackDoorLockedTocPrologPickLock]
vartests=VarOperation:readBackDoorLockedPickLock,==,0 VarTestsLogicalOperator:AND VarOperation:BackDoorLockedPickLockVisible,>,0 
buttons=2
event1=EventBackDoorLockedReadPagePickLock
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPagePickLock]
display=false
buttons=1
event1=EventBackDoorLockedExpr1

[EventBackDoorLockedExpr1]
comment=@(83, 15)
operations=EventBackDoorLockedExpr1Temp,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockLetBefore1

[EventBackDoorLockedReadPagePickLockLetBefore1]
operations=pickedLock,=,EventBackDoorLockedExpr1Temp
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockDisplay

[EventBackDoorLockedReadPagePickLockDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockBase

[EventBackDoorLockedReadPagePickLockBase]
buttons=2
event1=EventBackDoorLockedReadPagePickLockBasePassTest
event2=EventBackDoorLockedReadPagePickLockBaseFailTest
quota=20

[EventBackDoorLockedReadPagePickLockBasePassTest]
operations=testBackDoorLockedPickLockPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockTiePoint

[EventBackDoorLockedReadPagePickLockTiePoint]
operations=readBackDoorLockedPreviousPage,=,4 readBackDoorLockedPickLock,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockPostTest

[EventBackDoorLockedReadPagePickLockPostTest]
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockPostTestPass EventBackDoorLockedReadPagePickLockPostTestFail

[EventBackDoorLockedReadPagePickLockPostTestPass]
vartests=VarOperation:testBackDoorLockedPickLockPass,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockEnd

[EventBackDoorLockedReadPagePickLockEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint

[EventBackDoorLockedReadPagePickLockPostTestFail]
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockEnd

[EventBackDoorLockedReadPagePickLockBaseFailTest]
operations=testBackDoorLockedPickLockPass,=,0
display=false
buttons=1
event1=EventBackDoorLockedReadPagePickLockTiePoint

[EventBackDoorLockedTocPrologUnlockDoor]
vartests=VarOperation:readBackDoorLockedUnlockDoor,==,0 VarTestsLogicalOperator:AND VarOperation:BackDoorLockedUnlockDoorVisible,>,0 
buttons=2
event1=EventBackDoorLockedReadPageUnlockDoor
event2=EventBackDoorLockedEnd

[EventBackDoorLockedReadPageUnlockDoor]
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorDisplay

[EventBackDoorLockedReadPageUnlockDoorDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorBase

[EventBackDoorLockedReadPageUnlockDoorBase]
buttons=2
event1=EventBackDoorLockedReadPageUnlockDoorBasePassTest
event2=EventBackDoorLockedReadPageUnlockDoorBaseFailTest
quota=20

[EventBackDoorLockedReadPageUnlockDoorBasePassTest]
operations=testBackDoorLockedUnlockDoorPass,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorTiePoint

[EventBackDoorLockedReadPageUnlockDoorTiePoint]
operations=readBackDoorLockedPreviousPage,=,5 readBackDoorLockedUnlockDoor,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorPostTest

[EventBackDoorLockedReadPageUnlockDoorPostTest]
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorPostTestPass EventBackDoorLockedReadPageUnlockDoorPostTestFail

[EventBackDoorLockedReadPageUnlockDoorPostTestPass]
vartests=VarOperation:testBackDoorLockedUnlockDoorPass,>,0 
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorEnd

[EventBackDoorLockedReadPageUnlockDoorEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint

[EventBackDoorLockedReadPageUnlockDoorPostTestFail]
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorEnd

[EventBackDoorLockedReadPageUnlockDoorBaseFailTest]
operations=testBackDoorLockedUnlockDoorPass,=,0
display=false
buttons=1
event1=EventBackDoorLockedReadPageUnlockDoorTiePoint

[EventBackDoorLockedTocPrologEpilog]
display=false
buttons=1
event1=EventBackDoorLockedReadPageEpilog

[EventBackDoorLockedReadPageEpilog]
operations=EventBackDoorLockedExit,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageEpilogDisplay

[EventBackDoorLockedReadPageEpilogDisplay]
display=false
buttons=1
event1=EventBackDoorLockedReadPageEpilogBase

[EventBackDoorLockedReadPageEpilogBase]
buttons=1
event1=EventBackDoorLockedReadPageEpilogTiePoint

[EventBackDoorLockedReadPageEpilogTiePoint]
operations=readBackDoorLockedPreviousPage,=,6 readBackDoorLockedEpilog,=,1
display=false
buttons=1
event1=EventBackDoorLockedReadPageEpilogAddRemoveAfter1

[EventBackDoorLockedReadPageEpilogAddRemoveAfter1]
display=false
buttons=1
event1=EventBackDoorLockedReadPageEpilogEnd
remove=TokenExploreBackDoorLocked

[EventBackDoorLockedReadPageEpilogEnd]
display=false
buttons=1
event1=EventBackDoorLockedTiePoint
