; Saved by version: 3.11

[EventBasementStart]
operations=BasementTriggeredPageIndex,=,0
buttons=1
event1=EventBasementInit

[EventBasementInit]
operations=EventBasementExit,=,0
buttons=1
event1=EventBasementFirstTimeInitializer EventBasementExpr2

[EventBasementFirstTimeInitializer]
operations=EventBasementInitialized,=,1 visibleBasementPlaceStart,=,1 visibleBasementPlaceDarkness,=,1 visibleBasementPlaceEvidence,=,1 visibleBasementPlaceExploreDungeonCaveViaBasement,=,1 visibleBasementPlaceEnd,=,1 visibleBasementSearchEvidence,=,1 visibleBasementSearchTrapdoor,=,1
vartests=VarOperation:EventBasementInitialized,==,0 
buttons=1
event1=EventBasementExpr2

[EventBasementExpr2]
comment=@(53, 15)
operations=EventBasementExpr2Temp,=,readAboutExploreDungeonCaveViaBasement
buttons=1
event1=EventBasementExpr13

[EventBasementExpr13]
comment=@(53, 2)
operations=visibleBasementPlaceExploreDungeonCaveViaBasement,=,EventBasementExpr2Temp
buttons=1
event1=EventBasementExpr14

[EventBasementExpr14]
comment=@(73, 2)
operations=EventBasementReadPageSearchEvidenceExpr1TempA,=,0
buttons=1
event1=EventBasementExpr15

[EventBasementExpr15]
comment=@(73, 2)
operations=visibleBasementSearchEvidence,=,EventBasementReadPageSearchEvidenceExpr1TempA
buttons=1
event1=EventBasementExpr16

[EventBasementExpr16]
comment=@(96, 2)
operations=EventBasementReadPageSearchTrapdoorExpr2TempA,=,0
buttons=1
event1=EventBasementExpr17

[EventBasementExpr17]
comment=@(96, 2)
operations=visibleBasementSearchTrapdoor,=,EventBasementReadPageSearchTrapdoorExpr2TempA
buttons=1
event1=EventBasementTriggerPrologSelector

[EventBasementTriggerPrologSelector]
buttons=1
event1=EventBasementReadPagePlaceStartTriggeredPrologTarget EventBasementReadPageSearchEvidenceTriggeredPrologTarget EventBasementReadPageSearchTrapdoorTriggeredPrologTarget EventBasementTriggerSelector

[EventBasementReadPagePlaceStartTriggeredPrologTarget]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,1 
buttons=1
event1=EventBasementTocPrologPlaceStart

[EventBasementTocPrologPlaceStart]
buttons=2
event1=EventBasementReadPagePlaceStart
event2=EventBasementEnd

[EventBasementReadPagePlaceStart]
operations=readBasementPreviousPage,=,1 readBasementPlaceStart,=,1
buttons=1
event1=EventBasementReadPagePlaceStartBeforeAddRemove1

[EventBasementReadPagePlaceStartBeforeAddRemove1]
comment=@(16, 2)
buttons=1
event1=EventBasementReadPagePlaceStartBeforeAddRemove2
remove=TokenExploreBasementViaDiningRoomSight

[EventBasementReadPagePlaceStartBeforeAddRemove2]
comment=@(17, 2)
buttons=1
event1=EventBasementReadPagePlaceStartDisplay
add=TileBasement TokenBasementWall

[EventBasementReadPagePlaceStartDisplay]
buttons=1
event1=EventBasementReadPagePlaceStartBase

[EventBasementReadPagePlaceStartBase]
buttons=1
event1=EventBasementReadPagePlaceStartTiePoint

[EventBasementReadPagePlaceStartTiePoint]
buttons=1
event1=EventBasementExpr1

[EventBasementExpr1]
comment=@(25, 21)
operations=EventBasementExpr1Temp,=,1
buttons=1
event1=EventBasementReadPagePlaceStartAfterLet1

[EventBasementReadPagePlaceStartAfterLet1]
comment=@(25, 2)
operations=exploredBasement,=,EventBasementExpr1Temp
buttons=1
event1=EventBasementReadPagePlaceStartEnd

[EventBasementReadPagePlaceStartEnd]
buttons=1
event1=EventBasementTiePoint

[EventBasementTiePoint]
buttons=1
event1=EventBasementLoopBack EventBasementEnd

[EventBasementLoopBack]
vartests=VarOperation:EventBasementExit,==,0 
buttons=1
event1=EventBasementInit

[EventBasementEnd]
buttons=1
event1=

[EventBasementReadPageSearchEvidenceTriggeredPrologTarget]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,6 
buttons=1
event1=EventBasementTocPrologSearchEvidence

[EventBasementTocPrologSearchEvidence]
buttons=2
event1=EventBasementReadPageSearchEvidence
event2=EventBasementEnd

[EventBasementReadPageSearchEvidence]
operations=readBasementPreviousPage,=,6 readBasementSearchEvidence,=,1
buttons=1
event1=EventBasementReadPageSearchEvidenceBeforeAddRemove1

[EventBasementReadPageSearchEvidenceBeforeAddRemove1]
comment=@(78, 2)
buttons=1
event1=EventBasementReadPageSearchEvidenceDisplay
remove=TokenSearchBasementEvidence

[EventBasementReadPageSearchEvidenceDisplay]
buttons=1
event1=EventBasementReadPageSearchEvidenceBase

[EventBasementReadPageSearchEvidenceBase]
buttons=1
event1=EventBasementReadPageSearchEvidenceTiePoint
add=QItemEvidenceBasementRubble

[EventBasementReadPageSearchEvidenceTiePoint]
buttons=1
event1=EventBasementExpr9

[EventBasementExpr9]
comment=@(90, 26)
operations=EventBasementExpr9Temp,=,1
buttons=1
event1=EventBasementReadPageSearchEvidenceAfterLet1

[EventBasementReadPageSearchEvidenceAfterLet1]
comment=@(90, 2)
operations=foundEvidenceBasement,=,EventBasementExpr9Temp
buttons=1
event1=EventBasementExpr10

[EventBasementExpr10]
comment=@(91, 23)
operations=EventBasementExpr10Temp,=,foundEvidenceCount
buttons=1
event1=EventBasementExpr11

[EventBasementExpr11]
comment=@(91, 44)
operations=EventBasementExpr11Temp,=,1
buttons=1
event1=EventBasementExpr12

[EventBasementExpr12]
comment=@(91, 23)
operations=EventBasementExpr10Temp,+,EventBasementExpr11Temp
buttons=1
event1=EventBasementReadPageSearchEvidenceAfterLet2

[EventBasementReadPageSearchEvidenceAfterLet2]
comment=@(91, 2)
operations=foundEvidenceCount,=,EventBasementExpr10Temp
buttons=1
event1=EventBasementReadPageSearchEvidenceAfterGoto12

[EventBasementReadPageSearchEvidenceAfterGoto12]
comment=@(92, 2)
buttons=1
event1=EventBasementEnd

[EventBasementReadPageSearchTrapdoorTriggeredPrologTarget]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,7 
buttons=1
event1=EventBasementTocPrologSearchTrapdoor

[EventBasementTocPrologSearchTrapdoor]
buttons=2
event1=EventBasementReadPageSearchTrapdoor
event2=EventBasementEnd

[EventBasementReadPageSearchTrapdoor]
operations=readBasementPreviousPage,=,7 readBasementSearchTrapdoor,=,1
buttons=1
event1=EventBasementReadPageSearchTrapdoorBeforeAddRemove1

[EventBasementReadPageSearchTrapdoorBeforeAddRemove1]
comment=@(104, 2)
buttons=1
event1=EventBasementReadPageSearchTrapdoorBeforeAddRemove2
remove=TokenBasementWall TokenSearchBasementTrapdoor

[EventBasementReadPageSearchTrapdoorBeforeAddRemove2]
comment=@(105, 2)
buttons=1
event1=EventBasementReadPageSearchTrapdoorBeforeAddRemove3
remove=TokenDungeonCaveWall

[EventBasementReadPageSearchTrapdoorBeforeAddRemove3]
comment=@(106, 2)
buttons=1
event1=EventBasementReadPageSearchTrapdoorDisplay
add=TokenExploreDungeonCaveViaBasement

[EventBasementReadPageSearchTrapdoorDisplay]
buttons=1
event1=EventBasementReadPageSearchTrapdoorBase

[EventBasementReadPageSearchTrapdoorBase]
buttons=1
event1=EventBasementReadPageSearchTrapdoorTiePoint

[EventBasementReadPageSearchTrapdoorTiePoint]
buttons=1
event1=EventBasementReadPageSearchTrapdoorAfterGoto13

[EventBasementReadPageSearchTrapdoorAfterGoto13]
comment=@(114, 2)
buttons=1
event1=EventBasementEnd

[EventBasementTriggerSelector]
buttons=1
event1=EventBasementReadPagePlaceStartXferIfTriggered EventBasementReadPagePlaceDarknessXferIfTriggered EventBasementReadPagePlaceEvidenceXferIfTriggered EventBasementReadPagePlaceExploreDungeonCaveViaBasementXferIfTriggered EventBasementReadPagePlaceEndXferIfTriggered EventBasementReadPageSearchEvidenceXferIfTriggered EventBasementReadPageSearchTrapdoorXferIfTriggered EventBasementToc

[EventBasementReadPagePlaceStartXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,1 
buttons=1
event1=EventBasementReadPagePlaceStart

[EventBasementReadPagePlaceDarknessXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,2 
buttons=1
event1=EventBasementReadPagePlaceDarkness

[EventBasementReadPagePlaceDarkness]
operations=readBasementPreviousPage,=,2 readBasementPlaceDarkness,=,1
buttons=1
event1=EventBasementReadPagePlaceDarknessBeforeAddRemove1

[EventBasementReadPagePlaceDarknessBeforeAddRemove1]
comment=@(29, 2)
buttons=1
event1=EventBasementReadPagePlaceDarknessBeforeAddRemove2
add=TokenBasementDarkness1

[EventBasementReadPagePlaceDarknessBeforeAddRemove2]
comment=@(30, 2)
buttons=1
event1=EventBasementReadPagePlaceDarknessBeforeAddRemove3
add=TokenBasementDarkness2

[EventBasementReadPagePlaceDarknessBeforeAddRemove3]
comment=@(31, 2)
buttons=1
event1=EventBasementReadPagePlaceDarknessBeforeAddRemove4
add=TokenBasementDarkness3

[EventBasementReadPagePlaceDarknessBeforeAddRemove4]
comment=@(32, 2)
buttons=1
event1=EventBasementReadPagePlaceDarknessDisplay
add=TokenBasementDarkness4

[EventBasementReadPagePlaceDarknessDisplay]
buttons=1
event1=EventBasementReadPagePlaceDarknessBase

[EventBasementReadPagePlaceDarknessBase]
buttons=1
event1=EventBasementReadPagePlaceDarknessTiePoint

[EventBasementReadPagePlaceDarknessTiePoint]
buttons=1
event1=EventBasementReadPagePlaceDarknessEnd

[EventBasementReadPagePlaceDarknessEnd]
buttons=1
event1=EventBasementTiePoint

[EventBasementReadPagePlaceEvidenceXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,3 
buttons=1
event1=EventBasementReadPagePlaceEvidence

[EventBasementReadPagePlaceEvidence]
operations=readBasementPreviousPage,=,3 readBasementPlaceEvidence,=,1
buttons=1
event1=EventBasementReadPagePlaceEvidenceBeforeAddRemove1

[EventBasementReadPagePlaceEvidenceBeforeAddRemove1]
comment=@(44, 2)
buttons=1
event1=EventBasementReadPagePlaceEvidenceDisplay
add=TokenSearchBasementEvidence

[EventBasementReadPagePlaceEvidenceDisplay]
buttons=1
event1=EventBasementReadPagePlaceEvidenceBase

[EventBasementReadPagePlaceEvidenceBase]
buttons=1
event1=EventBasementReadPagePlaceEvidenceTiePoint

[EventBasementReadPagePlaceEvidenceTiePoint]
buttons=1
event1=EventBasementReadPagePlaceEvidenceEnd

[EventBasementReadPagePlaceEvidenceEnd]
buttons=1
event1=EventBasementTiePoint

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,4 
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasement

[EventBasementReadPagePlaceExploreDungeonCaveViaBasement]
operations=readBasementPreviousPage,=,4 readBasementPlaceExploreDungeonCaveViaBasement,=,1
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementBeforeAddRemove1

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementBeforeAddRemove1]
comment=@(56, 2)
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementDisplay
add=TokenSearchBasementTrapdoor

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementDisplay]
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementBase

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementBase]
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementTiePoint

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementTiePoint]
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementEnd

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementEnd]
buttons=1
event1=EventBasementTiePoint

[EventBasementReadPagePlaceEndXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,5 
buttons=1
event1=EventBasementReadPagePlaceEnd

[EventBasementReadPagePlaceEnd]
operations=readBasementPreviousPage,=,5 readBasementPlaceEnd,=,1
buttons=1
event1=EventBasementExpr7

[EventBasementExpr7]
comment=@(66, 5)
operations=EventBasementExpr7Temp,=,moveAfterExplore
buttons=1
event1=EventBasementReadPagePlaceEndBeforeTrigger1 EventBasementExpr8

[EventBasementReadPagePlaceEndBeforeTrigger1]
comment=@(66, 27)
operations=@MoveAfterExplore,=,1
vartests=VarOperation:EventBasementExpr7Temp,>,0 
buttons=1
event1=EventBasementExpr8

[EventBasementExpr8]
comment=@(67, 21)
operations=EventBasementExpr8Temp,=,0
buttons=1
event1=EventBasementReadPagePlaceEndBeforeLet2

[EventBasementReadPagePlaceEndBeforeLet2]
comment=@(67, 2)
operations=moveAfterExplore,=,EventBasementExpr8Temp
buttons=1
event1=EventBasementReadPagePlaceEndBeforeGoto11

[EventBasementReadPagePlaceEndBeforeGoto11]
comment=@(68, 2)
buttons=1
event1=EventBasementEnd

[EventBasementReadPageSearchEvidenceXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,6 
buttons=1
event1=EventBasementReadPageSearchEvidence

[EventBasementReadPageSearchTrapdoorXferIfTriggered]
operations=EventBasementTriggeredPageIndex,=,0
vartests=VarOperation:EventBasementTriggeredPageIndex,==,7 
buttons=1
event1=EventBasementReadPageSearchTrapdoor

[EventBasementToc]
buttons=1
event1=EventBasementTocSelector

[EventBasementTocSelector]
buttons=1
event1=EventBasementTocPrologProxyPlaceStart EventBasementTocPrologProxyPlaceDarkness EventBasementTocPrologProxyPlaceEvidence EventBasementTocPrologProxyPlaceExploreDungeonCaveViaBasement EventBasementTocPrologProxyPlaceEnd EventBasementTocPrologProxySearchEvidence EventBasementTocPrologProxySearchTrapdoor EventBasementTocNoPagesAvailable

[EventBasementTocPrologProxyPlaceStart]
vartests=VarOperation:readBasementPlaceStart,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementPlaceStart,>,0 
buttons=1
event1=EventBasementTocPrologPlaceStart

[EventBasementTocPrologProxyPlaceDarkness]
vartests=VarOperation:readBasementPlaceDarkness,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementPlaceDarkness,>,0 
buttons=1
event1=EventBasementTocPrologPlaceDarkness

[EventBasementTocPrologPlaceDarkness]
buttons=1
event1=EventBasementReadPagePlaceDarkness

[EventBasementTocPrologProxyPlaceEvidence]
vartests=VarOperation:readBasementPlaceEvidence,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementPlaceEvidence,>,0 
buttons=1
event1=EventBasementTocPrologPlaceEvidence

[EventBasementTocPrologPlaceEvidence]
buttons=1
event1=EventBasementReadPagePlaceEvidence

[EventBasementTocPrologProxyPlaceExploreDungeonCaveViaBasement]
vartests=VarOperation:readBasementPlaceExploreDungeonCaveViaBasement,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementPlaceExploreDungeonCaveViaBasement,>,0 
buttons=1
event1=EventBasementTocPrologPlaceExploreDungeonCaveViaBasement

[EventBasementTocPrologPlaceExploreDungeonCaveViaBasement]
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasement

[EventBasementTocPrologProxyPlaceEnd]
vartests=VarOperation:readBasementPlaceEnd,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementPlaceEnd,>,0 
buttons=1
event1=EventBasementTocPrologPlaceEnd

[EventBasementTocPrologPlaceEnd]
buttons=1
event1=EventBasementReadPagePlaceEnd

[EventBasementTocPrologProxySearchEvidence]
vartests=VarOperation:readBasementSearchEvidence,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementSearchEvidence,>,0 
buttons=1
event1=EventBasementTocPrologSearchEvidence

[EventBasementTocPrologProxySearchTrapdoor]
vartests=VarOperation:readBasementSearchTrapdoor,==,0 VarTestsLogicalOperator:AND VarOperation:visibleBasementSearchTrapdoor,>,0 
buttons=1
event1=EventBasementTocPrologSearchTrapdoor

[EventBasementTocNoPagesAvailable]
operations=EventBasementExit,=,1
buttons=1
event1=EventBasementTiePoint

[EventBasementReadPagePlaceStartTrigger]
operations=EventBasementTriggeredPageIndex,=,1
buttons=1
event1=EventBasementInit
trigger=VarExploreBasementViaDiningRoom

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementTrigger]
operations=EventBasementTriggeredPageIndex,=,4
buttons=1
event1=EventBasementExpr3
trigger=VarReadAboutExploreDungeonCaveViaBasement

[EventBasementExpr3]
comment=@(54, 64)
operations=EventBasementExpr3Temp,=,exploredBasement
buttons=1
event1=EventBasementExpr5 EventBasementExpr6

[EventBasementExpr5]
comment=@(54, 60)
operations=EventBasementExpr3Temp,=,1
vartests=VarOperation:EventBasementExpr3Temp,==,0 
buttons=1
event1=EventBasementExpr4

[EventBasementExpr4]
comment=@(54, 60)
buttons=1
event1=EventBasementReadPagePlaceExploreDungeonCaveViaBasementTriggerFail EventBasementInit

[EventBasementReadPagePlaceExploreDungeonCaveViaBasementTriggerFail]
vartests=VarOperation:EventBasementExpr3Temp,==,0 
buttons=1
event1=EventBasementEnd

[EventBasementExpr6]
comment=@(54, 60)
operations=EventBasementExpr3Temp,=,0
buttons=1
event1=EventBasementExpr4

[EventBasementReadPageSearchEvidenceTrigger]
operations=EventBasementTriggeredPageIndex,=,6
buttons=1
event1=EventBasementInit
trigger=VarSearchBasementEvidence

[EventBasementReadPageSearchTrapdoorTrigger]
operations=EventBasementTriggeredPageIndex,=,7
buttons=1
event1=EventBasementInit
trigger=VarSearchBasementTrapdoor
