; Saved by version: 3.0.4

[EventBenAfterStart]
operations=BenAfterTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBenAfterInit

[EventBenAfterInit]
operations=EventBenAfterExit,=,1
display=false
buttons=1
event1=EventBenAfterFirstTimeInitializer EventBenAfterToc

[EventBenAfterFirstTimeInitializer]
operations=EventBenAfterInitialized,=,1 visibleBenAfterDirt,=,1 visibleBenAfterFootprints,=,1 visibleBenAfterAnythingElse,=,1
vartests=VarOperation:EventBenAfterInitialized,==,0 
display=false
buttons=1
event1=EventBenAfterToc

[EventBenAfterToc]
display=false
buttons=1
event1=EventBenAfterTocSelector

[EventBenAfterTocSelector]
display=false
buttons=1
event1=EventBenAfterToc0 EventBenAfterToc1 EventBenAfterToc2 EventBenAfterTocTiePoint

[EventBenAfterToc0]
vartests=VarOperation:readBenAfterPreviousPage,==,0 
buttons=4
event1=EventBenAfterReadPageDirt
event1Condition=VarOperation:visibleBenAfterDirt,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBenAfterReadPageFootprints
event2Condition=VarOperation:visibleBenAfterFootprints,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBenAfterReadPageAnythingElse
event3Condition=VarOperation:visibleBenAfterAnythingElse,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBenAfterReadPageDirt]
display=false
buttons=1
event1=EventBenAfterExpr2

[EventBenAfterExpr2]
comment=@(21, 15)
operations=EventBenAfterExpr2Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBenAfterExpr3 EventBenAfterExpr4

[EventBenAfterExpr3]
comment=@(21, 11)
operations=EventBenAfterExpr2Temp,=,1
vartests=VarOperation:EventBenAfterExpr2Temp,==,0 
display=false
buttons=1
event1=EventBenAfterReadPageDirtDisplay

[EventBenAfterReadPageDirtDisplay]
display=false
buttons=1
event1=EventBenAfterReadPageDirtOverload1 EventBenAfterReadPageDirtBase

[EventBenAfterReadPageDirtOverload1]
operations=readBenAfterDirt,=,1
vartests=VarOperation:EventBenAfterExpr2Temp,>,0 
buttons=1
event1=EventBenAfterReadPageDirtTiePoint

[EventBenAfterReadPageDirtTiePoint]
operations=readBenAfterPreviousPage,=,1 readBenAfterDirt,=,1 readBenAfterPreviousPage,=,1
display=false
buttons=1
event1=EventBenAfterReadPageDirtTestEnd EventBenAfterReadPageDirtEnd

[EventBenAfterReadPageDirtTestEnd]
operations=readBenAfterFinished,=,1
vartests=VarOperation:readEventBenAfterReadPageDirtFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBenAfterReadPageDirtEnd

[EventBenAfterReadPageDirtEnd]
display=false
buttons=1
event1=EventBenAfterTiePoint

[EventBenAfterTiePoint]
display=false
buttons=1
event1=EventBenAfterClearTrigger

[EventBenAfterClearTrigger]
operations=BenAfterTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventBenAfterLoopBack EventBenAfterEnd

[EventBenAfterLoopBack]
vartests=VarOperation:EventBenAfterExit,==,0 
display=false
buttons=1
event1=EventBenAfterInit

[EventBenAfterEnd]
display=false
buttons=1
event1=

[EventBenAfterReadPageDirtBase]
buttons=1
event1=EventBenAfterReadPageDirtTiePoint

[EventBenAfterExpr4]
comment=@(21, 11)
operations=EventBenAfterExpr2Temp,=,0
display=false
buttons=1
event1=EventBenAfterReadPageDirtDisplay

[EventBenAfterReadPageFootprints]
display=false
buttons=1
event1=EventBenAfterExpr5

[EventBenAfterExpr5]
comment=@(35, 15)
operations=EventBenAfterExpr5Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBenAfterExpr6 EventBenAfterExpr7

[EventBenAfterExpr6]
comment=@(35, 11)
operations=EventBenAfterExpr5Temp,=,1
vartests=VarOperation:EventBenAfterExpr5Temp,==,0 
display=false
buttons=1
event1=EventBenAfterReadPageFootprintsDisplay

[EventBenAfterReadPageFootprintsDisplay]
display=false
buttons=1
event1=EventBenAfterReadPageFootprintsOverload1 EventBenAfterReadPageFootprintsBase

[EventBenAfterReadPageFootprintsOverload1]
operations=readBenAfterFootprints,=,1
vartests=VarOperation:EventBenAfterExpr5Temp,>,0 
buttons=1
event1=EventBenAfterReadPageFootprintsTiePoint

[EventBenAfterReadPageFootprintsTiePoint]
operations=readBenAfterPreviousPage,=,2 readBenAfterFootprints,=,1 readBenAfterPreviousPage,=,2
display=false
buttons=1
event1=EventBenAfterReadPageFootprintsTestEnd EventBenAfterReadPageFootprintsEnd

[EventBenAfterReadPageFootprintsTestEnd]
operations=readBenAfterFinished,=,1
vartests=VarOperation:readEventBenAfterReadPageFootprintsFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBenAfterReadPageFootprintsEnd

[EventBenAfterReadPageFootprintsEnd]
display=false
buttons=1
event1=EventBenAfterTiePoint

[EventBenAfterReadPageFootprintsBase]
buttons=1
event1=EventBenAfterReadPageFootprintsTiePoint

[EventBenAfterExpr7]
comment=@(35, 11)
operations=EventBenAfterExpr5Temp,=,0
display=false
buttons=1
event1=EventBenAfterReadPageFootprintsDisplay

[EventBenAfterReadPageAnythingElse]
display=false
buttons=1
event1=EventBenAfterExpr8

[EventBenAfterExpr8]
comment=@(59, 15)
operations=EventBenAfterExpr8Temp,=,exploredBackyardNicely
display=false
buttons=1
event1=EventBenAfterExpr9 EventBenAfterExpr10

[EventBenAfterExpr9]
comment=@(59, 11)
operations=EventBenAfterExpr8Temp,=,1
vartests=VarOperation:EventBenAfterExpr8Temp,==,0 
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseAddRemoveBefore1

[EventBenAfterReadPageAnythingElseAddRemoveBefore1]
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseAddRemoveBefore2
remove=TokenBackyardBenAfter

[EventBenAfterReadPageAnythingElseAddRemoveBefore2]
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseTriggerBefore3
add=TokenExploreBackDoorLocked TokenInvestigatorsDiningRoom

[EventBenAfterReadPageAnythingElseTriggerBefore3]
operations=@ClearAllMythosFlags,=,1
display=false
buttons=1
event1=EventBenAfterExpr11

[EventBenAfterExpr11]
comment=@(79, 16)
operations=EventBenAfterExpr11Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore4

[EventBenAfterReadPageAnythingElseLetBefore4]
operations=$mythosHelp,=,EventBenAfterExpr11Temp
display=false
buttons=1
event1=EventBenAfterExpr12

[EventBenAfterExpr12]
comment=@(80, 18)
operations=EventBenAfterExpr12Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore5

[EventBenAfterReadPageAnythingElseLetBefore5]
operations=$mythosFlavor,=,EventBenAfterExpr12Temp
display=false
buttons=1
event1=EventBenAfterExpr13

[EventBenAfterExpr13]
comment=@(81, 17)
operations=EventBenAfterExpr13Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore6

[EventBenAfterReadPageAnythingElseLetBefore6]
operations=$mythosMinor,=,EventBenAfterExpr13Temp
display=false
buttons=1
event1=EventBenAfterExpr14

[EventBenAfterExpr14]
comment=@(82, 19)
operations=EventBenAfterExpr14Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore7

[EventBenAfterReadPageAnythingElseLetBefore7]
operations=$mythosIndoors,=,EventBenAfterExpr14Temp
display=false
buttons=1
event1=EventBenAfterExpr15

[EventBenAfterExpr15]
comment=@(83, 21)
operations=EventBenAfterExpr15Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore8

[EventBenAfterReadPageAnythingElseLetBefore8]
operations=$MythosKey,=,EventBenAfterExpr15Temp
display=false
buttons=1
event1=EventBenAfterExpr16

[EventBenAfterExpr16]
comment=@(84, 25)
operations=EventBenAfterExpr16Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore9

[EventBenAfterReadPageAnythingElseLetBefore9]
operations=$mythosDiningRoom,=,EventBenAfterExpr16Temp
display=false
buttons=1
event1=EventBenAfterExpr17

[EventBenAfterExpr17]
comment=@(86, 28)
operations=EventBenAfterExpr17Temp,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore10

[EventBenAfterReadPageAnythingElseLetBefore10]
operations=talkedToBenAnythingElse,=,EventBenAfterExpr17Temp
display=false
buttons=1
event1=EventBenAfterExpr18

[EventBenAfterExpr18]
comment=@(87, 27)
operations=EventBenAfterExpr18Temp,=,talkedToBenCount
display=false
buttons=1
event1=EventBenAfterExpr19

[EventBenAfterExpr19]
comment=@(87, 46)
operations=EventBenAfterExpr19Temp,=,1
display=false
buttons=1
event1=EventBenAfterExpr20

[EventBenAfterExpr20]
comment=@(87, 27)
operations=EventBenAfterExpr18Temp,+,EventBenAfterExpr19Temp
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseLetBefore11

[EventBenAfterReadPageAnythingElseLetBefore11]
operations=talkedToBenCount,=,EventBenAfterExpr18Temp
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseTriggerBefore12

[EventBenAfterReadPageAnythingElseTriggerBefore12]
operations=@TalkedToBenAfter,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseDisplay

[EventBenAfterReadPageAnythingElseDisplay]
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseOverload1 EventBenAfterReadPageAnythingElseBase

[EventBenAfterReadPageAnythingElseOverload1]
operations=readBenAfterAnythingElse,=,1
vartests=VarOperation:EventBenAfterExpr8Temp,>,0 
buttons=1
event1=EventBenAfterReadPageAnythingElseTiePoint

[EventBenAfterReadPageAnythingElseTiePoint]
operations=readBenAfterPreviousPage,=,3 readBenAfterAnythingElse,=,1 readBenAfterPreviousPage,=,3
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseAddRemoveAfter1

[EventBenAfterReadPageAnythingElseAddRemoveAfter1]
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseExitAfter2
remove=TokenInvestigatorsDiningRoom

[EventBenAfterReadPageAnythingElseExitAfter2]
operations=EventBenAfterExit,=,1
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseTestEnd EventBenAfterReadPageAnythingElseEnd

[EventBenAfterReadPageAnythingElseTestEnd]
operations=readBenAfterFinished,=,1
vartests=VarOperation:readEventBenAfterReadPageAnythingElseFinished,==,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseEnd

[EventBenAfterReadPageAnythingElseEnd]
display=false
buttons=1
event1=EventBenAfterTiePoint

[EventBenAfterReadPageAnythingElseBase]
buttons=1
event1=EventBenAfterReadPageAnythingElseTiePoint

[EventBenAfterExpr10]
comment=@(59, 11)
operations=EventBenAfterExpr8Temp,=,0
display=false
buttons=1
event1=EventBenAfterReadPageAnythingElseAddRemoveBefore1

[EventBenAfterToc1]
vartests=VarOperation:readBenAfterPreviousPage,==,1 
buttons=4
event1=EventBenAfterReadPageDirt
event1Condition=VarOperation:visibleBenAfterDirt,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBenAfterReadPageFootprints
event2Condition=VarOperation:visibleBenAfterFootprints,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBenAfterReadPageAnythingElse
event3Condition=VarOperation:visibleBenAfterAnythingElse,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBenAfterToc2]
vartests=VarOperation:readBenAfterPreviousPage,==,2 
buttons=4
event1=EventBenAfterReadPageDirt
event1Condition=VarOperation:visibleBenAfterDirt,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterDirt,==,0 
event1ConditionAction=hide
event2=EventBenAfterReadPageFootprints
event2Condition=VarOperation:visibleBenAfterFootprints,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterFootprints,==,0 
event2ConditionAction=hide
event3=EventBenAfterReadPageAnythingElse
event3Condition=VarOperation:visibleBenAfterAnythingElse,==,0 VarTestsLogicalOperator:OR VarOperation:readBenAfterAnythingElse,==,0 
event3ConditionAction=hide
event4=

[EventBenAfterTocTiePoint]
display=false
buttons=1
event1=EventBenAfterTocIsFinished EventBenAfterClearTrigger

[EventBenAfterTocIsFinished]
operations=readBenAfterFinished,=,1
vartests=VarOperation:readBenAfterDirt,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterFootprints,>,0 VarTestsLogicalOperator:AND VarOperation:readBenAfterAnythingElse,>,0 
display=false
buttons=1
event1=EventBenAfterClearTrigger
