; Saved by version: 3.15

[EventDungeonCaveStart]
operations=DungeonCaveTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventDungeonCaveInit

[EventDungeonCaveInit]
operations=EventDungeonCaveExit,=,0
display=false
buttons=1
event1=EventDungeonCaveFirstTimeInitializer EventDungeonCaveExpr11

[EventDungeonCaveFirstTimeInitializer]
operations=initializedDungeonCave,=,1 visibleDungeonCaveExploreViaCrypt,=,1 visibleDungeonCaveExploreViaBasement,=,1 visibleDungeonCavePlaceExploreCrypt,=,1 visibleDungeonCavePlaceExploreTortureChamber,=,1
vartests=VarOperation:initializedDungeonCave,==,0 
display=false
buttons=1
event1=EventDungeonCaveExpr11

[EventDungeonCaveExpr11]
comment=@(6, 2)
operations=EventDungeonCaveReadPageExploreViaCryptExpr1TempA,=,0
display=false
buttons=1
event1=EventDungeonCaveExpr12

[EventDungeonCaveExpr12]
comment=@(6, 2)
operations=visibleDungeonCaveExploreViaCrypt,=,EventDungeonCaveReadPageExploreViaCryptExpr1TempA
display=false
buttons=1
event1=EventDungeonCaveExpr13

[EventDungeonCaveExpr13]
comment=@(36, 2)
operations=EventDungeonCaveReadPageExploreViaBasementExpr2TempA,=,0
display=false
buttons=1
event1=EventDungeonCaveExpr14

[EventDungeonCaveExpr14]
comment=@(36, 2)
operations=visibleDungeonCaveExploreViaBasement,=,EventDungeonCaveReadPageExploreViaBasementExpr2TempA
display=false
buttons=1
event1=EventDungeonCaveExpr15

[EventDungeonCaveExpr15]
comment=@(71, 2)
operations=EventDungeonCaveReadPagePlaceExploreCryptExpr3TempA,=,0
display=false
buttons=1
event1=EventDungeonCaveExpr16

[EventDungeonCaveExpr16]
comment=@(71, 2)
operations=visibleDungeonCavePlaceExploreCrypt,=,EventDungeonCaveReadPagePlaceExploreCryptExpr3TempA
display=false
buttons=1
event1=EventDungeonCaveExpr17

[EventDungeonCaveExpr17]
comment=@(85, 2)
operations=EventDungeonCaveReadPagePlaceExploreTortureChamberExpr4TempA,=,0
display=false
buttons=1
event1=EventDungeonCaveExpr18

[EventDungeonCaveExpr18]
comment=@(85, 2)
operations=visibleDungeonCavePlaceExploreTortureChamber,=,EventDungeonCaveReadPagePlaceExploreTortureChamberExpr4TempA
display=false
buttons=1
event1=EventDungeonCaveTriggerPrologSelector

[EventDungeonCaveTriggerPrologSelector]
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptTriggeredPrologTarget EventDungeonCaveReadPageExploreViaBasementTriggeredPrologTarget EventDungeonCaveTriggerSelector

[EventDungeonCaveReadPageExploreViaCryptTriggeredPrologTarget]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventDungeonCaveTocPrologExploreViaCrypt

[EventDungeonCaveTocPrologExploreViaCrypt]
buttons=2
event1=EventDungeonCaveReadPageExploreViaCrypt
event2=EventDungeonCaveEnd

[EventDungeonCaveReadPageExploreViaCrypt]
operations=readDungeonCavePreviousPage,=,1 readDungeonCaveExploreViaCrypt,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove1

[EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove1]
comment=@(17, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove2
remove=UIHighlightTokenExploreDungeonCaveViaCrypt TokenExploreDungeonCaveViaCrypt

[EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove2]
comment=@(18, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove3
remove=UIHighlightTokenExploreDungeonCaveViaBasement TokenExploreDungeonCaveViaBasement

[EventDungeonCaveReadPageExploreViaCryptBeforeAddRemove3]
comment=@(19, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptDisplay
add=TileTortureChamber UIHighlightTokenDungeonCaveWall TokenDungeonCaveWall

[EventDungeonCaveReadPageExploreViaCryptDisplay]
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptBase

[EventDungeonCaveReadPageExploreViaCryptBase]
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptTiePoint

[EventDungeonCaveReadPageExploreViaCryptTiePoint]
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptRemoveHighlights

[EventDungeonCaveReadPageExploreViaCryptRemoveHighlights]
display=false
buttons=1
event1=EventDungeonCaveExpr1
remove=UIHighlightTokenDungeonCaveWall

[EventDungeonCaveExpr1]
comment=@(30, 32)
operations=EventDungeonCaveExpr1Temp,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptAfterLet1

[EventDungeonCaveReadPageExploreViaCryptAfterLet1]
comment=@(30, 2)
operations=exploredDungeonCaveViaCrypt,=,EventDungeonCaveExpr1Temp
display=false
buttons=1
event1=EventDungeonCaveExpr2

[EventDungeonCaveExpr2]
comment=@(31, 24)
operations=EventDungeonCaveExpr2Temp,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptAfterLet2

[EventDungeonCaveReadPageExploreViaCryptAfterLet2]
comment=@(31, 2)
operations=exploredDungeonCave,=,EventDungeonCaveExpr2Temp
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptAfterGoto87

[EventDungeonCaveReadPageExploreViaCryptAfterGoto87]
comment=@(32, 2)
operations=EventDungeonCaveTriggeredPageIndex,=,4
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveTiePoint]
display=false
buttons=1
event1=EventDungeonCaveLoopBack EventDungeonCaveEnd

[EventDungeonCaveLoopBack]
vartests=VarOperation:EventDungeonCaveExit,==,0 
display=false
buttons=1
event1=EventDungeonCaveInit

[EventDungeonCaveEnd]
display=false
buttons=1
event1=

[EventDungeonCaveReadPageExploreViaBasementTriggeredPrologTarget]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventDungeonCaveTocPrologExploreViaBasement

[EventDungeonCaveTocPrologExploreViaBasement]
buttons=2
event1=EventDungeonCaveReadPageExploreViaBasement
event2=EventDungeonCaveEnd

[EventDungeonCaveReadPageExploreViaBasement]
operations=readDungeonCavePreviousPage,=,2 readDungeonCaveExploreViaBasement,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementBeforeAddRemove1

[EventDungeonCaveReadPageExploreViaBasementBeforeAddRemove1]
comment=@(45, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementBeforeAddRemove2
remove=UIHighlightTokenExploreDungeonCaveViaBasement TokenExploreDungeonCaveViaBasement UIHighlightTokenDungeonCaveWall TokenDungeonCaveWall

[EventDungeonCaveReadPageExploreViaBasementBeforeAddRemove2]
comment=@(46, 2)
display=false
buttons=1
event1=EventDungeonCaveExpr3
add=TileTortureChamber

[EventDungeonCaveExpr3]
comment=@(58, 5)
operations=EventDungeonCaveExpr3Temp,=,exploredDungeonCave
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementDisplay

[EventDungeonCaveReadPageExploreViaBasementDisplay]
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementOverload1 EventDungeonCaveReadPageExploreViaBasementBase

[EventDungeonCaveReadPageExploreViaBasementOverload1]
vartests=VarOperation:EventDungeonCaveExpr3Temp,>,0 
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementTiePoint

[EventDungeonCaveReadPageExploreViaBasementTiePoint]
display=false
buttons=1
event1=EventDungeonCaveExpr4

[EventDungeonCaveExpr4]
comment=@(65, 24)
operations=EventDungeonCaveExpr4Temp,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementAfterLet1

[EventDungeonCaveReadPageExploreViaBasementAfterLet1]
comment=@(65, 2)
operations=exploredDungeonCave,=,EventDungeonCaveExpr4Temp
display=false
buttons=1
event1=EventDungeonCaveExpr5

[EventDungeonCaveExpr5]
comment=@(66, 35)
operations=EventDungeonCaveExpr5Temp,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementAfterLet2

[EventDungeonCaveReadPageExploreViaBasementAfterLet2]
comment=@(66, 2)
operations=exploredDungeonCaveViaBasement,=,EventDungeonCaveExpr5Temp
display=false
buttons=1
event1=EventDungeonCaveExpr6

[EventDungeonCaveExpr6]
comment=@(67, 9)
operations=EventDungeonCaveExpr6Temp,=,exploredCrypt
display=false
buttons=1
event1=EventDungeonCaveExpr8 EventDungeonCaveExpr9

[EventDungeonCaveExpr8]
comment=@(67, 5)
operations=EventDungeonCaveExpr6Temp,=,1
vartests=VarOperation:EventDungeonCaveExpr6Temp,==,0 
display=false
buttons=1
event1=EventDungeonCaveExpr7

[EventDungeonCaveExpr7]
comment=@(67, 5)
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementAfterGoto88 EventDungeonCaveReadPageExploreViaBasementEnd

[EventDungeonCaveReadPageExploreViaBasementAfterGoto88]
comment=@(67, 28)
operations=EventDungeonCaveTriggeredPageIndex,=,3
vartests=VarOperation:EventDungeonCaveExpr6Temp,>,0 
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveReadPageExploreViaBasementEnd]
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveExpr9]
comment=@(67, 5)
operations=EventDungeonCaveExpr6Temp,=,0
display=false
buttons=1
event1=EventDungeonCaveExpr7

[EventDungeonCaveReadPageExploreViaBasementBase]
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasementTiePoint

[EventDungeonCaveTriggerSelector]
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCryptXferIfTriggered EventDungeonCaveReadPageExploreViaBasementXferIfTriggered EventDungeonCaveReadPagePlaceExploreCryptXferIfTriggered EventDungeonCaveReadPagePlaceExploreTortureChamberXferIfTriggered EventDungeonCaveToc

[EventDungeonCaveReadPageExploreViaCryptXferIfTriggered]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaCrypt

[EventDungeonCaveReadPageExploreViaBasementXferIfTriggered]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventDungeonCaveReadPageExploreViaBasement

[EventDungeonCaveReadPagePlaceExploreCryptXferIfTriggered]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCrypt

[EventDungeonCaveReadPagePlaceExploreCrypt]
operations=readDungeonCavePreviousPage,=,3 readDungeonCavePlaceExploreCrypt,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptBeforeAddRemove1

[EventDungeonCaveReadPagePlaceExploreCryptBeforeAddRemove1]
comment=@(73, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptDisplay
add=UIHighlightTokenExploreCryptViaDungeonCave TokenExploreCryptViaDungeonCave

[EventDungeonCaveReadPagePlaceExploreCryptDisplay]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptBase

[EventDungeonCaveReadPagePlaceExploreCryptBase]
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptTiePoint

[EventDungeonCaveReadPagePlaceExploreCryptTiePoint]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptRemoveHighlights

[EventDungeonCaveReadPagePlaceExploreCryptRemoveHighlights]
display=false
buttons=1
event1=EventDungeonCaveExpr10
remove=UIHighlightTokenExploreCryptViaDungeonCave

[EventDungeonCaveExpr10]
comment=@(80, 24)
operations=EventDungeonCaveExpr10Temp,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptAfterLet1

[EventDungeonCaveReadPagePlaceExploreCryptAfterLet1]
comment=@(80, 2)
operations=exploredDungeonCave,=,EventDungeonCaveExpr10Temp
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCryptAfterGoto89

[EventDungeonCaveReadPagePlaceExploreCryptAfterGoto89]
comment=@(81, 2)
operations=EventDungeonCaveTriggeredPageIndex,=,4
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveReadPagePlaceExploreTortureChamberXferIfTriggered]
operations=EventDungeonCaveTriggeredPageIndex,=,0
vartests=VarOperation:EventDungeonCaveTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamber

[EventDungeonCaveReadPagePlaceExploreTortureChamber]
operations=readDungeonCavePreviousPage,=,4 readDungeonCavePlaceExploreTortureChamber,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberBeforeAddRemove1

[EventDungeonCaveReadPagePlaceExploreTortureChamberBeforeAddRemove1]
comment=@(87, 2)
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberDisplay
add=UIHighlightTokenExploreTortureChamberViaDungeonCave TokenExploreTortureChamberViaDungeonCave

[EventDungeonCaveReadPagePlaceExploreTortureChamberDisplay]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberBase

[EventDungeonCaveReadPagePlaceExploreTortureChamberBase]
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberTiePoint

[EventDungeonCaveReadPagePlaceExploreTortureChamberTiePoint]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberRemoveHighlights

[EventDungeonCaveReadPagePlaceExploreTortureChamberRemoveHighlights]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberAfterTrigger1
remove=UIHighlightTokenExploreTortureChamberViaDungeonCave

[EventDungeonCaveReadPagePlaceExploreTortureChamberAfterTrigger1]
comment=@(93, 2)
operations=@MoveAfterExplore,=,1
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamberAfterGoto90

[EventDungeonCaveReadPagePlaceExploreTortureChamberAfterGoto90]
comment=@(94, 2)
operations=EventDungeonCaveExit,=,1
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveToc]
display=false
buttons=1
event1=EventDungeonCaveTocSelector

[EventDungeonCaveTocSelector]
display=false
buttons=1
event1=EventDungeonCaveTocPrologProxyExploreViaCrypt EventDungeonCaveTocPrologProxyExploreViaBasement EventDungeonCaveTocPrologProxyPlaceExploreCrypt EventDungeonCaveTocPrologProxyPlaceExploreTortureChamber EventDungeonCaveTocNoPagesAvailable

[EventDungeonCaveTocPrologProxyExploreViaCrypt]
vartests=VarOperation:readDungeonCaveExploreViaCrypt,==,0 VarTestsLogicalOperator:AND VarOperation:visibleDungeonCaveExploreViaCrypt,>,0 
display=false
buttons=1
event1=EventDungeonCaveTocPrologExploreViaCrypt

[EventDungeonCaveTocPrologProxyExploreViaBasement]
vartests=VarOperation:readDungeonCaveExploreViaBasement,==,0 VarTestsLogicalOperator:AND VarOperation:visibleDungeonCaveExploreViaBasement,>,0 
display=false
buttons=1
event1=EventDungeonCaveTocPrologExploreViaBasement

[EventDungeonCaveTocPrologProxyPlaceExploreCrypt]
vartests=VarOperation:readDungeonCavePlaceExploreCrypt,==,0 VarTestsLogicalOperator:AND VarOperation:visibleDungeonCavePlaceExploreCrypt,>,0 
display=false
buttons=1
event1=EventDungeonCaveTocPrologPlaceExploreCrypt

[EventDungeonCaveTocPrologPlaceExploreCrypt]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreCrypt

[EventDungeonCaveTocPrologProxyPlaceExploreTortureChamber]
vartests=VarOperation:readDungeonCavePlaceExploreTortureChamber,==,0 VarTestsLogicalOperator:AND VarOperation:visibleDungeonCavePlaceExploreTortureChamber,>,0 
display=false
buttons=1
event1=EventDungeonCaveTocPrologPlaceExploreTortureChamber

[EventDungeonCaveTocPrologPlaceExploreTortureChamber]
display=false
buttons=1
event1=EventDungeonCaveReadPagePlaceExploreTortureChamber

[EventDungeonCaveTocNoPagesAvailable]
operations=EventDungeonCaveExit,=,1
display=false
buttons=1
event1=EventDungeonCaveTiePoint

[EventDungeonCaveReadPageExploreViaCryptTrigger]
operations=EventDungeonCaveTriggeredPageIndex,=,1
display=false
buttons=1
event1=EventDungeonCaveInit
trigger=VarExploreDungeonCaveViaCrypt

[EventDungeonCaveReadPageExploreViaBasementTrigger]
operations=EventDungeonCaveTriggeredPageIndex,=,2
display=false
buttons=1
event1=EventDungeonCaveInit
trigger=VarExploreDungeonCaveViaBasement
