; Saved by version: 3.0.4

[EventDvmClosePortalStart]
operations=DvmClosePortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventDvmClosePortalInit

[EventDvmClosePortalInit]
operations=EventDvmClosePortalExit,=,0
display=false
buttons=1
event1=EventDvmClosePortalFirstTimeInitializer EventDvmClosePortalOrderedToc

[EventDvmClosePortalFirstTimeInitializer]
operations=EventDvmClosePortalInitialized,=,1 DvmClosePortalPage1Visible,=,1 DvmClosePortalPage2Visible,=,1 DvmClosePortalPage3Visible,=,1 DvmClosePortalPage4Visible,=,1 DvmClosePortalPage5Visible,=,1
vartests=VarOperation:EventDvmClosePortalInitialized,==,0 
display=false
buttons=1
event1=EventDvmClosePortalOrderedToc

[EventDvmClosePortalOrderedToc]
display=false
buttons=1
event1=EventDvmClosePortalTocSelector

[EventDvmClosePortalTocSelector]
display=false
buttons=1
event1=EventDvmClosePortalOrderedToc0 EventDvmClosePortalOrderedToc1 EventDvmClosePortalOrderedToc2 EventDvmClosePortalOrderedToc3 EventDvmClosePortalOrderedToc4 EventDvmClosePortalOrderedToc5

[EventDvmClosePortalOrderedToc0]
vartests=VarOperation:DvmClosePortalPage1Visible,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage1,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage2,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage5,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalEpilog,==,0 
buttons=3
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=

[EventDvmClosePortalReadPagePage1]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage1Display

[EventDvmClosePortalReadPagePage1Display]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage1Base

[EventDvmClosePortalReadPagePage1Base]
buttons=1
event1=EventDvmClosePortalReadPagePage1TiePoint

[EventDvmClosePortalReadPagePage1TiePoint]
operations=readDvmClosePortalPreviousPage,=,1 readDvmClosePortalPage1,=,1
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage1End

[EventDvmClosePortalReadPagePage1End]
display=false
buttons=1
event1=EventDvmClosePortalTiePoint

[EventDvmClosePortalTiePoint]
display=false
buttons=1
event1=EventDvmClosePortalClearTrigger

[EventDvmClosePortalClearTrigger]
operations=DvmClosePortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventDvmClosePortalLoopBack EventDvmClosePortalEnd

[EventDvmClosePortalLoopBack]
vartests=VarOperation:EventDvmClosePortalExit,==,0 
display=false
buttons=1
event1=EventDvmClosePortalInit

[EventDvmClosePortalEnd]
display=false
buttons=1
event1=

[EventDvmClosePortalOrderedToc1]
vartests=VarOperation:DvmClosePortalPage2Visible,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage2,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage5,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalEpilog,==,0 
buttons=5
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=EventDvmClosePortalReadPagePage2
event3Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,>,0 
event3ConditionAction=hide
event4=EventDvmClosePortalReadPagePage2
event4Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,==,0 
event4ConditionAction=hide
event5=

[EventDvmClosePortalReadPagePage2]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage2Display

[EventDvmClosePortalReadPagePage2Display]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage2Base

[EventDvmClosePortalReadPagePage2Base]
buttons=1
event1=EventDvmClosePortalReadPagePage2TiePoint

[EventDvmClosePortalReadPagePage2TiePoint]
operations=readDvmClosePortalPreviousPage,=,2 readDvmClosePortalPage2,=,1
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage2End

[EventDvmClosePortalReadPagePage2End]
display=false
buttons=1
event1=EventDvmClosePortalTiePoint

[EventDvmClosePortalOrderedToc2]
vartests=VarOperation:DvmClosePortalPage3Visible,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage5,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalEpilog,==,0 
buttons=7
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=EventDvmClosePortalReadPagePage2
event3Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,>,0 
event3ConditionAction=hide
event4=EventDvmClosePortalReadPagePage2
event4Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,==,0 
event4ConditionAction=hide
event5=EventDvmClosePortalReadPagePage3
event5Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,>,0 
event5ConditionAction=hide
event6=EventDvmClosePortalReadPagePage3
event6Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,==,0 
event6ConditionAction=hide
event7=

[EventDvmClosePortalReadPagePage3]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage3Display

[EventDvmClosePortalReadPagePage3Display]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage3Base

[EventDvmClosePortalReadPagePage3Base]
buttons=1
event1=EventDvmClosePortalReadPagePage3TiePoint

[EventDvmClosePortalReadPagePage3TiePoint]
operations=readDvmClosePortalPreviousPage,=,3 readDvmClosePortalPage3,=,1
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage3End

[EventDvmClosePortalReadPagePage3End]
display=false
buttons=1
event1=EventDvmClosePortalTiePoint

[EventDvmClosePortalOrderedToc3]
vartests=VarOperation:DvmClosePortalPage4Visible,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage5,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalEpilog,==,0 
buttons=9
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=EventDvmClosePortalReadPagePage2
event3Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,>,0 
event3ConditionAction=hide
event4=EventDvmClosePortalReadPagePage2
event4Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,==,0 
event4ConditionAction=hide
event5=EventDvmClosePortalReadPagePage3
event5Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,>,0 
event5ConditionAction=hide
event6=EventDvmClosePortalReadPagePage3
event6Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,==,0 
event6ConditionAction=hide
event7=EventDvmClosePortalReadPagePage4
event7Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,>,0 
event7ConditionAction=hide
event8=EventDvmClosePortalReadPagePage4
event8Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,==,0 
event8ConditionAction=hide
event9=

[EventDvmClosePortalReadPagePage4]
display=false
buttons=1
event1=EventDvmClosePortalExpr5

[EventDvmClosePortalExpr5]
comment=@(113, 5)
operations=EventDvmClosePortalExpr5Temp,=,readJournalPage5
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage4Display

[EventDvmClosePortalReadPagePage4Display]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage4Overload1 EventDvmClosePortalReadPagePage4Base

[EventDvmClosePortalReadPagePage4Overload1]
operations=readDvmClosePortalPage4,=,1
vartests=VarOperation:EventDvmClosePortalExpr5Temp,>,0 
buttons=1
event1=EventDvmClosePortalReadPagePage4TiePoint

[EventDvmClosePortalReadPagePage4TiePoint]
operations=readDvmClosePortalPreviousPage,=,4 readDvmClosePortalPage4,=,1
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage4End

[EventDvmClosePortalReadPagePage4End]
display=false
buttons=1
event1=EventDvmClosePortalTiePoint

[EventDvmClosePortalReadPagePage4Base]
buttons=1
event1=EventDvmClosePortalReadPagePage4TiePoint

[EventDvmClosePortalOrderedToc4]
vartests=VarOperation:DvmClosePortalPage5Visible,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalPage5,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmClosePortalEpilog,==,0 
buttons=11
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=EventDvmClosePortalReadPagePage2
event3Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,>,0 
event3ConditionAction=hide
event4=EventDvmClosePortalReadPagePage2
event4Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,==,0 
event4ConditionAction=hide
event5=EventDvmClosePortalReadPagePage3
event5Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,>,0 
event5ConditionAction=hide
event6=EventDvmClosePortalReadPagePage3
event6Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,==,0 
event6ConditionAction=hide
event7=EventDvmClosePortalReadPagePage4
event7Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,>,0 
event7ConditionAction=hide
event8=EventDvmClosePortalReadPagePage4
event8Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,==,0 
event8ConditionAction=hide
event9=EventDvmClosePortalReadPagePage5
event9Condition=VarOperation:DvmClosePortalPage5Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage5,>,0 
event9ConditionAction=hide
event10=EventDvmClosePortalReadPagePage5
event10Condition=VarOperation:DvmClosePortalPage5Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage5,==,0 
event10ConditionAction=hide
event11=

[EventDvmClosePortalReadPagePage5]
display=false
buttons=1
event1=EventDvmClosePortalExpr6

[EventDvmClosePortalExpr6]
comment=@(150, 11)
operations=EventDvmClosePortalExpr6Temp,=,readAboutBoy
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage5Display

[EventDvmClosePortalReadPagePage5Display]
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage5Overload1 EventDvmClosePortalReadPagePage5Base

[EventDvmClosePortalReadPagePage5Overload1]
operations=readDvmClosePortalPage5,=,1
vartests=VarOperation:EventDvmClosePortalExpr6Temp,>,0 
buttons=1
event1=EventDvmClosePortalReadPagePage5TiePoint

[EventDvmClosePortalReadPagePage5TiePoint]
operations=readDvmClosePortalPreviousPage,=,5 readDvmClosePortalPage5,=,1
display=false
buttons=1
event1=EventDvmClosePortalReadPagePage5End

[EventDvmClosePortalReadPagePage5End]
display=false
buttons=1
event1=EventDvmClosePortalTiePoint

[EventDvmClosePortalReadPagePage5Base]
buttons=1
event1=EventDvmClosePortalReadPagePage5TiePoint

[EventDvmClosePortalOrderedToc5]
buttons=11
event1=EventDvmClosePortalReadPagePage1
event1Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,>,0 
event1ConditionAction=hide
event2=EventDvmClosePortalReadPagePage1
event2Condition=VarOperation:DvmClosePortalPage1Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage1,==,0 
event2ConditionAction=hide
event3=EventDvmClosePortalReadPagePage2
event3Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,>,0 
event3ConditionAction=hide
event4=EventDvmClosePortalReadPagePage2
event4Condition=VarOperation:DvmClosePortalPage2Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage2,==,0 
event4ConditionAction=hide
event5=EventDvmClosePortalReadPagePage3
event5Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,>,0 
event5ConditionAction=hide
event6=EventDvmClosePortalReadPagePage3
event6Condition=VarOperation:DvmClosePortalPage3Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage3,==,0 
event6ConditionAction=hide
event7=EventDvmClosePortalReadPagePage4
event7Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,>,0 
event7ConditionAction=hide
event8=EventDvmClosePortalReadPagePage4
event8Condition=VarOperation:DvmClosePortalPage4Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage4,==,0 
event8ConditionAction=hide
event9=EventDvmClosePortalReadPagePage5
event9Condition=VarOperation:DvmClosePortalPage5Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage5,>,0 
event9ConditionAction=hide
event10=EventDvmClosePortalReadPagePage5
event10Condition=VarOperation:DvmClosePortalPage5Visible,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmClosePortalPage5,==,0 
event10ConditionAction=hide
event11=
