; Saved by version: 3.0.4

[EventDvmOpenPortalStart]
operations=DvmOpenPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventDvmOpenPortalInit

[EventDvmOpenPortalInit]
operations=EventDvmOpenPortalExit,=,1
display=false
buttons=1
event1=EventDvmOpenPortalFirstTimeInitializer EventDvmOpenPortalOrderedToc

[EventDvmOpenPortalFirstTimeInitializer]
operations=EventDvmOpenPortalInitialized,=,1 visibleDvmOpenPortalTableOfContents,=,1 visibleDvmOpenPortalOverview,=,1 visibleDvmOpenPortalTools,=,1 visibleDvmOpenPortalSacrifice,=,1 visibleDvmOpenPortalCommentary,=,1
vartests=VarOperation:EventDvmOpenPortalInitialized,==,0 
display=false
buttons=1
event1=EventDvmOpenPortalOrderedToc

[EventDvmOpenPortalOrderedToc]
operations=readAllDvmOpenPortal,=,0
display=false
buttons=1
event1=EventDvmOpenPortalTocSelector

[EventDvmOpenPortalTocSelector]
display=false
buttons=1
event1=EventDvmOpenPortalOrderedToc0 EventDvmOpenPortalOrderedToc1 EventDvmOpenPortalOrderedToc2 EventDvmOpenPortalOrderedToc3 EventDvmOpenPortalOrderedToc4 EventDvmOpenPortalOrderedToc5

[EventDvmOpenPortalOrderedToc0]
vartests=VarOperation:visibleDvmOpenPortalTableOfContents,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTools,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalEpilog,==,0 
buttons=3
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=

[EventDvmOpenPortalReadPageTableOfContents]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageTableOfContentsDisplay

[EventDvmOpenPortalReadPageTableOfContentsDisplay]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageTableOfContentsBase

[EventDvmOpenPortalReadPageTableOfContentsBase]
buttons=1
event1=EventDvmOpenPortalReadPageTableOfContentsTiePoint

[EventDvmOpenPortalReadPageTableOfContentsTiePoint]
operations=readDvmOpenPortalPreviousPage,=,1 readDvmOpenPortalTableOfContents,=,1
display=false
buttons=1
event1=EventDvmOpenPortalReadPageTableOfContentsEnd

[EventDvmOpenPortalReadPageTableOfContentsEnd]
display=false
buttons=1
event1=EventDvmOpenPortalTiePoint

[EventDvmOpenPortalTiePoint]
display=false
buttons=1
event1=EventDvmOpenPortalClearTrigger

[EventDvmOpenPortalClearTrigger]
operations=DvmOpenPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventDvmOpenPortalLoopBack EventDvmOpenPortalEnd

[EventDvmOpenPortalLoopBack]
vartests=VarOperation:EventDvmOpenPortalExit,==,0 
display=false
buttons=1
event1=EventDvmOpenPortalInit

[EventDvmOpenPortalEnd]
display=false
buttons=1
event1=

[EventDvmOpenPortalOrderedToc1]
vartests=VarOperation:visibleDvmOpenPortalOverview,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTableOfContents,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTools,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalEpilog,==,0 
buttons=5
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=EventDvmOpenPortalReadPageOverview
event3Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,>,0 
event3ConditionAction=hide
event4=EventDvmOpenPortalReadPageOverview
event4Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,==,0 
event4ConditionAction=hide
event5=

[EventDvmOpenPortalReadPageOverview]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageOverviewDisplay

[EventDvmOpenPortalReadPageOverviewDisplay]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageOverviewBase

[EventDvmOpenPortalReadPageOverviewBase]
buttons=1
event1=EventDvmOpenPortalReadPageOverviewTiePoint

[EventDvmOpenPortalReadPageOverviewTiePoint]
operations=readDvmOpenPortalPreviousPage,=,2 readDvmOpenPortalOverview,=,1
display=false
buttons=1
event1=EventDvmOpenPortalReadPageOverviewEnd

[EventDvmOpenPortalReadPageOverviewEnd]
display=false
buttons=1
event1=EventDvmOpenPortalTiePoint

[EventDvmOpenPortalOrderedToc2]
vartests=VarOperation:visibleDvmOpenPortalTools,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTableOfContents,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalOverview,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTools,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalEpilog,==,0 
buttons=7
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=EventDvmOpenPortalReadPageOverview
event3Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,>,0 
event3ConditionAction=hide
event4=EventDvmOpenPortalReadPageOverview
event4Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,==,0 
event4ConditionAction=hide
event5=EventDvmOpenPortalReadPageTools
event5Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,>,0 
event5ConditionAction=hide
event6=EventDvmOpenPortalReadPageTools
event6Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,==,0 
event6ConditionAction=hide
event7=

[EventDvmOpenPortalReadPageTools]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageToolsDisplay

[EventDvmOpenPortalReadPageToolsDisplay]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageToolsBase

[EventDvmOpenPortalReadPageToolsBase]
buttons=1
event1=EventDvmOpenPortalReadPageToolsTiePoint

[EventDvmOpenPortalReadPageToolsTiePoint]
operations=readDvmOpenPortalPreviousPage,=,3 readDvmOpenPortalTools,=,1
display=false
buttons=1
event1=EventDvmOpenPortalReadPageToolsEnd

[EventDvmOpenPortalReadPageToolsEnd]
display=false
buttons=1
event1=EventDvmOpenPortalTiePoint

[EventDvmOpenPortalOrderedToc3]
vartests=VarOperation:visibleDvmOpenPortalSacrifice,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTableOfContents,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalOverview,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTools,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalEpilog,==,0 
buttons=9
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=EventDvmOpenPortalReadPageOverview
event3Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,>,0 
event3ConditionAction=hide
event4=EventDvmOpenPortalReadPageOverview
event4Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,==,0 
event4ConditionAction=hide
event5=EventDvmOpenPortalReadPageTools
event5Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,>,0 
event5ConditionAction=hide
event6=EventDvmOpenPortalReadPageTools
event6Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,==,0 
event6ConditionAction=hide
event7=EventDvmOpenPortalReadPageSacrifice
event7Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,>,0 
event7ConditionAction=hide
event8=EventDvmOpenPortalReadPageSacrifice
event8Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,==,0 
event8ConditionAction=hide
event9=

[EventDvmOpenPortalReadPageSacrifice]
display=false
buttons=1
event1=EventDvmOpenPortalExpr5

[EventDvmOpenPortalExpr5]
comment=@(107, 11)
operations=EventDvmOpenPortalExpr5Temp,=,journalReadPage4
display=false
buttons=1
event1=EventDvmOpenPortalReadPageSacrificeDisplay

[EventDvmOpenPortalReadPageSacrificeDisplay]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageSacrificeOverload1 EventDvmOpenPortalReadPageSacrificeBase

[EventDvmOpenPortalReadPageSacrificeOverload1]
operations=readDvmOpenPortalSacrifice,=,1
vartests=VarOperation:EventDvmOpenPortalExpr5Temp,>,0 
buttons=1
event1=EventDvmOpenPortalReadPageSacrificeTiePoint

[EventDvmOpenPortalReadPageSacrificeTiePoint]
operations=readDvmOpenPortalPreviousPage,=,4 readDvmOpenPortalSacrifice,=,1
display=false
buttons=1
event1=EventDvmOpenPortalReadPageSacrificeEnd

[EventDvmOpenPortalReadPageSacrificeEnd]
display=false
buttons=1
event1=EventDvmOpenPortalTiePoint

[EventDvmOpenPortalReadPageSacrificeBase]
buttons=1
event1=EventDvmOpenPortalReadPageSacrificeTiePoint

[EventDvmOpenPortalOrderedToc4]
vartests=VarOperation:visibleDvmOpenPortalCommentary,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTableOfContents,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalOverview,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalTools,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalSacrifice,>,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:AND VarOperation:readDvmOpenPortalEpilog,==,0 
buttons=11
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=EventDvmOpenPortalReadPageOverview
event3Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,>,0 
event3ConditionAction=hide
event4=EventDvmOpenPortalReadPageOverview
event4Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,==,0 
event4ConditionAction=hide
event5=EventDvmOpenPortalReadPageTools
event5Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,>,0 
event5ConditionAction=hide
event6=EventDvmOpenPortalReadPageTools
event6Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,==,0 
event6ConditionAction=hide
event7=EventDvmOpenPortalReadPageSacrifice
event7Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,>,0 
event7ConditionAction=hide
event8=EventDvmOpenPortalReadPageSacrifice
event8Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,==,0 
event8ConditionAction=hide
event9=EventDvmOpenPortalReadPageCommentary
event9Condition=VarOperation:visibleDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalCommentary,>,0 
event9ConditionAction=hide
event10=EventDvmOpenPortalReadPageCommentary
event10Condition=VarOperation:visibleDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalCommentary,==,0 
event10ConditionAction=hide
event11=

[EventDvmOpenPortalReadPageCommentary]
display=false
buttons=1
event1=EventDvmOpenPortalExpr6

[EventDvmOpenPortalExpr6]
comment=@(146, 11)
operations=EventDvmOpenPortalExpr6Temp,=,readAboutBoy
display=false
buttons=1
event1=EventDvmOpenPortalReadPageCommentaryDisplay

[EventDvmOpenPortalReadPageCommentaryDisplay]
display=false
buttons=1
event1=EventDvmOpenPortalReadPageCommentaryOverload1 EventDvmOpenPortalReadPageCommentaryBase

[EventDvmOpenPortalReadPageCommentaryOverload1]
operations=readDvmOpenPortalCommentary,=,1
vartests=VarOperation:EventDvmOpenPortalExpr6Temp,>,0 
buttons=1
event1=EventDvmOpenPortalReadPageCommentaryTiePoint

[EventDvmOpenPortalReadPageCommentaryTiePoint]
operations=readDvmOpenPortalPreviousPage,=,5 readDvmOpenPortalCommentary,=,1
display=false
buttons=1
event1=EventDvmOpenPortalReadPageCommentaryEnd

[EventDvmOpenPortalReadPageCommentaryEnd]
display=false
buttons=1
event1=EventDvmOpenPortalTiePoint

[EventDvmOpenPortalReadPageCommentaryBase]
buttons=1
event1=EventDvmOpenPortalReadPageCommentaryTiePoint

[EventDvmOpenPortalOrderedToc5]
buttons=11
event1=EventDvmOpenPortalReadPageTableOfContents
event1Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,>,0 
event1ConditionAction=hide
event2=EventDvmOpenPortalReadPageTableOfContents
event2Condition=VarOperation:visibleDvmOpenPortalTableOfContents,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTableOfContents,==,0 
event2ConditionAction=hide
event3=EventDvmOpenPortalReadPageOverview
event3Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,>,0 
event3ConditionAction=hide
event4=EventDvmOpenPortalReadPageOverview
event4Condition=VarOperation:visibleDvmOpenPortalOverview,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalOverview,==,0 
event4ConditionAction=hide
event5=EventDvmOpenPortalReadPageTools
event5Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,>,0 
event5ConditionAction=hide
event6=EventDvmOpenPortalReadPageTools
event6Condition=VarOperation:visibleDvmOpenPortalTools,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalTools,==,0 
event6ConditionAction=hide
event7=EventDvmOpenPortalReadPageSacrifice
event7Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,>,0 
event7ConditionAction=hide
event8=EventDvmOpenPortalReadPageSacrifice
event8Condition=VarOperation:visibleDvmOpenPortalSacrifice,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalSacrifice,==,0 
event8ConditionAction=hide
event9=EventDvmOpenPortalReadPageCommentary
event9Condition=VarOperation:visibleDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalCommentary,>,0 
event9ConditionAction=hide
event10=EventDvmOpenPortalReadPageCommentary
event10Condition=VarOperation:visibleDvmOpenPortalCommentary,==,0 VarTestsLogicalOperator:OR VarOperation:readDvmOpenPortalCommentary,==,0 
event10ConditionAction=hide
event11=
