; Saved by version: 3.0.4

[EventFeedPortalStart]
operations=FeedPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventFeedPortalInit

[EventFeedPortalInit]
operations=EventFeedPortalExit,=,1
display=false
buttons=1
event1=EventFeedPortalFirstTimeInitializer EventFeedPortalToc

[EventFeedPortalFirstTimeInitializer]
operations=EventFeedPortalInitialized,=,1 FeedPortalPage1Visible,=,1 FeedPortalPage2Visible,=,1 FeedPortalRepeatable1Visible,=,1 FeedPortalRepeatable2Visible,=,1 FeedPortalRepeatable3Visible,=,1 FeedPortalRepeatable4Visible,=,1 FeedPortalRepeatable5Visible,=,1
vartests=VarOperation:EventFeedPortalInitialized,==,0 
display=false
buttons=1
event1=EventFeedPortalToc

[EventFeedPortalToc]
display=false
buttons=1
event1=EventFeedPortalTocSelector

[EventFeedPortalTocSelector]
display=false
buttons=1
event1=EventFeedPortalTocPrologPage1 EventFeedPortalTocPrologPage2 EventFeedPortalTocPrologRepeatable1 EventFeedPortalTocPrologRepeatable2 EventFeedPortalTocPrologRepeatable3 EventFeedPortalTocPrologRepeatable4 EventFeedPortalTocPrologRepeatable5 EventFeedPortalClearTrigger

[EventFeedPortalTocPrologPage1]
vartests=VarOperation:readFeedPortalPage1,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalPage1Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPagePage1

[EventFeedPortalReadPagePage1]
display=false
buttons=1
event1=EventFeedPortalReadPagePage1Display

[EventFeedPortalReadPagePage1Display]
display=false
buttons=1
event1=EventFeedPortalReadPagePage1Base

[EventFeedPortalReadPagePage1Base]
buttons=1
event1=EventFeedPortalReadPagePage1TiePoint

[EventFeedPortalReadPagePage1TiePoint]
operations=readFeedPortalPreviousPage,=,1 readFeedPortalPage1,=,1
display=false
buttons=1
event1=EventFeedPortalReadPagePage1End

[EventFeedPortalReadPagePage1End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTiePoint]
display=false
buttons=1
event1=EventFeedPortalClearTrigger

[EventFeedPortalClearTrigger]
operations=FeedPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventFeedPortalLoopBack EventFeedPortalEnd

[EventFeedPortalLoopBack]
vartests=VarOperation:EventFeedPortalExit,==,0 
display=false
buttons=1
event1=EventFeedPortalInit

[EventFeedPortalEnd]
display=false
buttons=1
event1=

[EventFeedPortalTocPrologPage2]
vartests=VarOperation:readFeedPortalPage2,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalPage2Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPagePage2

[EventFeedPortalReadPagePage2]
display=false
buttons=1
event1=EventFeedPortalReadPagePage2Display

[EventFeedPortalReadPagePage2Display]
display=false
buttons=1
event1=EventFeedPortalReadPagePage2Base

[EventFeedPortalReadPagePage2Base]
buttons=1
event1=EventFeedPortalReadPagePage2TiePoint

[EventFeedPortalReadPagePage2TiePoint]
operations=readFeedPortalPreviousPage,=,2 readFeedPortalPage2,=,1
display=false
buttons=1
event1=EventFeedPortalReadPagePage2End

[EventFeedPortalReadPagePage2End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTocPrologRepeatable1]
vartests=VarOperation:readFeedPortalRepeatable1,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalRepeatable1Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable1

[EventFeedPortalReadPageRepeatable1]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable1Display

[EventFeedPortalReadPageRepeatable1Display]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable1Base

[EventFeedPortalReadPageRepeatable1Base]
buttons=1
event1=EventFeedPortalReadPageRepeatable1TiePoint

[EventFeedPortalReadPageRepeatable1TiePoint]
operations=readFeedPortalPreviousPage,=,3 readFeedPortalRepeatable1,=,1
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable1End

[EventFeedPortalReadPageRepeatable1End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTocPrologRepeatable2]
vartests=VarOperation:readFeedPortalRepeatable2,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalRepeatable2Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable2

[EventFeedPortalReadPageRepeatable2]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable2Display

[EventFeedPortalReadPageRepeatable2Display]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable2Base

[EventFeedPortalReadPageRepeatable2Base]
buttons=1
event1=EventFeedPortalReadPageRepeatable2TiePoint

[EventFeedPortalReadPageRepeatable2TiePoint]
operations=readFeedPortalPreviousPage,=,4 readFeedPortalRepeatable2,=,1
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable2End

[EventFeedPortalReadPageRepeatable2End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTocPrologRepeatable3]
vartests=VarOperation:readFeedPortalRepeatable3,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalRepeatable3Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable3

[EventFeedPortalReadPageRepeatable3]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable3Display

[EventFeedPortalReadPageRepeatable3Display]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable3Base

[EventFeedPortalReadPageRepeatable3Base]
buttons=1
event1=EventFeedPortalReadPageRepeatable3TiePoint

[EventFeedPortalReadPageRepeatable3TiePoint]
operations=readFeedPortalPreviousPage,=,5 readFeedPortalRepeatable3,=,1
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable3End

[EventFeedPortalReadPageRepeatable3End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTocPrologRepeatable4]
vartests=VarOperation:readFeedPortalRepeatable4,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalRepeatable4Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable4

[EventFeedPortalReadPageRepeatable4]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable4Display

[EventFeedPortalReadPageRepeatable4Display]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable4Base

[EventFeedPortalReadPageRepeatable4Base]
buttons=1
event1=EventFeedPortalReadPageRepeatable4TiePoint

[EventFeedPortalReadPageRepeatable4TiePoint]
operations=readFeedPortalPreviousPage,=,6 readFeedPortalRepeatable4,=,1
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable4End

[EventFeedPortalReadPageRepeatable4End]
display=false
buttons=1
event1=EventFeedPortalTiePoint

[EventFeedPortalTocPrologRepeatable5]
vartests=VarOperation:readFeedPortalRepeatable5,==,0 VarTestsLogicalOperator:AND VarOperation:FeedPortalRepeatable5Visible,>,0 
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable5

[EventFeedPortalReadPageRepeatable5]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable5MarkBefore1

[EventFeedPortalReadPageRepeatable5MarkBefore1]
operations=readFeedPortalRepeatable5,=,0
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable5Display

[EventFeedPortalReadPageRepeatable5Display]
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable5Base

[EventFeedPortalReadPageRepeatable5Base]
buttons=1
event1=EventFeedPortalReadPageRepeatable5TiePoint

[EventFeedPortalReadPageRepeatable5TiePoint]
operations=readFeedPortalPreviousPage,=,7 readFeedPortalRepeatable5,=,1
display=false
buttons=1
event1=EventFeedPortalReadPageRepeatable5End

[EventFeedPortalReadPageRepeatable5End]
display=false
buttons=1
event1=EventFeedPortalTiePoint
