; Saved by version: 3.10

[EventGalleryStart]
operations=GalleryTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventGalleryInit

[EventGalleryInit]
operations=EventGalleryExit,=,0
display=false
buttons=1
event1=EventGalleryFirstTimeInitializer EventGalleryTriggerPrologSelector

[EventGalleryFirstTimeInitializer]
operations=EventGalleryInitialized,=,1 visibleGalleryPlaceGallery,=,1 visibleGalleryPlaceHall1Painting,=,1 visibleGalleryPlaceExploreFoyerViaGallery,=,1 visibleGalleryPlaceGalleryCoatRoom,=,1 visibleGalleryPlaceGalleryDvm,=,1 visibleGalleryPlaceCoatRoom,=,1 visibleGallerySearchDvm,=,1 visibleGallerySearchCoatRoomEvidence,=,1
vartests=VarOperation:EventGalleryInitialized,==,0 
display=false
buttons=1
event1=EventGalleryTriggerPrologSelector

[EventGalleryTriggerPrologSelector]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryTriggeredPrologTarget EventGalleryReadPageSearchDvmTriggeredPrologTarget EventGalleryReadPageSearchCoatRoomEvidenceTriggeredPrologTarget EventGalleryTriggerSelector

[EventGalleryReadPagePlaceGalleryTriggeredPrologTarget]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceGallery

[EventGalleryTocPrologPlaceGallery]
buttons=2
event1=EventGalleryReadPagePlaceGallery
event2=EventGalleryEnd

[EventGalleryReadPagePlaceGallery]
operations=readGalleryPreviousPage,=,1 readGalleryPlaceGallery,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryBeforeAddRemove1

[EventGalleryReadPagePlaceGalleryBeforeAddRemove1]
comment=@(16, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryBeforeAddRemove2
add=TileGallery

[EventGalleryReadPagePlaceGalleryBeforeAddRemove2]
comment=@(17, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDisplay
remove=TokenExploreGalleryViaHall1

[EventGalleryReadPagePlaceGalleryDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryBase

[EventGalleryReadPagePlaceGalleryBase]
buttons=1
event1=EventGalleryReadPagePlaceGalleryTiePoint

[EventGalleryReadPagePlaceGalleryTiePoint]
display=false
buttons=1
event1=EventGalleryExpr1

[EventGalleryExpr1]
comment=@(33, 20)
operations=EventGalleryExpr1Temp,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryAfterLet1

[EventGalleryReadPagePlaceGalleryAfterLet1]
comment=@(33, 2)
operations=exploredGallery,=,EventGalleryExpr1Temp
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryAfterTrigger2

[EventGalleryReadPagePlaceGalleryAfterTrigger2]
comment=@(35, 2)
operations=@ExploreHall2ViaHall1,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryEnd

[EventGalleryReadPagePlaceGalleryEnd]
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryTiePoint]
display=false
buttons=1
event1=EventGalleryLoopBack EventGalleryEnd

[EventGalleryLoopBack]
vartests=VarOperation:EventGalleryExit,==,0 
display=false
buttons=1
event1=EventGalleryInit

[EventGalleryEnd]
display=false
buttons=1
event1=

[EventGalleryReadPageSearchDvmTriggeredPrologTarget]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,7 
display=false
buttons=1
event1=EventGalleryTocPrologSearchDvm

[EventGalleryTocPrologSearchDvm]
buttons=2
event1=EventGalleryReadPageSearchDvm
event2=EventGalleryEnd

[EventGalleryReadPageSearchDvm]
operations=readGalleryPreviousPage,=,7 readGallerySearchDvm,=,1
display=false
buttons=1
event1=EventGalleryReadPageSearchDvmBeforeAddRemove1

[EventGalleryReadPageSearchDvmBeforeAddRemove1]
comment=@(113, 2)
display=false
buttons=1
event1=EventGalleryReadPageSearchDvmDisplay
remove=TokenSearchGalleryDvm

[EventGalleryReadPageSearchDvmDisplay]
display=false
buttons=1
event1=EventGalleryReadPageSearchDvmBase

[EventGalleryReadPageSearchDvmBase]
buttons=1
event1=EventGalleryReadPageSearchDvmTiePoint
add=QItemDvm

[EventGalleryReadPageSearchDvmTiePoint]
display=false
buttons=1
event1=EventGalleryExpr2

[EventGalleryExpr2]
comment=@(125, 13)
operations=EventGalleryExpr2Temp,=,1
display=false
buttons=1
event1=EventGalleryReadPageSearchDvmAfterLet1

[EventGalleryReadPageSearchDvmAfterLet1]
comment=@(125, 2)
operations=foundDvm,=,EventGalleryExpr2Temp
display=false
buttons=1
event1=EventGalleryReadPageSearchDvmEnd

[EventGalleryReadPageSearchDvmEnd]
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryReadPageSearchCoatRoomEvidenceTriggeredPrologTarget]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,8 
display=false
buttons=1
event1=EventGalleryTocPrologSearchCoatRoomEvidence

[EventGalleryTocPrologSearchCoatRoomEvidence]
buttons=2
event1=EventGalleryReadPageSearchCoatRoomEvidence
event2=EventGalleryEnd

[EventGalleryReadPageSearchCoatRoomEvidence]
operations=readGalleryPreviousPage,=,8 readGallerySearchCoatRoomEvidence,=,1
display=false
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidenceBeforeAddRemove1

[EventGalleryReadPageSearchCoatRoomEvidenceBeforeAddRemove1]
comment=@(137, 2)
display=false
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidenceDisplay
remove=TokenSearchCoatRoomEvidence

[EventGalleryReadPageSearchCoatRoomEvidenceDisplay]
display=false
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidenceBase

[EventGalleryReadPageSearchCoatRoomEvidenceBase]
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidenceTiePoint
add=QItemEvidenceCoatRoom

[EventGalleryReadPageSearchCoatRoomEvidenceTiePoint]
display=false
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidenceAfterGoto68

[EventGalleryReadPageSearchCoatRoomEvidenceAfterGoto68]
comment=@(148, 2)
display=false
buttons=1
event1=EventGalleryEnd

[EventGalleryTriggerSelector]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryXferIfTriggered EventGalleryReadPagePlaceHall1PaintingXferIfTriggered EventGalleryReadPagePlaceExploreFoyerViaGalleryXferIfTriggered EventGalleryReadPagePlaceGalleryCoatRoomXferIfTriggered EventGalleryReadPagePlaceGalleryDvmXferIfTriggered EventGalleryReadPagePlaceCoatRoomXferIfTriggered EventGalleryReadPageSearchDvmXferIfTriggered EventGalleryReadPageSearchCoatRoomEvidenceXferIfTriggered EventGalleryToc

[EventGalleryReadPagePlaceGalleryXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventGalleryReadPagePlaceGallery

[EventGalleryReadPagePlaceHall1PaintingXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1Painting

[EventGalleryReadPagePlaceHall1Painting]
operations=readGalleryPreviousPage,=,2 readGalleryPlaceHall1Painting,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1PaintingBeforeAddRemove1

[EventGalleryReadPagePlaceHall1PaintingBeforeAddRemove1]
comment=@(39, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1PaintingDisplay
add=TokenSearchHall1Painting

[EventGalleryReadPagePlaceHall1PaintingDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1PaintingBase

[EventGalleryReadPagePlaceHall1PaintingBase]
buttons=1
event1=EventGalleryReadPagePlaceHall1PaintingTiePoint

[EventGalleryReadPagePlaceHall1PaintingTiePoint]
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1PaintingEnd

[EventGalleryReadPagePlaceHall1PaintingEnd]
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryReadPagePlaceExploreFoyerViaGalleryXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGallery

[EventGalleryReadPagePlaceExploreFoyerViaGallery]
operations=readGalleryPreviousPage,=,3 readGalleryPlaceExploreFoyerViaGallery,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGalleryBeforeAddRemove1

[EventGalleryReadPagePlaceExploreFoyerViaGalleryBeforeAddRemove1]
comment=@(56, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGalleryDisplay
add=TokenExploreFoyerViaGallery

[EventGalleryReadPagePlaceExploreFoyerViaGalleryDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGalleryBase

[EventGalleryReadPagePlaceExploreFoyerViaGalleryBase]
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGalleryTiePoint

[EventGalleryReadPagePlaceExploreFoyerViaGalleryTiePoint]
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGalleryEnd

[EventGalleryReadPagePlaceExploreFoyerViaGalleryEnd]
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryReadPagePlaceGalleryCoatRoomXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoom

[EventGalleryReadPagePlaceGalleryCoatRoom]
operations=readGalleryPreviousPage,=,4 readGalleryPlaceGalleryCoatRoom,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoomBeforeAddRemove1

[EventGalleryReadPagePlaceGalleryCoatRoomBeforeAddRemove1]
comment=@(66, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoomDisplay
add=TokenExploreCoatRoom

[EventGalleryReadPagePlaceGalleryCoatRoomDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoomBase

[EventGalleryReadPagePlaceGalleryCoatRoomBase]
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoomTiePoint

[EventGalleryReadPagePlaceGalleryCoatRoomTiePoint]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoomEnd

[EventGalleryReadPagePlaceGalleryCoatRoomEnd]
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryReadPagePlaceGalleryDvmXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,5 
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvm

[EventGalleryReadPagePlaceGalleryDvm]
operations=readGalleryPreviousPage,=,5 readGalleryPlaceGalleryDvm,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmBeforeAddRemove1

[EventGalleryReadPagePlaceGalleryDvmBeforeAddRemove1]
comment=@(76, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmDisplay
add=TokenSearchGalleryDvm

[EventGalleryReadPagePlaceGalleryDvmDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmBase

[EventGalleryReadPagePlaceGalleryDvmBase]
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmTiePoint

[EventGalleryReadPagePlaceGalleryDvmTiePoint]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmAfterTrigger1

[EventGalleryReadPagePlaceGalleryDvmAfterTrigger1]
comment=@(84, 2)
operations=@MoveAfterExplore,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvmAfterGoto66

[EventGalleryReadPagePlaceGalleryDvmAfterGoto66]
comment=@(85, 2)
display=false
buttons=1
event1=EventGalleryEnd

[EventGalleryReadPagePlaceCoatRoomXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,6 
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoom

[EventGalleryReadPagePlaceCoatRoom]
operations=readGalleryPreviousPage,=,6 readGalleryPlaceCoatRoom,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomBeforeAddRemove1

[EventGalleryReadPagePlaceCoatRoomBeforeAddRemove1]
comment=@(91, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomBeforeAddRemove2
remove=TokenExploreCoatRoom

[EventGalleryReadPagePlaceCoatRoomBeforeAddRemove2]
comment=@(92, 2)
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomDisplay
add=TokenSearchCoatRoomEvidence

[EventGalleryReadPagePlaceCoatRoomDisplay]
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomBase

[EventGalleryReadPagePlaceCoatRoomBase]
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomTiePoint

[EventGalleryReadPagePlaceCoatRoomTiePoint]
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomAfterTrigger1

[EventGalleryReadPagePlaceCoatRoomAfterTrigger1]
comment=@(103, 2)
operations=@MoveAfterExplore,=,1
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoomAfterGoto67

[EventGalleryReadPagePlaceCoatRoomAfterGoto67]
comment=@(104, 2)
display=false
buttons=1
event1=EventGalleryEnd

[EventGalleryReadPageSearchDvmXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,7 
display=false
buttons=1
event1=EventGalleryReadPageSearchDvm

[EventGalleryReadPageSearchCoatRoomEvidenceXferIfTriggered]
operations=EventGalleryTriggeredPageIndex,=,0
vartests=VarOperation:EventGalleryTriggeredPageIndex,==,8 
display=false
buttons=1
event1=EventGalleryReadPageSearchCoatRoomEvidence

[EventGalleryToc]
display=false
buttons=1
event1=EventGalleryTocSelector

[EventGalleryTocSelector]
display=false
buttons=1
event1=EventGalleryTocPrologProxyPlaceGallery EventGalleryTocPrologProxyPlaceHall1Painting EventGalleryTocPrologProxyPlaceExploreFoyerViaGallery EventGalleryTocPrologProxyPlaceGalleryCoatRoom EventGalleryTocPrologProxyPlaceGalleryDvm EventGalleryTocPrologProxyPlaceCoatRoom EventGalleryTocPrologProxySearchDvm EventGalleryTocPrologProxySearchCoatRoomEvidence EventGalleryTocNoPagesAvailable

[EventGalleryTocPrologProxyPlaceGallery]
vartests=VarOperation:readGalleryPlaceGallery,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceGallery,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceGallery

[EventGalleryTocPrologProxyPlaceHall1Painting]
vartests=VarOperation:readGalleryPlaceHall1Painting,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceHall1Painting,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceHall1Painting

[EventGalleryTocPrologPlaceHall1Painting]
display=false
buttons=1
event1=EventGalleryReadPagePlaceHall1Painting

[EventGalleryTocPrologProxyPlaceExploreFoyerViaGallery]
vartests=VarOperation:readGalleryPlaceExploreFoyerViaGallery,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceExploreFoyerViaGallery,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceExploreFoyerViaGallery

[EventGalleryTocPrologPlaceExploreFoyerViaGallery]
display=false
buttons=1
event1=EventGalleryReadPagePlaceExploreFoyerViaGallery

[EventGalleryTocPrologProxyPlaceGalleryCoatRoom]
vartests=VarOperation:readGalleryPlaceGalleryCoatRoom,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceGalleryCoatRoom,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceGalleryCoatRoom

[EventGalleryTocPrologPlaceGalleryCoatRoom]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryCoatRoom

[EventGalleryTocPrologProxyPlaceGalleryDvm]
vartests=VarOperation:readGalleryPlaceGalleryDvm,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceGalleryDvm,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceGalleryDvm

[EventGalleryTocPrologPlaceGalleryDvm]
display=false
buttons=1
event1=EventGalleryReadPagePlaceGalleryDvm

[EventGalleryTocPrologProxyPlaceCoatRoom]
vartests=VarOperation:readGalleryPlaceCoatRoom,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGalleryPlaceCoatRoom,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologPlaceCoatRoom

[EventGalleryTocPrologPlaceCoatRoom]
display=false
buttons=1
event1=EventGalleryReadPagePlaceCoatRoom

[EventGalleryTocPrologProxySearchDvm]
vartests=VarOperation:readGallerySearchDvm,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGallerySearchDvm,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologSearchDvm

[EventGalleryTocPrologProxySearchCoatRoomEvidence]
vartests=VarOperation:readGallerySearchCoatRoomEvidence,==,0 VarTestsLogicalOperator:AND VarOperation:visibleGallerySearchCoatRoomEvidence,>,0 
display=false
buttons=1
event1=EventGalleryTocPrologSearchCoatRoomEvidence

[EventGalleryTocNoPagesAvailable]
operations=EventGalleryExit,=,1
display=false
buttons=1
event1=EventGalleryTiePoint

[EventGalleryReadPagePlaceGalleryTrigger]
operations=EventGalleryTriggeredPageIndex,=,1
display=false
buttons=1
event1=EventGalleryInit
trigger=VarExploreGalleryViaHall1

[EventGalleryReadPagePlaceCoatRoomTrigger]
operations=EventGalleryTriggeredPageIndex,=,6
display=false
buttons=1
event1=EventGalleryInit
trigger=VarExploreCoatRoom

[EventGalleryReadPageSearchDvmTrigger]
operations=EventGalleryTriggeredPageIndex,=,7
display=false
buttons=1
event1=EventGalleryInit
trigger=VarSearchGalleryDvm

[EventGalleryReadPageSearchCoatRoomEvidenceTrigger]
operations=EventGalleryTriggeredPageIndex,=,8
display=false
buttons=1
event1=EventGalleryInit
trigger=VarSearchCoatRoomEvidence
