; Saved by version: 3.13

[EventHall2Start]
operations=Hall2TriggeredPageIndex,=,0
display=false
buttons=1
event1=EventHall2Init

[EventHall2Init]
operations=EventHall2Exit,=,0
display=false
buttons=1
event1=EventHall2FirstTimeInitializer EventHall2TriggerPrologSelector

[EventHall2FirstTimeInitializer]
operations=EventHall2Initialized,=,1 visibleHall2PlaceHall2ViaHall1,=,1 visibleHall2PlacePart2,=,1 visibleHall2PlaceHall2Evidence,=,1 visibleHall2SearchEvidence,=,1
vartests=VarOperation:EventHall2Initialized,==,0 
display=false
buttons=1
event1=EventHall2TriggerPrologSelector

[EventHall2TriggerPrologSelector]
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceTriggeredPrologTarget EventHall2TriggerSelector

[EventHall2ReadPageSearchEvidenceTriggeredPrologTarget]
operations=EventHall2TriggeredPageIndex,=,0
vartests=VarOperation:EventHall2TriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventHall2TocPrologSearchEvidence

[EventHall2TocPrologSearchEvidence]
buttons=2
event1=EventHall2ReadPageSearchEvidence
event2=EventHall2End

[EventHall2ReadPageSearchEvidence]
operations=readHall2PreviousPage,=,4 readHall2SearchEvidence,=,1
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceDisplay

[EventHall2ReadPageSearchEvidenceDisplay]
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceBase

[EventHall2ReadPageSearchEvidenceBase]
buttons=1
event1=EventHall2ReadPageSearchEvidenceTiePoint
add=QItemEvidenceHall2

[EventHall2ReadPageSearchEvidenceTiePoint]
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceAfterAddRemove1

[EventHall2ReadPageSearchEvidenceAfterAddRemove1]
comment=@(62, 2)
display=false
buttons=1
event1=EventHall2Expr3
remove=TokenSearchHall2Evidence

[EventHall2Expr3]
comment=@(64, 23)
operations=EventHall2Expr3Temp,=,foundEvidenceCount
display=false
buttons=1
event1=EventHall2Expr4

[EventHall2Expr4]
comment=@(64, 44)
operations=EventHall2Expr4Temp,=,1
display=false
buttons=1
event1=EventHall2Expr5

[EventHall2Expr5]
comment=@(64, 23)
operations=EventHall2Expr3Temp,+,EventHall2Expr4Temp
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceAfterLet2

[EventHall2ReadPageSearchEvidenceAfterLet2]
comment=@(64, 2)
operations=foundEvidenceCount,=,EventHall2Expr3Temp
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidenceAfterGoto110

[EventHall2ReadPageSearchEvidenceAfterGoto110]
comment=@(65, 2)
display=false
buttons=1
event1=EventHall2End

[EventHall2End]
display=false
buttons=1
event1=

[EventHall2TriggerSelector]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1XferIfTriggered EventHall2ReadPagePlacePart2XferIfTriggered EventHall2ReadPagePlaceHall2EvidenceXferIfTriggered EventHall2ReadPageSearchEvidenceXferIfTriggered EventHall2Toc

[EventHall2ReadPagePlaceHall2ViaHall1XferIfTriggered]
operations=EventHall2TriggeredPageIndex,=,0
vartests=VarOperation:EventHall2TriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1

[EventHall2ReadPagePlaceHall2ViaHall1]
operations=readHall2PreviousPage,=,1 readHall2PlaceHall2ViaHall1,=,1
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1BeforeAddRemove1

[EventHall2ReadPagePlaceHall2ViaHall1BeforeAddRemove1]
comment=@(10, 2)
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1Display
add=TileHall2 TokenWallHall2

[EventHall2ReadPagePlaceHall2ViaHall1Display]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1Base

[EventHall2ReadPagePlaceHall2ViaHall1Base]
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1TiePoint

[EventHall2ReadPagePlaceHall2ViaHall1TiePoint]
display=false
buttons=1
event1=EventHall2Expr1

[EventHall2Expr1]
comment=@(17, 26)
operations=EventHall2Expr1Temp,=,1
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1AfterLet1

[EventHall2ReadPagePlaceHall2ViaHall1AfterLet1]
comment=@(17, 2)
operations=exploredHall2ViaHall1,=,EventHall2Expr1Temp
display=false
buttons=1
event1=EventHall2Expr2

[EventHall2Expr2]
comment=@(18, 18)
operations=EventHall2Expr2Temp,=,1
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1AfterLet2

[EventHall2ReadPagePlaceHall2ViaHall1AfterLet2]
comment=@(18, 2)
operations=exploredHall2,=,EventHall2Expr2Temp
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1End

[EventHall2ReadPagePlaceHall2ViaHall1End]
display=false
buttons=1
event1=EventHall2TiePoint

[EventHall2TiePoint]
display=false
buttons=1
event1=EventHall2LoopBack EventHall2End

[EventHall2LoopBack]
vartests=VarOperation:EventHall2Exit,==,0 
display=false
buttons=1
event1=EventHall2Init

[EventHall2ReadPagePlacePart2XferIfTriggered]
operations=EventHall2TriggeredPageIndex,=,0
vartests=VarOperation:EventHall2TriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2

[EventHall2ReadPagePlacePart2]
operations=readHall2PreviousPage,=,2 readHall2PlacePart2,=,1
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2BeforeAddRemove1

[EventHall2ReadPagePlacePart2BeforeAddRemove1]
comment=@(22, 2)
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2Display
add=TokenExploreFoyerViaHall2 TokenExploreStudyViaHall2

[EventHall2ReadPagePlacePart2Display]
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2Base

[EventHall2ReadPagePlacePart2Base]
buttons=1
event1=EventHall2ReadPagePlacePart2TiePoint

[EventHall2ReadPagePlacePart2TiePoint]
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2End

[EventHall2ReadPagePlacePart2End]
display=false
buttons=1
event1=EventHall2TiePoint

[EventHall2ReadPagePlaceHall2EvidenceXferIfTriggered]
operations=EventHall2TriggeredPageIndex,=,0
vartests=VarOperation:EventHall2TriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2Evidence

[EventHall2ReadPagePlaceHall2Evidence]
operations=readHall2PreviousPage,=,3 readHall2PlaceHall2Evidence,=,1
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2EvidenceBeforeAddRemove1

[EventHall2ReadPagePlaceHall2EvidenceBeforeAddRemove1]
comment=@(31, 2)
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2EvidenceDisplay
add=TokenSearchHall2Evidence

[EventHall2ReadPagePlaceHall2EvidenceDisplay]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2EvidenceBase

[EventHall2ReadPagePlaceHall2EvidenceBase]
buttons=1
event1=EventHall2ReadPagePlaceHall2EvidenceTiePoint

[EventHall2ReadPagePlaceHall2EvidenceTiePoint]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2EvidenceAfterGoto109

[EventHall2ReadPagePlaceHall2EvidenceAfterGoto109]
comment=@(39, 2)
display=false
buttons=1
event1=EventHall2End

[EventHall2ReadPageSearchEvidenceXferIfTriggered]
operations=EventHall2TriggeredPageIndex,=,0
vartests=VarOperation:EventHall2TriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventHall2ReadPageSearchEvidence

[EventHall2Toc]
display=false
buttons=1
event1=EventHall2TocSelector

[EventHall2TocSelector]
display=false
buttons=1
event1=EventHall2TocPrologProxyPlaceHall2ViaHall1 EventHall2TocPrologProxyPlacePart2 EventHall2TocPrologProxyPlaceHall2Evidence EventHall2TocPrologProxySearchEvidence EventHall2TocNoPagesAvailable

[EventHall2TocPrologProxyPlaceHall2ViaHall1]
vartests=VarOperation:readHall2PlaceHall2ViaHall1,==,0 VarTestsLogicalOperator:AND VarOperation:visibleHall2PlaceHall2ViaHall1,>,0 
display=false
buttons=1
event1=EventHall2TocPrologPlaceHall2ViaHall1

[EventHall2TocPrologPlaceHall2ViaHall1]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2ViaHall1

[EventHall2TocPrologProxyPlacePart2]
vartests=VarOperation:readHall2PlacePart2,==,0 VarTestsLogicalOperator:AND VarOperation:visibleHall2PlacePart2,>,0 
display=false
buttons=1
event1=EventHall2TocPrologPlacePart2

[EventHall2TocPrologPlacePart2]
display=false
buttons=1
event1=EventHall2ReadPagePlacePart2

[EventHall2TocPrologProxyPlaceHall2Evidence]
vartests=VarOperation:readHall2PlaceHall2Evidence,==,0 VarTestsLogicalOperator:AND VarOperation:visibleHall2PlaceHall2Evidence,>,0 
display=false
buttons=1
event1=EventHall2TocPrologPlaceHall2Evidence

[EventHall2TocPrologPlaceHall2Evidence]
display=false
buttons=1
event1=EventHall2ReadPagePlaceHall2Evidence

[EventHall2TocPrologProxySearchEvidence]
vartests=VarOperation:readHall2SearchEvidence,==,0 VarTestsLogicalOperator:AND VarOperation:visibleHall2SearchEvidence,>,0 
display=false
buttons=1
event1=EventHall2TocPrologSearchEvidence

[EventHall2TocNoPagesAvailable]
operations=EventHall2Exit,=,1
display=false
buttons=1
event1=EventHall2TiePoint

[EventHall2ReadPagePlaceHall2ViaHall1Trigger]
operations=EventHall2TriggeredPageIndex,=,1
display=false
buttons=1
event1=EventHall2Init
trigger=VarExploreHall2ViaHall1

[EventHall2ReadPageSearchEvidenceTrigger]
operations=EventHall2TriggeredPageIndex,=,4
display=false
buttons=1
event1=EventHall2Init
trigger=VarSearchHall2Evidence
