; Saved by version: 3.13

[EventJournalStart]
operations=JournalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventJournalInit
trigger=VarReadJournal

[EventJournalInit]
operations=EventJournalExit,=,0
display=false
buttons=1
event1=EventJournalFirstTimeInitializer EventJournalTriggerPrologSelector

[EventJournalFirstTimeInitializer]
operations=EventJournalInitialized,=,1 visibleJournalPage1,=,1 visibleJournalPage2,=,1 visibleJournalPage3,=,1 visibleJournalPage4,=,1 visibleJournalPage5,=,1
vartests=VarOperation:EventJournalInitialized,==,0 
display=false
buttons=1
event1=EventJournalTriggerPrologSelector

[EventJournalTriggerPrologSelector]
display=false
buttons=1
event1=EventJournalTriggerSelector

[EventJournalTriggerSelector]
display=false
buttons=1
event1=EventJournalReadPagePage1XferIfTriggered EventJournalReadPagePage2XferIfTriggered EventJournalReadPagePage3XferIfTriggered EventJournalReadPagePage4XferIfTriggered EventJournalReadPagePage5XferIfTriggered EventJournalOrderedToc

[EventJournalReadPagePage1XferIfTriggered]
operations=EventJournalTriggeredPageIndex,=,0
vartests=VarOperation:EventJournalTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventJournalReadPagePage1

[EventJournalReadPagePage1]
operations=readJournalPreviousPage,=,1 readJournalPage1,=,1
display=false
buttons=1
event1=EventJournalReadPagePage1Display

[EventJournalReadPagePage1Display]
display=false
buttons=1
event1=EventJournalReadPagePage1Base

[EventJournalReadPagePage1Base]
buttons=1
event1=EventJournalReadPagePage1TiePoint

[EventJournalReadPagePage1TiePoint]
display=false
buttons=1
event1=EventJournalReadPagePage1End

[EventJournalReadPagePage1End]
display=false
buttons=1
event1=EventJournalTiePoint

[EventJournalTiePoint]
display=false
buttons=1
event1=EventJournalLoopBack EventJournalEnd

[EventJournalLoopBack]
vartests=VarOperation:EventJournalExit,==,0 
display=false
buttons=1
event1=EventJournalInit

[EventJournalEnd]
display=false
buttons=1
event1=

[EventJournalReadPagePage2XferIfTriggered]
operations=EventJournalTriggeredPageIndex,=,0
vartests=VarOperation:EventJournalTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventJournalReadPagePage2

[EventJournalReadPagePage2]
operations=readJournalPreviousPage,=,2 readJournalPage2,=,1
display=false
buttons=1
event1=EventJournalReadPagePage2Display

[EventJournalReadPagePage2Display]
display=false
buttons=1
event1=EventJournalReadPagePage2Base

[EventJournalReadPagePage2Base]
buttons=1
event1=EventJournalReadPagePage2TiePoint

[EventJournalReadPagePage2TiePoint]
display=false
buttons=1
event1=EventJournalReadPagePage2End

[EventJournalReadPagePage2End]
display=false
buttons=1
event1=EventJournalTiePoint

[EventJournalReadPagePage3XferIfTriggered]
operations=EventJournalTriggeredPageIndex,=,0
vartests=VarOperation:EventJournalTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventJournalReadPagePage3

[EventJournalReadPagePage3]
operations=readJournalPreviousPage,=,3 readJournalPage3,=,1
display=false
buttons=1
event1=EventJournalReadPagePage3Display

[EventJournalReadPagePage3Display]
display=false
buttons=1
event1=EventJournalReadPagePage3Base

[EventJournalReadPagePage3Base]
buttons=1
event1=EventJournalReadPagePage3TiePoint

[EventJournalReadPagePage3TiePoint]
display=false
buttons=1
event1=EventJournalExpr1

[EventJournalExpr1]
comment=@(82, 49)
operations=EventJournalExpr1Temp,=,1
display=false
buttons=1
event1=EventJournalReadPagePage3AfterLet1

[EventJournalReadPagePage3AfterLet1]
comment=@(82, 8)
operations=readAboutExploreDungeonCaveViaBasement,=,EventJournalExpr1Temp
display=false
buttons=1
event1=EventJournalReadPagePage3AfterTrigger2

[EventJournalReadPagePage3AfterTrigger2]
comment=@(83, 8)
operations=@ReadAboutExploreDungeonCaveViaBasement,=,1
display=false
buttons=1
event1=EventJournalReadPagePage3End

[EventJournalReadPagePage3End]
display=false
buttons=1
event1=EventJournalTiePoint

[EventJournalReadPagePage4XferIfTriggered]
operations=EventJournalTriggeredPageIndex,=,0
vartests=VarOperation:EventJournalTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventJournalReadPagePage4

[EventJournalReadPagePage4]
operations=readJournalPreviousPage,=,4 readJournalPage4,=,1
display=false
buttons=1
event1=EventJournalReadPagePage4Display

[EventJournalReadPagePage4Display]
display=false
buttons=1
event1=EventJournalReadPagePage4Base

[EventJournalReadPagePage4Base]
buttons=1
event1=EventJournalReadPagePage4TiePoint

[EventJournalReadPagePage4TiePoint]
display=false
buttons=1
event1=EventJournalExpr2

[EventJournalExpr2]
comment=@(110, 17)
operations=EventJournalExpr2Temp,=,1
display=false
buttons=1
event1=EventJournalReadPagePage4AfterLet1

[EventJournalReadPagePage4AfterLet1]
comment=@(110, 2)
operations=readAboutBoy,=,EventJournalExpr2Temp
display=false
buttons=1
event1=EventJournalReadPagePage4AfterTrigger2

[EventJournalReadPagePage4AfterTrigger2]
comment=@(111, 2)
operations=@PlaceExploreAltarViaCell,=,1
display=false
buttons=1
event1=EventJournalReadPagePage4End

[EventJournalReadPagePage4End]
display=false
buttons=1
event1=EventJournalTiePoint

[EventJournalReadPagePage5XferIfTriggered]
operations=EventJournalTriggeredPageIndex,=,0
vartests=VarOperation:EventJournalTriggeredPageIndex,==,5 
display=false
buttons=1
event1=EventJournalReadPagePage5

[EventJournalReadPagePage5]
operations=readJournalPreviousPage,=,5 readJournalPage5,=,1
display=false
buttons=1
event1=EventJournalReadPagePage5Display

[EventJournalReadPagePage5Display]
display=false
buttons=1
event1=EventJournalReadPagePage5Base

[EventJournalReadPagePage5Base]
buttons=1
event1=EventJournalReadPagePage5TiePoint

[EventJournalReadPagePage5TiePoint]
display=false
buttons=1
event1=EventJournalReadPagePage5End

[EventJournalReadPagePage5End]
display=false
buttons=1
event1=EventJournalTiePoint

[EventJournalOrderedToc]
operations=readAllJournal,=,0
display=false
buttons=1
event1=EventJournalTocSelector

[EventJournalTocSelector]
display=false
buttons=1
event1=EventJournalOrderedToc0 EventJournalOrderedToc1 EventJournalOrderedToc2 EventJournalOrderedToc3 EventJournalOrderedToc4 EventJournalReadPageEpilog

[EventJournalOrderedToc0]
vartests=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
buttons=3
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=

[EventJournalOrderedToc1]
vartests=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
buttons=5
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=EventJournalReadPagePage2
event3Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 
event3ConditionAction=hide
event4=EventJournalReadPagePage2
event4Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 
event4ConditionAction=hide
event5=

[EventJournalOrderedToc2]
vartests=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
buttons=7
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=EventJournalReadPagePage2
event3Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 
event3ConditionAction=hide
event4=EventJournalReadPagePage2
event4Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 
event4ConditionAction=hide
event5=EventJournalReadPagePage3
event5Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 
event5ConditionAction=hide
event6=EventJournalReadPagePage3
event6Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 
event6ConditionAction=hide
event7=

[EventJournalOrderedToc3]
vartests=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
buttons=9
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=EventJournalReadPagePage2
event3Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 
event3ConditionAction=hide
event4=EventJournalReadPagePage2
event4Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 
event4ConditionAction=hide
event5=EventJournalReadPagePage3
event5Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 
event5ConditionAction=hide
event6=EventJournalReadPagePage3
event6Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 
event6ConditionAction=hide
event7=EventJournalReadPagePage4
event7Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,>,0 
event7ConditionAction=hide
event8=EventJournalReadPagePage4
event8Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 
event8ConditionAction=hide
event9=

[EventJournalOrderedToc4]
vartests=VarOperation:visibleJournalPage5,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
buttons=11
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=EventJournalReadPagePage2
event3Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 
event3ConditionAction=hide
event4=EventJournalReadPagePage2
event4Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 
event4ConditionAction=hide
event5=EventJournalReadPagePage3
event5Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 
event5ConditionAction=hide
event6=EventJournalReadPagePage3
event6Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 
event6ConditionAction=hide
event7=EventJournalReadPagePage4
event7Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,>,0 
event7ConditionAction=hide
event8=EventJournalReadPagePage4
event8Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 
event8ConditionAction=hide
event9=EventJournalReadPagePage5
event9Condition=VarOperation:visibleJournalPage5,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,>,0 
event9ConditionAction=hide
event10=EventJournalReadPagePage5
event10Condition=VarOperation:visibleJournalPage5,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
event10ConditionAction=hide
event11=

[EventJournalReadPageEpilog]
operations=readAllJournal,=,1 readJournalPreviousPage,=,6 readJournalEpilog,=,1
display=false
buttons=1
event1=EventJournalReadPageEpilogDisplay

[EventJournalReadPageEpilogDisplay]
display=false
buttons=1
event1=EventJournalReadPageEpilogBase

[EventJournalReadPageEpilogBase]
buttons=11
event1=EventJournalReadPagePage1
event1Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,>,0 
event1ConditionAction=hide
event2=EventJournalReadPagePage1
event2Condition=VarOperation:visibleJournalPage1,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage1,==,0 
event2ConditionAction=hide
event3=EventJournalReadPagePage2
event3Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,>,0 
event3ConditionAction=hide
event4=EventJournalReadPagePage2
event4Condition=VarOperation:visibleJournalPage2,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage2,==,0 
event4ConditionAction=hide
event5=EventJournalReadPagePage3
event5Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,>,0 
event5ConditionAction=hide
event6=EventJournalReadPagePage3
event6Condition=VarOperation:visibleJournalPage3,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage3,==,0 
event6ConditionAction=hide
event7=EventJournalReadPagePage4
event7Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,>,0 
event7ConditionAction=hide
event8=EventJournalReadPagePage4
event8Condition=VarOperation:visibleJournalPage4,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage4,==,0 
event8ConditionAction=hide
event9=EventJournalReadPagePage5
event9Condition=VarOperation:visibleJournalPage5,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,>,0 
event9ConditionAction=hide
event10=EventJournalReadPagePage5
event10Condition=VarOperation:visibleJournalPage5,>,0 VarTestsLogicalOperator:AND VarOperation:readJournalPage5,==,0 
event10ConditionAction=hide
event11=
