; Saved by version: 3.0.4

[EventOpenPortalStart]
operations=OpenPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventOpenPortalInit

[EventOpenPortalInit]
operations=EventOpenPortalExit,=,0
display=false
buttons=1
event1=EventOpenPortalFirstTimeInitializer EventOpenPortalToc

[EventOpenPortalFirstTimeInitializer]
operations=EventOpenPortalInitialized,=,1 OpenPortalStep1Visible,=,1 OpenPortalStep2Visible,=,1 OpenPortalStep3Visible,=,1 OpenPortalStep3FailVisible,=,1 OpenPortalStep3RepeatVisible,=,1 OpenPortalStep3RepeatFailVisible,=,1 OpenPortalStep4Visible,=,1 OpenPortalStep4FailVisible,=,1
vartests=VarOperation:EventOpenPortalInitialized,==,0 
display=false
buttons=1
event1=EventOpenPortalToc

[EventOpenPortalToc]
display=false
buttons=1
event1=EventOpenPortalTocSelector

[EventOpenPortalTocSelector]
display=false
buttons=1
event1=EventOpenPortalTocPrologStep1 EventOpenPortalTocPrologStep2 EventOpenPortalTocPrologStep3 EventOpenPortalTocPrologStep3Fail EventOpenPortalTocPrologStep3Repeat EventOpenPortalTocPrologStep3RepeatFail EventOpenPortalTocPrologStep4 EventOpenPortalTocPrologStep4Fail EventOpenPortalTocPrologEpilog

[EventOpenPortalTocPrologStep1]
vartests=VarOperation:readOpenPortalStep1,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep1Visible,>,0 
buttons=2
event1=EventOpenPortalReadPageStep1
event2=EventOpenPortalEnd

[EventOpenPortalReadPageStep1]
display=false
buttons=1
event1=EventOpenPortalReadPageStep1Display

[EventOpenPortalReadPageStep1Display]
display=false
buttons=1
event1=EventOpenPortalReadPageStep1Base

[EventOpenPortalReadPageStep1Base]
buttons=1
event1=EventOpenPortalReadPageStep1TiePoint

[EventOpenPortalReadPageStep1TiePoint]
operations=readOpenPortalPreviousPage,=,1 readOpenPortalStep1,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep1End

[EventOpenPortalReadPageStep1End]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalTiePoint]
display=false
buttons=1
event1=EventOpenPortalMarkBefore1

[EventOpenPortalMarkBefore1]
operations=readOpenPortalStep3Repeat,=,1
display=false
buttons=1
event1=EventOpenPortalClearTrigger

[EventOpenPortalClearTrigger]
operations=OpenPortalTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventOpenPortalLoopBack EventOpenPortalEnd

[EventOpenPortalLoopBack]
vartests=VarOperation:EventOpenPortalExit,==,0 
display=false
buttons=1
event1=EventOpenPortalInit

[EventOpenPortalEnd]
display=false
buttons=1
event1=

[EventOpenPortalTocPrologStep2]
vartests=VarOperation:readOpenPortalStep2,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep2Visible,>,0 
buttons=2
event1=EventOpenPortalReadPageStep2
event2=EventOpenPortalEnd

[EventOpenPortalReadPageStep2]
display=false
buttons=1
event1=EventOpenPortalReadPageStep2Display

[EventOpenPortalReadPageStep2Display]
display=false
buttons=1
event1=EventOpenPortalReadPageStep2Base

[EventOpenPortalReadPageStep2Base]
buttons=2
event1=EventOpenPortalReadPageStep2BasePassTest
event2=EventOpenPortalReadPageStep2BaseFailTest
quota=10

[EventOpenPortalReadPageStep2BasePassTest]
operations=testOpenPortalStep2Pass,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep2TiePoint

[EventOpenPortalReadPageStep2TiePoint]
operations=readOpenPortalPreviousPage,=,2 readOpenPortalStep2,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep2PostTest

[EventOpenPortalReadPageStep2PostTest]
display=false
buttons=1
event1=EventOpenPortalReadPageStep2PostTestPass EventOpenPortalReadPageStep2PostTestFail

[EventOpenPortalReadPageStep2PostTestPass]
vartests=VarOperation:testOpenPortalStep2Pass,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep2End

[EventOpenPortalReadPageStep2End]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep2PostTestFail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep2End

[EventOpenPortalReadPageStep2BaseFailTest]
operations=testOpenPortalStep2Pass,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep2TiePoint

[EventOpenPortalTocPrologStep3]
vartests=VarOperation:readOpenPortalStep3,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep3Visible,>,0 
buttons=2
event1=EventOpenPortalReadPageStep3
event2=EventOpenPortalEnd

[EventOpenPortalReadPageStep3]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3Display

[EventOpenPortalReadPageStep3Display]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3Base

[EventOpenPortalReadPageStep3Base]
buttons=2
event1=EventOpenPortalReadPageStep3BasePassTest
event2=EventOpenPortalReadPageStep3BaseFailTest
quota=4

[EventOpenPortalReadPageStep3BasePassTest]
operations=testOpenPortalStep3Pass,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3TiePoint

[EventOpenPortalReadPageStep3TiePoint]
operations=readOpenPortalPreviousPage,=,3 readOpenPortalStep3,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3PostTest

[EventOpenPortalReadPageStep3PostTest]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3PostTestPass EventOpenPortalReadPageStep3PostTestFail

[EventOpenPortalReadPageStep3PostTestPass]
vartests=VarOperation:testOpenPortalStep3Pass,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep3End

[EventOpenPortalReadPageStep3End]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep3PostTestFail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3Fail

[EventOpenPortalReadPageStep3Fail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3FailMarkBefore1

[EventOpenPortalReadPageStep3FailMarkBefore1]
operations=readOpenPortalStep3Repeat,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep3FailDisplay

[EventOpenPortalReadPageStep3FailDisplay]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3FailBase

[EventOpenPortalReadPageStep3FailBase]
buttons=1
event1=EventOpenPortalReadPageStep3FailTiePoint

[EventOpenPortalReadPageStep3FailTiePoint]
operations=readOpenPortalPreviousPage,=,4 readOpenPortalStep3Fail,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3FailEnd

[EventOpenPortalReadPageStep3FailEnd]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep3BaseFailTest]
operations=testOpenPortalStep3Pass,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep3TiePoint

[EventOpenPortalTocPrologStep3Fail]
vartests=VarOperation:readOpenPortalStep3Fail,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep3FailVisible,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep3Fail

[EventOpenPortalTocPrologStep3Repeat]
vartests=VarOperation:readOpenPortalStep3Repeat,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep3RepeatVisible,>,0 
buttons=2
event1=EventOpenPortalReadPageStep3Repeat
event2=EventOpenPortalEnd

[EventOpenPortalReadPageStep3Repeat]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatDisplay

[EventOpenPortalReadPageStep3RepeatDisplay]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatBase

[EventOpenPortalReadPageStep3RepeatBase]
buttons=2
event1=EventOpenPortalReadPageStep3RepeatBasePassTest
event2=EventOpenPortalReadPageStep3RepeatBaseFailTest
quota=4

[EventOpenPortalReadPageStep3RepeatBasePassTest]
operations=testOpenPortalStep3RepeatPass,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatTiePoint

[EventOpenPortalReadPageStep3RepeatTiePoint]
operations=readOpenPortalPreviousPage,=,5 readOpenPortalStep3Repeat,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatPostTest

[EventOpenPortalReadPageStep3RepeatPostTest]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatPostTestPass EventOpenPortalReadPageStep3RepeatPostTestFail

[EventOpenPortalReadPageStep3RepeatPostTestPass]
vartests=VarOperation:testOpenPortalStep3RepeatPass,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatEnd

[EventOpenPortalReadPageStep3RepeatEnd]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep3RepeatPostTestFail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFail

[EventOpenPortalReadPageStep3RepeatFail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFailMarkBefore1

[EventOpenPortalReadPageStep3RepeatFailMarkBefore1]
operations=readOpenPortalStep3Repeat,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFailDisplay

[EventOpenPortalReadPageStep3RepeatFailDisplay]
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFailBase

[EventOpenPortalReadPageStep3RepeatFailBase]
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFailTiePoint

[EventOpenPortalReadPageStep3RepeatFailTiePoint]
operations=readOpenPortalPreviousPage,=,6 readOpenPortalStep3RepeatFail,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFailEnd

[EventOpenPortalReadPageStep3RepeatFailEnd]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep3RepeatBaseFailTest]
operations=testOpenPortalStep3RepeatPass,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatTiePoint

[EventOpenPortalTocPrologStep3RepeatFail]
vartests=VarOperation:readOpenPortalStep3RepeatFail,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep3RepeatFailVisible,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep3RepeatFail

[EventOpenPortalTocPrologStep4]
vartests=VarOperation:readOpenPortalStep4,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep4Visible,>,0 
buttons=2
event1=EventOpenPortalReadPageStep4
event2=EventOpenPortalEnd

[EventOpenPortalReadPageStep4]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4Display

[EventOpenPortalReadPageStep4Display]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4Base

[EventOpenPortalReadPageStep4Base]
buttons=2
event1=EventOpenPortalReadPageStep4BasePassTest
event2=EventOpenPortalReadPageStep4BaseFailTest
quota=10

[EventOpenPortalReadPageStep4BasePassTest]
operations=testOpenPortalStep4Pass,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep4TiePoint

[EventOpenPortalReadPageStep4TiePoint]
operations=readOpenPortalPreviousPage,=,7 readOpenPortalStep4,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep4PostTest

[EventOpenPortalReadPageStep4PostTest]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4PostTestPass EventOpenPortalReadPageStep4PostTestFail

[EventOpenPortalReadPageStep4PostTestPass]
vartests=VarOperation:testOpenPortalStep4Pass,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep4Fail

[EventOpenPortalReadPageStep4Fail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4FailDisplay

[EventOpenPortalReadPageStep4FailDisplay]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4FailBase

[EventOpenPortalReadPageStep4FailBase]
buttons=1
event1=EventOpenPortalReadPageStep4FailTiePoint

[EventOpenPortalReadPageStep4FailTiePoint]
operations=readOpenPortalPreviousPage,=,8 readOpenPortalStep4Fail,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageStep4FailEnd

[EventOpenPortalReadPageStep4FailEnd]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalReadPageStep4PostTestFail]
display=false
buttons=1
event1=EventOpenPortalReadPageStep4Fail

[EventOpenPortalReadPageStep4BaseFailTest]
operations=testOpenPortalStep4Pass,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageStep4TiePoint

[EventOpenPortalTocPrologStep4Fail]
vartests=VarOperation:readOpenPortalStep4Fail,==,0 VarTestsLogicalOperator:AND VarOperation:OpenPortalStep4FailVisible,>,0 
display=false
buttons=1
event1=EventOpenPortalReadPageStep4Fail

[EventOpenPortalTocPrologEpilog]
display=false
buttons=1
event1=EventOpenPortalReadPageEpilog

[EventOpenPortalReadPageEpilog]
operations=EventOpenPortalExit,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogDisplay

[EventOpenPortalReadPageEpilogDisplay]
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogBase

[EventOpenPortalReadPageEpilogBase]
buttons=1
event1=EventOpenPortalReadPageEpilogTiePoint

[EventOpenPortalReadPageEpilogTiePoint]
operations=readOpenPortalPreviousPage,=,9 readOpenPortalEpilog,=,1
display=false
buttons=1
event1=EventOpenPortalExpr5

[EventOpenPortalExpr5]
comment=@(195, 6)
operations=EventOpenPortalExpr5Temp,=,alreadyWarnedAboutKilling
display=false
buttons=1
event1=EventOpenPortalExpr6 EventOpenPortalExpr7

[EventOpenPortalExpr6]
comment=@(195, 5)
operations=EventOpenPortalExpr5Temp,=,1
vartests=VarOperation:EventOpenPortalExpr5Temp,==,0 
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogAddRemoveAfter1 EventOpenPortalExpr8

[EventOpenPortalReadPageEpilogAddRemoveAfter1]
vartests=VarOperation:EventOpenPortalExpr5Temp,>,0 
display=false
buttons=1
event1=EventOpenPortalExpr8
remove=MonsterUncleDavidAltar

[EventOpenPortalExpr8]
comment=@(196, 6)
operations=EventOpenPortalExpr8Temp,=,alreadyWarnedAboutKilling
display=false
buttons=1
event1=EventOpenPortalExpr9 EventOpenPortalExpr10

[EventOpenPortalExpr9]
comment=@(196, 5)
operations=EventOpenPortalExpr8Temp,=,1
vartests=VarOperation:EventOpenPortalExpr8Temp,==,0 
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogAddRemoveAfter2 EventOpenPortalExpr11

[EventOpenPortalReadPageEpilogAddRemoveAfter2]
vartests=VarOperation:EventOpenPortalExpr8Temp,>,0 
display=false
buttons=1
event1=EventOpenPortalExpr11
add=MonsterUncleDavidToKill

[EventOpenPortalExpr11]
comment=@(197, 30)
operations=EventOpenPortalExpr11Temp,=,1
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogLetAfter3

[EventOpenPortalReadPageEpilogLetAfter3]
operations=alreadyWarnedAboutKilling,=,EventOpenPortalExpr11Temp
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogEnd

[EventOpenPortalReadPageEpilogEnd]
display=false
buttons=1
event1=EventOpenPortalTiePoint

[EventOpenPortalExpr10]
comment=@(196, 5)
operations=EventOpenPortalExpr8Temp,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogAddRemoveAfter2 EventOpenPortalExpr11

[EventOpenPortalExpr7]
comment=@(195, 5)
operations=EventOpenPortalExpr5Temp,=,0
display=false
buttons=1
event1=EventOpenPortalReadPageEpilogAddRemoveAfter1 EventOpenPortalExpr8
