; Saved by version: 3.10
[Quest]
format=19
hidden=False
type=MoM
defaultlanguage=English
defaultmusicon=True
packs=MoM1ET RN SM
minhero=3


[QuestText]
Localization.English.txt

[QuestData]
tiles.ini
tokens.ini
events.ini
spawns.ini
ui.ini
items.ini
monsters.ini
puzzles.ini
Backyard.events.ini
BenAfter.events.ini
BenBefore.events.ini
Chapel.events.ini
Crypt.events.ini
DiningRoom.events.ini
Driveway.events.ini
Foyer.events.ini
Gallery.events.ini
Hall1.events.ini
Hall2.events.ini
Library.events.ini
Startup.events.ini
Study.events.ini
utility.events.ini
