; Saved by version: 3.15

[SpawnCustomMonsterChapelRiot]
xposition=-19.25
yposition=15.75
buttons=1
event1=
monster=CustomMonsterChapelRiot

[SpawnSpawnCultist1]
xposition=-12.25
yposition=-1.75
buttons=1
event1=
monster=MonsterCultist

[SpawnLibraryCultist]
xposition=-22.75
yposition=1.75
buttons=1
event1=
monster=CustomMonsterLibraryCultist

[SpawnPlaceAltarSpawnMathias]
xposition=1.75
yposition=19.25
buttons=1
event1=EventPlaceAltarWoman
monster=CustomMonsterMathias

[SpawnAltarCultists2]
xposition=-1.75
yposition=19.25
vartests=VarOperation:cultistCount,>,0 
display=false
buttons=1
event1=SpawnAltarCultists1
monster=CustomMonsterAltarCultist

[SpawnAltarCultists1]
xposition=-1.75
yposition=19.25
vartests=VarOperation:#heroes,==,3 
buttons=1
event1=EventPlaceAltarFinalize
monster=CustomMonsterAltarCultist

[SpawnCustomMonsterAltarCultistAfterDeath]
xposition=-8.75
yposition=19.25
buttons=1
event1=
trigger=DefeatedCustomMonsterAltarCultist
monster=CustomMonsterAltarCultist

[SpawnAltarCultists3]
xposition=-1.75
yposition=19.25
vartests=VarOperation:#heroes,>=,4 
display=false
buttons=1
event1=SpawnAltarCultists2
monster=CustomMonsterAltarCultist

[SpawnCellStartRitualMonster]
xposition=-4.634714
yposition=19.04911
vartests=VarOperation:ritual,>,0 VarTestsLogicalOperator:AND VarOperation:goal,==,goalStopRitual 
buttons=1
event1=EventPlaceCellEnd
add=TokenCellHoleInTheWall
monster=CustomMonsterCellLloiger

[SpawnAltarCultists4]
xposition=-1.75
yposition=19.25
vartests=VarOperation:#heroes,>=,5 
display=false
buttons=1
event1=SpawnAltarCultists3
monster=CustomMonsterAltarCultist

[SpawnAltarCultists5]
xposition=-1.75
yposition=19.25
vartests=VarOperation:#heroes,>=,5 
buttons=1
event1=SpawnAltarCultists4
monster=CustomMonsterAltarCultist

[SpawnPlaceDungeonCaveViaChapelCultist1]
xposition=-1.75
yposition=22.75
display=false
buttons=1
event1=SpawnPlaceDungeonCaveViaChapelCultist2
monster=MonsterCultist

[SpawnPlaceDungeonCaveViaChapelCultist2]
xposition=-1.75
yposition=22.75
buttons=1
event1=
monster=MonsterCultist

[SpawnMythosWandererHall1]
xposition=-8.75
yposition=5.25
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererStudy]
xposition=-19.25
yposition=1.75
vartests=VarOperation:exploredStudy,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererLibrary]
xposition=-22.75
yposition=5.25
vartests=VarOperation:exploredLibrary,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererChapel]
xposition=-22.75
yposition=19.25
vartests=VarOperation:exploredChapel,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererGallery]
xposition=-8.75
yposition=12.25
vartests=VarOperation:exploredGallery,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererHall2]
xposition=-15.75
yposition=5.25
vartests=VarOperation:exploredHall2,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnMythosWandererFoyer]
xposition=-19.25
yposition=8.75
vartests=VarOperation:exploredFoyer,>,0 
buttons=1
event1=EventMythosWandererPlaced
monster=CustomMonsterWanderer

[SpawnChapelStopCultistsRiot]
xposition=-22.75
yposition=19.25
display=false
buttons=1
event1=
trigger=VarspawnChapel2Riot
monster=MonsterRiot

[SpawnPlaceChapelTownfolk]
xposition=-22.75
yposition=19.25
buttons=1
event1=EventPlaceChapel2DeadPriest
monster=CustomMonsterChapelTownfolk

[SpawnCustomMonsterMathiasAngry]
xposition=-4.631324
yposition=19.24939
buttons=1
event1=
trigger=DefeatedCustomMonsterChapelTownfolk
monster=MonsterCultist

[SpawnFeeder1]
display=false
buttons=0
monster=CustomMonsterFeeder
