; Saved by version: 3.0.4

[EventStartupStart]
operations=StartupTriggeredPageIndex,=,0
buttons=1
event1=EventStartupInit

[EventStartupInit]
operations=EventStartupExit,=,1
buttons=1
event1=EventStartupFirstTimeInitializer EventStartupPageSelector

[EventStartupFirstTimeInitializer]
operations=EventStartupInitialized,=,1 visibleStartupStartUp,=,1 visibleStartupShowEverything,=,1 visibleStartupSplashScreen,=,1 visibleStartupSplashScreenClosed,=,1 visibleStartupStartScenario,=,1 visibleStartupKate,=,1
vartests=VarOperation:EventStartupInitialized,==,0 
buttons=1
event1=EventStartupPageSelector

[EventStartupPageSelector]
buttons=1
event1=EventStartupReadPageStartUpXferIfTriggered EventStartupReadPageSplashScreenXferIfTriggered EventStartupReadPageSplashScreenClosedXferIfTriggered EventStartupToc

[EventStartupReadPageStartUpXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,1 
buttons=1
event1=EventStartupReadPageStartUp

[EventStartupReadPageStartUp]
operations=readStartupPreviousPage,=,1 readStartupStartUp,=,1
buttons=1
event1=EventStartupExpr1

[EventStartupExpr1]
comment=@(10, 13)
operations=EventStartupExpr1Temp,=,0
buttons=1
event1=EventStartupReadPageStartUpBeforeLet1

[EventStartupReadPageStartUpBeforeLet1]
operations=testMode,=,EventStartupExpr1Temp
buttons=1
event1=EventStartupExpr2

[EventStartupExpr2]
comment=@(12, 24)
operations=EventStartupExpr2Temp,=,5
buttons=1
event1=EventStartupExpr3

[EventStartupExpr3]
comment=@(12, 28)
operations=EventStartupExpr3Temp,=,#heros
buttons=1
event1=EventStartupExpr4

[EventStartupExpr4]
comment=@(12, 24)
operations=EventStartupExpr2Temp,-,EventStartupExpr3Temp
buttons=1
event1=EventStartupExpr5

[EventStartupExpr5]
comment=@(12, 38)
operations=EventStartupExpr5Temp,=,2
buttons=1
event1=EventStartupExpr6

[EventStartupExpr6]
comment=@(12, 23)
operations=EventStartupExpr2Temp,*,EventStartupExpr5Temp
buttons=1
event1=EventStartupExpr7

[EventStartupExpr7]
comment=@(12, 42)
operations=EventStartupExpr7Temp,=,15
buttons=1
event1=EventStartupExpr8

[EventStartupExpr8]
comment=@(12, 23)
operations=EventStartupExpr2Temp,+,EventStartupExpr7Temp
buttons=1
event1=EventStartupReadPageStartUpBeforeLet2

[EventStartupReadPageStartUpBeforeLet2]
operations=roundsBeforeRitual,=,EventStartupExpr2Temp
buttons=1
event1=EventStartupExpr9

[EventStartupExpr9]
comment=@(20, 20)
operations=EventStartupExpr9Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet3

[EventStartupReadPageStartUpBeforeLet3]
operations=wandererInStudy,=,EventStartupExpr9Temp
buttons=1
event1=EventStartupExpr10

[EventStartupExpr10]
comment=@(21, 22)
operations=EventStartupExpr10Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet4

[EventStartupReadPageStartUpBeforeLet4]
operations=wandererInLibrary,=,EventStartupExpr10Temp
buttons=1
event1=EventStartupExpr11

[EventStartupExpr11]
comment=@(22, 21)
operations=EventStartupExpr11Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet5

[EventStartupReadPageStartUpBeforeLet5]
operations=wandererInChapel,=,EventStartupExpr11Temp
buttons=1
event1=EventStartupExpr12

[EventStartupExpr12]
comment=@(23, 20)
operations=EventStartupExpr12Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet6

[EventStartupReadPageStartUpBeforeLet6]
operations=wandererInHall2,=,EventStartupExpr12Temp
buttons=1
event1=EventStartupExpr13

[EventStartupExpr13]
comment=@(24, 20)
operations=EventStartupExpr13Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet7

[EventStartupReadPageStartUpBeforeLet7]
operations=wandererInFoyer,=,EventStartupExpr13Temp
buttons=1
event1=EventStartupExpr14

[EventStartupExpr14]
comment=@(25, 22)
operations=EventStartupExpr14Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet8

[EventStartupReadPageStartUpBeforeLet8]
operations=wandererInGallery,=,EventStartupExpr14Temp
buttons=1
event1=EventStartupExpr15

[EventStartupExpr15]
comment=@(29, 18)
operations=EventStartupExpr15Temp,=,0
buttons=1
event1=EventStartupReadPageStartUpBeforeLet9

[EventStartupReadPageStartUpBeforeLet9]
operations=wandererCount,=,EventStartupExpr15Temp
buttons=1
event1=EventStartupExpr16

[EventStartupExpr16]
comment=@(34, 23)
operations=EventStartupExpr16Temp,=,5
buttons=1
event1=EventStartupExpr17

[EventStartupExpr17]
comment=@(34, 27)
operations=EventStartupExpr17Temp,=,#heros
buttons=1
event1=EventStartupExpr18

[EventStartupExpr18]
comment=@(34, 23)
operations=EventStartupExpr16Temp,-,EventStartupExpr17Temp
buttons=1
event1=EventStartupExpr19

[EventStartupExpr19]
comment=@(34, 37)
operations=EventStartupExpr19Temp,=,2
buttons=1
event1=EventStartupExpr20

[EventStartupExpr20]
comment=@(34, 22)
operations=EventStartupExpr16Temp,*,EventStartupExpr19Temp
buttons=1
event1=EventStartupExpr21

[EventStartupExpr21]
comment=@(34, 41)
operations=EventStartupExpr21Temp,=,2
buttons=1
event1=EventStartupExpr22

[EventStartupExpr22]
comment=@(34, 22)
operations=EventStartupExpr16Temp,+,EventStartupExpr21Temp
buttons=1
event1=EventStartupReadPageStartUpBeforeLet10

[EventStartupReadPageStartUpBeforeLet10]
operations=wandererFrequency,=,EventStartupExpr16Temp
buttons=1
event1=EventStartupExpr23

[EventStartupExpr23]
comment=@(37, 22)
operations=EventStartupExpr23Temp,=,wandererFrequency
buttons=1
event1=EventStartupReadPageStartUpBeforeLet11

[EventStartupReadPageStartUpBeforeLet11]
operations=wandererCountdown,=,EventStartupExpr23Temp
buttons=1
event1=EventStartupExpr24

[EventStartupExpr24]
comment=@(40, 16)
operations=EventStartupExpr24Temp,=,#heros
buttons=1
event1=EventStartupReadPageStartUpBeforeLet12

[EventStartupReadPageStartUpBeforeLet12]
operations=wandererMax,=,EventStartupExpr24Temp
buttons=1
event1=EventStartupExpr25

[EventStartupExpr25]
comment=@(46, 11)
operations=EventStartupExpr25Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet13

[EventStartupReadPageStartUpBeforeLet13]
operations=endWin,=,EventStartupExpr25Temp
buttons=1
event1=EventStartupExpr26

[EventStartupExpr26]
comment=@(47, 18)
operations=EventStartupExpr26Temp,=,2
buttons=1
event1=EventStartupReadPageStartUpBeforeLet14

[EventStartupReadPageStartUpBeforeLet14]
operations=endPartialWin,=,EventStartupExpr26Temp
buttons=1
event1=EventStartupExpr27

[EventStartupExpr27]
comment=@(48, 12)
operations=EventStartupExpr27Temp,=,3
buttons=1
event1=EventStartupReadPageStartUpBeforeLet15

[EventStartupReadPageStartUpBeforeLet15]
operations=endFail,=,EventStartupExpr27Temp
buttons=1
event1=EventStartupExpr28

[EventStartupExpr28]
comment=@(51, 17)
operations=EventStartupExpr28Temp,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeLet16

[EventStartupReadPageStartUpBeforeLet16]
operations=goalOpenGate,=,EventStartupExpr28Temp
buttons=1
event1=EventStartupExpr29

[EventStartupExpr29]
comment=@(52, 17)
operations=EventStartupExpr29Temp,=,2
buttons=1
event1=EventStartupReadPageStartUpBeforeLet17

[EventStartupReadPageStartUpBeforeLet17]
operations=goalFeedGate,=,EventStartupExpr29Temp
buttons=1
event1=EventStartupExpr30

[EventStartupExpr30]
comment=@(53, 18)
operations=EventStartupExpr30Temp,=,3
buttons=1
event1=EventStartupReadPageStartUpBeforeLet18

[EventStartupReadPageStartUpBeforeLet18]
operations=goalCloseGate,=,EventStartupExpr30Temp
buttons=1
event1=EventStartupExpr31

[EventStartupExpr31]
comment=@(55, 16)
operations=EventStartupExpr31Temp,=,3 rngInput,=,EventStartupExpr31Temp @callRng,=,1 EventStartupExpr31Temp,=,rngResult
buttons=1
event1=EventStartupReadPageStartUpBeforeLet19

[EventStartupReadPageStartUpBeforeLet19]
operations=goal,=,EventStartupExpr31Temp
buttons=1
event1=EventStartupExpr32 EventStartupToc

[EventStartupExpr32]
comment=@(57, 9)
operations=EventStartupExpr32Temp,=,testMode
vartests=VarOperation:EventStartupExpr32Temp,>,0 
buttons=1
event1=EventStartupExpr33 EventStartupExpr34

[EventStartupExpr33]
comment=@(57, 5)
operations=EventStartupExpr32Temp,=,1
vartests=VarOperation:EventStartupExpr32Temp,==,0 
buttons=1
event1=EventStartupReadPageStartUpBeforeTrigger20

[EventStartupReadPageStartUpBeforeTrigger20]
operations=@SplashScreen,=,1
buttons=1
event1=EventStartupReadPageStartUpBeforeGoto88

[EventStartupReadPageStartUpBeforeGoto88]
operations=EventStartupGotoIndex,=,88
buttons=1
event1=EventStartupReadPageStartUpDisplay

[EventStartupReadPageStartUpDisplay]
buttons=1
event1=EventStartupReadPageStartUpBase

[EventStartupReadPageStartUpBase]
buttons=1
event1=EventStartupReadPageStartUpTiePoint

[EventStartupReadPageStartUpTiePoint]
buttons=1
event1=EventStartupReadPageStartUpEnd

[EventStartupReadPageStartUpEnd]
buttons=1
event1=EventStartupToc

[EventStartupToc]
buttons=1
event1=EventStartupTocSelector

[EventStartupTocSelector]
buttons=1
event1=EventStartupTocPrologStartUp EventStartupTocPrologShowEverything EventStartupTocPrologSplashScreen EventStartupTocPrologSplashScreenClosed EventStartupTocPrologStartScenario EventStartupTocPrologKate EventStartupTiePoint

[EventStartupTocPrologStartUp]
vartests=VarOperation:readStartupStartUp,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupStartUp,>,0 
buttons=1
event1=EventStartupReadPageStartUp

[EventStartupTocPrologShowEverything]
vartests=VarOperation:readStartupShowEverything,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupShowEverything,>,0 
buttons=1
event1=EventStartupReadPageShowEverything

[EventStartupReadPageShowEverything]
operations=readStartupPreviousPage,=,2 readStartupShowEverything,=,1
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove1

[EventStartupReadPageShowEverythingBeforeAddRemove1]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove2
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove2]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove3
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove3]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove4
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove4]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove5
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove5]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove6
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove6]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove7
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove7]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove8
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove8]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove9
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove9]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove10
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove10]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove11
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove11]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove12
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove12]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove13
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove13]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove14
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove14]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove15
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove15]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove16
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove16]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove17
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove17]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove18
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove18]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove19
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove19]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove20
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove20]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove21
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove21]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove22
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove22]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove23
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeAddRemove23]
buttons=1
event1=EventStartupReadPageShowEverythingBeforeGoto89
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageShowEverythingBeforeGoto89]
operations=EventStartupGotoIndex,=,89
buttons=1
event1=EventStartupReadPageShowEverythingDisplay

[EventStartupReadPageShowEverythingDisplay]
buttons=1
event1=EventStartupReadPageShowEverythingBase

[EventStartupReadPageShowEverythingBase]
buttons=1
event1=EventStartupReadPageShowEverythingTiePoint

[EventStartupReadPageShowEverythingTiePoint]
buttons=1
event1=EventStartupReadPageShowEverythingEnd

[EventStartupReadPageShowEverythingEnd]
buttons=1
event1=EventStartupTiePoint

[EventStartupTiePoint]
buttons=1
event1=EventStartupGotoAfter88 EventStartupEnd

[EventStartupGotoAfter88]
vartests=VarOperation:EventStartupGotoIndex,==,88 
buttons=1
event1=EventStartupEnd

[EventStartupEnd]
buttons=1
event1=

[EventStartupTocPrologSplashScreen]
vartests=VarOperation:readStartupSplashScreen,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupSplashScreen,>,0 
buttons=1
event1=EventStartupReadPageSplashScreen

[EventStartupReadPageSplashScreen]
operations=readStartupPreviousPage,=,3 readStartupSplashScreen,=,1
buttons=1
event1=EventStartupReadPageSplashScreenBeforeAddRemove1

[EventStartupReadPageSplashScreenBeforeAddRemove1]
buttons=1
event1=EventStartupReadPageSplashScreenDisplay
add=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageSplashScreenDisplay]
buttons=1
event1=EventStartupReadPageSplashScreenBase

[EventStartupReadPageSplashScreenBase]
buttons=1
event1=EventStartupReadPageSplashScreenTiePoint

[EventStartupReadPageSplashScreenTiePoint]
buttons=1
event1=EventStartupReadPageSplashScreenEnd

[EventStartupReadPageSplashScreenEnd]
buttons=1
event1=EventStartupToc

[EventStartupTocPrologSplashScreenClosed]
vartests=VarOperation:readStartupSplashScreenClosed,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupSplashScreenClosed,>,0 
buttons=1
event1=EventStartupReadPageSplashScreenClosed

[EventStartupReadPageSplashScreenClosed]
operations=readStartupPreviousPage,=,4 readStartupSplashScreenClosed,=,1
buttons=1
event1=EventStartupReadPageSplashScreenClosedBeforeAddRemove1

[EventStartupReadPageSplashScreenClosedBeforeAddRemove1]
buttons=1
event1=EventStartupReadPageSplashScreenClosedDisplay
remove=Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry Compiler.Models.AddRemoveEntry

[EventStartupReadPageSplashScreenClosedDisplay]
buttons=1
event1=EventStartupReadPageSplashScreenClosedBase

[EventStartupReadPageSplashScreenClosedBase]
buttons=1
event1=EventStartupReadPageSplashScreenClosedTiePoint

[EventStartupReadPageSplashScreenClosedTiePoint]
buttons=1
event1=EventStartupReadPageSplashScreenClosedEnd

[EventStartupReadPageSplashScreenClosedEnd]
buttons=1
event1=EventStartupToc

[EventStartupTocPrologStartScenario]
vartests=VarOperation:readStartupStartScenario,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupStartScenario,>,0 
buttons=1
event1=EventStartupReadPageStartScenario

[EventStartupReadPageStartScenario]
operations=readStartupPreviousPage,=,5 readStartupStartScenario,=,1
buttons=1
event1=EventStartupReadPageStartScenarioDisplay

[EventStartupReadPageStartScenarioDisplay]
buttons=1
event1=EventStartupReadPageStartScenarioBase

[EventStartupReadPageStartScenarioBase]
buttons=1
event1=EventStartupReadPageStartScenarioTiePoint

[EventStartupReadPageStartScenarioTiePoint]
buttons=1
event1=EventStartupReadPageStartScenarioEnd

[EventStartupReadPageStartScenarioEnd]
buttons=1
event1=EventStartupTiePoint

[EventStartupTocPrologKate]
vartests=VarOperation:readStartupKate,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupKate,>,0 
buttons=1
event1=EventStartupReadPageKate

[EventStartupReadPageKate]
operations=readStartupPreviousPage,=,6 readStartupKate,=,1
buttons=1
event1=EventStartupReadPageKateDisplay

[EventStartupReadPageKateDisplay]
buttons=1
event1=EventStartupReadPageKateBase

[EventStartupReadPageKateBase]
buttons=1
event1=EventStartupReadPageKateTiePoint

[EventStartupReadPageKateTiePoint]
buttons=1
event1=EventStartupReadPageKateAfterTrigger1

[EventStartupReadPageKateAfterTrigger1]
operations=@PlaceDriveWay,=,1
buttons=1
event1=EventStartupReadPageKateEnd

[EventStartupReadPageKateEnd]
buttons=1
event1=EventStartupTiePoint

[EventStartupExpr34]
comment=@(57, 5)
operations=EventStartupExpr32Temp,=,0
buttons=1
event1=EventStartupReadPageStartUpBeforeTrigger20

[EventStartupReadPageSplashScreenXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,3 
buttons=1
event1=EventStartupReadPageSplashScreen

[EventStartupReadPageSplashScreenClosedXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,4 
buttons=1
event1=EventStartupReadPageSplashScreenClosed

[EventStartupReadPageStartUpTrigger]
operations=EventStartupReadPageStartUpTriggeredPageIndex,=,1
buttons=1
event1=EventStartupInit
trigger=@EventStart

[EventStartupReadPageSplashScreenTrigger]
operations=EventStartupReadPageSplashScreenTriggeredPageIndex,=,3
buttons=1
event1=EventStartupInit
trigger=@SplashScreen

[EventStartupReadPageSplashScreenClosedTrigger]
operations=EventStartupReadPageSplashScreenClosedTriggeredPageIndex,=,4
buttons=1
event1=EventStartupInit
trigger=@SplashScreenClosed
