; Saved by version: 3.0.4

[EventStartupStart]
operations=StartupTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventStartupInit

[EventStartupInit]
operations=EventStartupExit,=,1
display=false
buttons=1
event1=EventStartupFirstTimeInitializer EventStartupPageSelector

[EventStartupFirstTimeInitializer]
operations=EventStartupInitialized,=,1 visibleStartupStartUp,=,1 visibleStartupShowEverything,=,1 visibleStartupSplashScreen,=,1 visibleStartupSplashScreenClosed,=,1 visibleStartupStartScenario,=,1 visibleStartupKate,=,1
vartests=VarOperation:EventStartupInitialized,==,0 
display=false
buttons=1
event1=EventStartupPageSelector

[EventStartupPageSelector]
display=false
buttons=1
event1=EventStartupReadPageStartUpXferIfTriggered EventStartupReadPageSplashScreenXferIfTriggered EventStartupReadPageSplashScreenClosedXferIfTriggered EventStartupToc

[EventStartupReadPageStartUpXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventStartupReadPageStartUp

[EventStartupReadPageStartUp]
operations=readStartupPreviousPage,=,1 readStartupStartUp,=,1
display=false
buttons=1
event1=EventStartupExpr1

[EventStartupExpr1]
comment=@(10, 13)
operations=EventStartupExpr1Temp,=,0
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet1

[EventStartupReadPageStartUpBeforeLet1]
operations=testMode,=,EventStartupExpr1Temp
display=false
buttons=1
event1=EventStartupExpr2

[EventStartupExpr2]
comment=@(12, 24)
operations=EventStartupExpr2Temp,=,5
display=false
buttons=1
event1=EventStartupExpr3

[EventStartupExpr3]
comment=@(12, 28)
operations=EventStartupExpr3Temp,=,#heros
display=false
buttons=1
event1=EventStartupExpr4

[EventStartupExpr4]
comment=@(12, 24)
operations=EventStartupExpr2Temp,-,EventStartupExpr3Temp
display=false
buttons=1
event1=EventStartupExpr5

[EventStartupExpr5]
comment=@(12, 38)
operations=EventStartupExpr5Temp,=,2
display=false
buttons=1
event1=EventStartupExpr6

[EventStartupExpr6]
comment=@(12, 23)
operations=EventStartupExpr2Temp,*,EventStartupExpr5Temp
display=false
buttons=1
event1=EventStartupExpr7

[EventStartupExpr7]
comment=@(12, 42)
operations=EventStartupExpr7Temp,=,15
display=false
buttons=1
event1=EventStartupExpr8

[EventStartupExpr8]
comment=@(12, 23)
operations=EventStartupExpr2Temp,+,EventStartupExpr7Temp
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet2

[EventStartupReadPageStartUpBeforeLet2]
operations=roundsBeforeRitual,=,EventStartupExpr2Temp
display=false
buttons=1
event1=EventStartupExpr9

[EventStartupExpr9]
comment=@(20, 20)
operations=EventStartupExpr9Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet3

[EventStartupReadPageStartUpBeforeLet3]
operations=wandererInStudy,=,EventStartupExpr9Temp
display=false
buttons=1
event1=EventStartupExpr10

[EventStartupExpr10]
comment=@(21, 22)
operations=EventStartupExpr10Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet4

[EventStartupReadPageStartUpBeforeLet4]
operations=wandererInLibrary,=,EventStartupExpr10Temp
display=false
buttons=1
event1=EventStartupExpr11

[EventStartupExpr11]
comment=@(22, 21)
operations=EventStartupExpr11Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet5

[EventStartupReadPageStartUpBeforeLet5]
operations=wandererInChapel,=,EventStartupExpr11Temp
display=false
buttons=1
event1=EventStartupExpr12

[EventStartupExpr12]
comment=@(23, 20)
operations=EventStartupExpr12Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet6

[EventStartupReadPageStartUpBeforeLet6]
operations=wandererInHall2,=,EventStartupExpr12Temp
display=false
buttons=1
event1=EventStartupExpr13

[EventStartupExpr13]
comment=@(24, 20)
operations=EventStartupExpr13Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet7

[EventStartupReadPageStartUpBeforeLet7]
operations=wandererInFoyer,=,EventStartupExpr13Temp
display=false
buttons=1
event1=EventStartupExpr14

[EventStartupExpr14]
comment=@(25, 22)
operations=EventStartupExpr14Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet8

[EventStartupReadPageStartUpBeforeLet8]
operations=wandererInGallery,=,EventStartupExpr14Temp
display=false
buttons=1
event1=EventStartupExpr15

[EventStartupExpr15]
comment=@(29, 18)
operations=EventStartupExpr15Temp,=,0
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet9

[EventStartupReadPageStartUpBeforeLet9]
operations=wandererCount,=,EventStartupExpr15Temp
display=false
buttons=1
event1=EventStartupExpr16

[EventStartupExpr16]
comment=@(34, 23)
operations=EventStartupExpr16Temp,=,5
display=false
buttons=1
event1=EventStartupExpr17

[EventStartupExpr17]
comment=@(34, 27)
operations=EventStartupExpr17Temp,=,#heros
display=false
buttons=1
event1=EventStartupExpr18

[EventStartupExpr18]
comment=@(34, 23)
operations=EventStartupExpr16Temp,-,EventStartupExpr17Temp
display=false
buttons=1
event1=EventStartupExpr19

[EventStartupExpr19]
comment=@(34, 37)
operations=EventStartupExpr19Temp,=,2
display=false
buttons=1
event1=EventStartupExpr20

[EventStartupExpr20]
comment=@(34, 22)
operations=EventStartupExpr16Temp,*,EventStartupExpr19Temp
display=false
buttons=1
event1=EventStartupExpr21

[EventStartupExpr21]
comment=@(34, 41)
operations=EventStartupExpr21Temp,=,2
display=false
buttons=1
event1=EventStartupExpr22

[EventStartupExpr22]
comment=@(34, 22)
operations=EventStartupExpr16Temp,+,EventStartupExpr21Temp
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet10

[EventStartupReadPageStartUpBeforeLet10]
operations=wandererFrequency,=,EventStartupExpr16Temp
display=false
buttons=1
event1=EventStartupExpr23

[EventStartupExpr23]
comment=@(37, 22)
operations=EventStartupExpr23Temp,=,wandererFrequency
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet11

[EventStartupReadPageStartUpBeforeLet11]
operations=wandererCountdown,=,EventStartupExpr23Temp
display=false
buttons=1
event1=EventStartupExpr24

[EventStartupExpr24]
comment=@(40, 16)
operations=EventStartupExpr24Temp,=,#heros
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet12

[EventStartupReadPageStartUpBeforeLet12]
operations=wandererMax,=,EventStartupExpr24Temp
display=false
buttons=1
event1=EventStartupExpr25

[EventStartupExpr25]
comment=@(46, 11)
operations=EventStartupExpr25Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet13

[EventStartupReadPageStartUpBeforeLet13]
operations=endWin,=,EventStartupExpr25Temp
display=false
buttons=1
event1=EventStartupExpr26

[EventStartupExpr26]
comment=@(47, 18)
operations=EventStartupExpr26Temp,=,2
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet14

[EventStartupReadPageStartUpBeforeLet14]
operations=endPartialWin,=,EventStartupExpr26Temp
display=false
buttons=1
event1=EventStartupExpr27

[EventStartupExpr27]
comment=@(48, 12)
operations=EventStartupExpr27Temp,=,3
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet15

[EventStartupReadPageStartUpBeforeLet15]
operations=endFail,=,EventStartupExpr27Temp
display=false
buttons=1
event1=EventStartupExpr28

[EventStartupExpr28]
comment=@(51, 17)
operations=EventStartupExpr28Temp,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet16

[EventStartupReadPageStartUpBeforeLet16]
operations=goalOpenGate,=,EventStartupExpr28Temp
display=false
buttons=1
event1=EventStartupExpr29

[EventStartupExpr29]
comment=@(52, 17)
operations=EventStartupExpr29Temp,=,2
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet17

[EventStartupReadPageStartUpBeforeLet17]
operations=goalFeedGate,=,EventStartupExpr29Temp
display=false
buttons=1
event1=EventStartupExpr30

[EventStartupExpr30]
comment=@(53, 18)
operations=EventStartupExpr30Temp,=,3
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet18

[EventStartupReadPageStartUpBeforeLet18]
operations=goalCloseGate,=,EventStartupExpr30Temp
display=false
buttons=1
event1=EventStartupExpr31

[EventStartupExpr31]
comment=@(55, 16)
operations=EventStartupExpr31Temp,=,3 rngInput,=,EventStartupExpr31Temp @callRng,=,1 EventStartupExpr31Temp,=,rngResult
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeLet19

[EventStartupReadPageStartUpBeforeLet19]
operations=goal,=,EventStartupExpr31Temp
display=false
buttons=1
event1=EventStartupExpr32 EventStartupTiePoint

[EventStartupExpr32]
comment=@(57, 9)
operations=EventStartupExpr32Temp,=,testMode
vartests=VarOperation:EventStartupExpr32Temp,>,0 
display=false
buttons=1
event1=EventStartupExpr33 EventStartupExpr34

[EventStartupExpr33]
comment=@(57, 5)
operations=EventStartupExpr32Temp,=,1
vartests=VarOperation:EventStartupExpr32Temp,==,0 
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeTrigger20

[EventStartupReadPageStartUpBeforeTrigger20]
operations=@SplashScreen,=,1
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeGoto7

[EventStartupReadPageStartUpBeforeGoto7]
display=false
buttons=1
event1=EventStartupEnd

[EventStartupEnd]
display=false
buttons=1
event1=

[EventStartupExpr34]
comment=@(57, 5)
operations=EventStartupExpr32Temp,=,0
display=false
buttons=1
event1=EventStartupReadPageStartUpBeforeTrigger20

[EventStartupTiePoint]
display=false
buttons=1
event1=EventStartupToc

[EventStartupToc]
display=false
buttons=1
event1=EventStartupTocSelector

[EventStartupTocSelector]
display=false
buttons=1
event1=EventStartupTocPrologStartUp EventStartupTocPrologShowEverything EventStartupTocPrologSplashScreen EventStartupTocPrologSplashScreenClosed EventStartupTocPrologStartScenario EventStartupTocPrologKate EventStartupTiePoint

[EventStartupTocPrologStartUp]
vartests=VarOperation:readStartupStartUp,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupStartUp,>,0 
display=false
buttons=1
event1=EventStartupReadPageStartUp

[EventStartupTocPrologShowEverything]
vartests=VarOperation:readStartupShowEverything,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupShowEverything,>,0 
display=false
buttons=1
event1=EventStartupReadPageShowEverything

[EventStartupReadPageShowEverything]
operations=readStartupPreviousPage,=,2 readStartupShowEverything,=,1
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove1

[EventStartupReadPageShowEverythingBeforeAddRemove1]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove2
add=TokenTestPlaceDriveway TokenTestTakeBooks TokenTestStartRitual

[EventStartupReadPageShowEverythingBeforeAddRemove2]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove3
add=TokenTestRitualPreparations TokenTestRitualFinished

[EventStartupReadPageShowEverythingBeforeAddRemove3]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove4
add=TokenTestPlaceTortureChamber TokenTestPlaceLibraryViaStudy

[EventStartupReadPageShowEverythingBeforeAddRemove4]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove5
add=TokenTestPlaceLibraryAfterCultists TokenTestPlaceChapelViaLibrary

[EventStartupReadPageShowEverythingBeforeAddRemove5]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove6
add=TokenTestPlaceKitchenViaDiningRoom TokenTestPlaceStudyViaHall2

[EventStartupReadPageShowEverythingBeforeAddRemove6]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove7
add=TokenTestPlaceHall2ViaHall1 TokenTestPlaceStudyViaFoyer

[EventStartupReadPageShowEverythingBeforeAddRemove7]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove8
add=TokenTestPlaceDungeonCell TokenTestPlaceCryptViaDungeonCave

[EventStartupReadPageShowEverythingBeforeAddRemove8]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove9
add=TokenTestPlaceDiningRoomViaBackdoor TokenTestPlaceCryptViaChapel

[EventStartupReadPageShowEverythingBeforeAddRemove9]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove10
add=TokenTestPlaceCoatRoomViaGallery TokenTestPlaceAltar

[EventStartupReadPageShowEverythingBeforeAddRemove10]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove11
add=TokenTestInitChosenInvestigator TokenTestPlaceDriveway

[EventStartupReadPageShowEverythingBeforeAddRemove11]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove12
add=TokenTestBasementViaDiningRoomSight TileStudy TileHall2

[EventStartupReadPageShowEverythingBeforeAddRemove12]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove13
add=TileGallery TileFoyer TileDriveway TileDiningRoom TileCrypt

[EventStartupReadPageShowEverythingBeforeAddRemove13]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove14
add=TileChapel TileBasement TileBackyard TileAltar

[EventStartupReadPageShowEverythingBeforeAddRemove14]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove15
add=TokenTestPlaceHall1ViaDiningRoom TokenTestPlaceFoyerViaGallery

[EventStartupReadPageShowEverythingBeforeAddRemove15]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove16
add=TokenTestPlaceGalleryViaFoyer TokenTestPlaceHall2ViaFoyer

[EventStartupReadPageShowEverythingBeforeAddRemove16]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove17
add=TokenTestPlaceFoyerViaHall2 TokenTestPlaceStudyViaFoyer

[EventStartupReadPageShowEverythingBeforeAddRemove17]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove18
add=TokenTestPlaceStudyViaHall2 TokenTestPlaceFoyerViaStudy

[EventStartupReadPageShowEverythingBeforeAddRemove18]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove19
add=TokenTestPlaceHall2ViaFoyer TokenTestPlaceDungeonCaveViaBasement

[EventStartupReadPageShowEverythingBeforeAddRemove19]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove20
add=TokenTestPlaceDungeonCaveViaCrypt TokenTestPlaceHall1ViaHall2

[EventStartupReadPageShowEverythingBeforeAddRemove20]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove21
add=TokenTestPlaceBackdoorViaDriveway TokenTestPlaceGalleryViaHall1

[EventStartupReadPageShowEverythingBeforeAddRemove21]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove22
add=TokenTestJournal2 TokenTestBenTrigger TileHall1

[EventStartupReadPageShowEverythingBeforeAddRemove22]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeAddRemove23
add=TileTortureChamber TokenBackyardBenBefore TokenDiningRoomBen

[EventStartupReadPageShowEverythingBeforeAddRemove23]
display=false
buttons=1
event1=EventStartupReadPageShowEverythingBeforeGoto8
add=TokenBackyardBenPassive TokenTestBackdoorLocked

[EventStartupReadPageShowEverythingBeforeGoto8]
display=false
buttons=1
event1=EventStartupEnd

[EventStartupTocPrologSplashScreen]
vartests=VarOperation:readStartupSplashScreen,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupSplashScreen,>,0 
display=false
buttons=1
event1=EventStartupReadPageSplashScreen

[EventStartupReadPageSplashScreen]
operations=readStartupPreviousPage,=,3 readStartupSplashScreen,=,1
display=false
buttons=1
event1=EventStartupReadPageSplashScreenBeforeAddRemove1

[EventStartupReadPageSplashScreenBeforeAddRemove1]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenDisplay
add=UIStoryImage UIStoryBackground UIOpenText UIStoryFrame UIOpeningTitle UIStoryContinue

[EventStartupReadPageSplashScreenDisplay]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenBase

[EventStartupReadPageSplashScreenBase]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenTiePoint

[EventStartupReadPageSplashScreenTiePoint]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenEnd

[EventStartupReadPageSplashScreenEnd]
display=false
buttons=1
event1=EventStartupTiePoint

[EventStartupTocPrologSplashScreenClosed]
vartests=VarOperation:readStartupSplashScreenClosed,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupSplashScreenClosed,>,0 
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosed

[EventStartupReadPageSplashScreenClosed]
operations=readStartupPreviousPage,=,4 readStartupSplashScreenClosed,=,1
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosedBeforeAddRemove1

[EventStartupReadPageSplashScreenClosedBeforeAddRemove1]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosedDisplay
remove=UIStoryImage UIStoryBackground UIOpenText UIStoryFrame UIOpeningTitle UIStoryContinue

[EventStartupReadPageSplashScreenClosedDisplay]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosedBase

[EventStartupReadPageSplashScreenClosedBase]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosedTiePoint

[EventStartupReadPageSplashScreenClosedTiePoint]
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosedEnd

[EventStartupReadPageSplashScreenClosedEnd]
display=false
buttons=1
event1=EventStartupTiePoint

[EventStartupTocPrologStartScenario]
vartests=VarOperation:readStartupStartScenario,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupStartScenario,>,0 
display=false
buttons=1
event1=EventStartupReadPageStartScenario

[EventStartupReadPageStartScenario]
operations=readStartupPreviousPage,=,5 readStartupStartScenario,=,1
display=false
buttons=1
event1=EventStartupReadPageStartScenarioDisplay

[EventStartupReadPageStartScenarioDisplay]
display=false
buttons=1
event1=EventStartupReadPageStartScenarioBase

[EventStartupReadPageStartScenarioBase]
buttons=1
event1=EventStartupReadPageStartScenarioTiePoint

[EventStartupReadPageStartScenarioTiePoint]
display=false
buttons=1
event1=EventStartupReadPageStartScenarioEnd

[EventStartupReadPageStartScenarioEnd]
display=false
buttons=1
event1=EventStartupTiePoint

[EventStartupTocPrologKate]
vartests=VarOperation:readStartupKate,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStartupKate,>,0 
display=false
buttons=1
event1=EventStartupReadPageKate

[EventStartupReadPageKate]
operations=readStartupPreviousPage,=,6 readStartupKate,=,1
display=false
buttons=1
event1=EventStartupReadPageKateDisplay

[EventStartupReadPageKateDisplay]
display=false
buttons=1
event1=EventStartupReadPageKateBase

[EventStartupReadPageKateBase]
buttons=1
event1=EventStartupReadPageKateTiePoint

[EventStartupReadPageKateTiePoint]
display=false
buttons=1
event1=EventStartupReadPageKateAfterTrigger1

[EventStartupReadPageKateAfterTrigger1]
operations=@PlaceDriveWay,=,1
display=false
buttons=1
event1=EventStartupReadPageKateEnd

[EventStartupReadPageKateEnd]
display=false
buttons=1
event1=EventStartupTiePoint

[EventStartupReadPageSplashScreenXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventStartupReadPageSplashScreen

[EventStartupReadPageSplashScreenClosedXferIfTriggered]
operations=EventStartupTriggeredPageIndex,=,0
vartests=VarOperation:EventStartupTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventStartupReadPageSplashScreenClosed

[EventStartupReadPageStartUpTrigger]
operations=EventStartupTriggeredPageIndex,=,1
display=false
buttons=1
event1=EventStartupInit
trigger=EventStart

[EventStartupReadPageSplashScreenTrigger]
operations=EventStartupTriggeredPageIndex,=,3
display=false
buttons=1
event1=EventStartupInit
trigger=@SplashScreen

[EventStartupReadPageSplashScreenClosedTrigger]
operations=EventStartupTriggeredPageIndex,=,4
display=false
buttons=1
event1=EventStartupInit
trigger=@SplashScreenClosed
