; Saved by version: 3.11

[EventStudyStart]
operations=StudyTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventStudyInit

[EventStudyInit]
operations=EventStudyExit,=,0
display=false
buttons=1
event1=EventStudyFirstTimeInitializer EventStudyExpr13

[EventStudyFirstTimeInitializer]
operations=EventStudyInitialized,=,1 visibleStudyExploreStudyViaHall2,=,1 visibleStudyExploreStudyViaHall2NoSarah,=,1 visibleStudyExploreStudyViaFoyer,=,1 visibleStudyExploreStudy,=,1 visibleStudyPlaceExploreFoyer,=,1 visibleStudyPlaceExploreLibrary,=,1 visibleStudyPlaceHealingStone,=,1 visibleStudySearchHealingStone,=,1
vartests=VarOperation:EventStudyInitialized,==,0 
display=false
buttons=1
event1=EventStudyExpr13

[EventStudyExpr13]
comment=@(5, 2)
operations=EventStudyReadPageExploreStudyViaHall2Expr1TempA,=,0
display=false
buttons=1
event1=EventStudyExpr14

[EventStudyExpr14]
comment=@(5, 2)
operations=visibleStudyExploreStudyViaHall2,=,EventStudyReadPageExploreStudyViaHall2Expr1TempA
display=false
buttons=1
event1=EventStudyExpr15

[EventStudyExpr15]
comment=@(13, 2)
operations=EventStudyReadPageExploreStudyViaHall2NoSarahExpr2TempA,=,0
display=false
buttons=1
event1=EventStudyExpr16

[EventStudyExpr16]
comment=@(13, 2)
operations=visibleStudyExploreStudyViaHall2NoSarah,=,EventStudyReadPageExploreStudyViaHall2NoSarahExpr2TempA
display=false
buttons=1
event1=EventStudyExpr17

[EventStudyExpr17]
comment=@(26, 2)
operations=EventStudyReadPageExploreStudyViaFoyerExpr3TempA,=,0
display=false
buttons=1
event1=EventStudyExpr18

[EventStudyExpr18]
comment=@(26, 2)
operations=visibleStudyExploreStudyViaFoyer,=,EventStudyReadPageExploreStudyViaFoyerExpr3TempA
display=false
buttons=1
event1=EventStudyExpr11

[EventStudyExpr11]
comment=@(54, 19)
operations=EventStudyExpr11Temp,=,exploredFoyer
display=false
buttons=1
event1=EventStudyExpr20 EventStudyExpr21

[EventStudyExpr20]
comment=@(54, 2)
operations=EventStudyExpr11Temp,=,1
vartests=VarOperation:EventStudyExpr11Temp,==,0 
display=false
buttons=1
event1=EventStudyExpr19

[EventStudyExpr19]
comment=@(54, 2)
display=false
buttons=1
event1=EventStudyExpr22

[EventStudyExpr22]
comment=@(54, 2)
operations=visibleStudyPlaceExploreFoyer,=,EventStudyExpr11Temp
display=false
buttons=1
event1=EventStudyExpr23

[EventStudyExpr23]
comment=@(86, 2)
operations=EventStudyReadPageSearchHealingStoneExpr4TempA,=,0
display=false
buttons=1
event1=EventStudyExpr24

[EventStudyExpr24]
comment=@(86, 2)
operations=visibleStudySearchHealingStone,=,EventStudyReadPageSearchHealingStoneExpr4TempA
display=false
buttons=1
event1=EventStudyTriggerPrologSelector

[EventStudyTriggerPrologSelector]
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneTriggeredPrologTarget EventStudyTriggerSelector

[EventStudyReadPageSearchHealingStoneTriggeredPrologTarget]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,8 
display=false
buttons=1
event1=EventStudyTocPrologSearchHealingStone

[EventStudyTocPrologSearchHealingStone]
buttons=2
event1=EventStudyReadPageSearchHealingStone
event2=EventStudyEnd

[EventStudyReadPageSearchHealingStone]
operations=readStudyPreviousPage,=,8 readStudySearchHealingStone,=,1
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneDisplay

[EventStudyReadPageSearchHealingStoneDisplay]
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneBase

[EventStudyReadPageSearchHealingStoneBase]
buttons=1
event1=EventStudyReadPageSearchHealingStoneTiePoint
add=QItemHealingStone

[EventStudyReadPageSearchHealingStoneTiePoint]
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneAfterAddRemove1

[EventStudyReadPageSearchHealingStoneAfterAddRemove1]
comment=@(103, 2)
display=false
buttons=1
event1=EventStudyExpr12
remove=TokenSearchStudyHealingStone

[EventStudyExpr12]
comment=@(105, 22)
operations=EventStudyExpr12Temp,=,1
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneAfterLet2

[EventStudyReadPageSearchHealingStoneAfterLet2]
comment=@(105, 2)
operations=foundHealingStone,=,EventStudyExpr12Temp
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStoneAfterGoto132

[EventStudyReadPageSearchHealingStoneAfterGoto132]
comment=@(106, 2)
display=false
buttons=1
event1=EventStudyEnd

[EventStudyEnd]
display=false
buttons=1
event1=

[EventStudyTriggerSelector]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2XferIfTriggered EventStudyReadPageExploreStudyViaHall2NoSarahXferIfTriggered EventStudyReadPageExploreStudyViaFoyerXferIfTriggered EventStudyReadPageExploreStudyXferIfTriggered EventStudyReadPagePlaceExploreFoyerXferIfTriggered EventStudyReadPagePlaceExploreLibraryXferIfTriggered EventStudyReadPagePlaceHealingStoneXferIfTriggered EventStudyReadPageSearchHealingStoneXferIfTriggered EventStudyToc

[EventStudyReadPageExploreStudyViaHall2XferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2

[EventStudyReadPageExploreStudyViaHall2]
operations=readStudyPreviousPage,=,1 readStudyExploreStudyViaHall2,=,1
display=false
buttons=1
event1=EventStudyExpr2

[EventStudyExpr2]
comment=@(8, 26)
operations=EventStudyExpr2Temp,=,1
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2BeforeLet1

[EventStudyReadPageExploreStudyViaHall2BeforeLet1]
comment=@(8, 2)
operations=exploredStudyViaHall2,=,EventStudyExpr2Temp
display=false
buttons=1
event1=EventStudyExpr3

[EventStudyExpr3]
comment=@(9, 26)
operations=EventStudyExpr3Temp,=,0
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2BeforeLet2

[EventStudyReadPageExploreStudyViaHall2BeforeLet2]
comment=@(9, 2)
operations=exploredStudyViaFoyer,=,EventStudyExpr3Temp
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2Display

[EventStudyReadPageExploreStudyViaHall2Display]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2Base

[EventStudyReadPageExploreStudyViaHall2Base]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2TiePoint

[EventStudyReadPageExploreStudyViaHall2TiePoint]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2End

[EventStudyReadPageExploreStudyViaHall2End]
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyTiePoint]
display=false
buttons=1
event1=EventStudyLoopBack EventStudyEnd

[EventStudyLoopBack]
vartests=VarOperation:EventStudyExit,==,0 
display=false
buttons=1
event1=EventStudyInit

[EventStudyReadPageExploreStudyViaHall2NoSarahXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarah

[EventStudyReadPageExploreStudyViaHall2NoSarah]
operations=readStudyPreviousPage,=,2 readStudyExploreStudyViaHall2NoSarah,=,1
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarahDisplay

[EventStudyReadPageExploreStudyViaHall2NoSarahDisplay]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarahBase

[EventStudyReadPageExploreStudyViaHall2NoSarahBase]
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarahTiePoint

[EventStudyReadPageExploreStudyViaHall2NoSarahTiePoint]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarahAfterGoto130

[EventStudyReadPageExploreStudyViaHall2NoSarahAfterGoto130]
comment=@(22, 2)
display=false
buttons=1
event1=EventStudyEnd

[EventStudyReadPageExploreStudyViaFoyerXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyer

[EventStudyReadPageExploreStudyViaFoyer]
operations=readStudyPreviousPage,=,3 readStudyExploreStudyViaFoyer,=,1
display=false
buttons=1
event1=EventStudyExpr8

[EventStudyExpr8]
comment=@(29, 26)
operations=EventStudyExpr8Temp,=,0
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerBeforeLet1

[EventStudyReadPageExploreStudyViaFoyerBeforeLet1]
comment=@(29, 2)
operations=exploredStudyViaHall2,=,EventStudyExpr8Temp
display=false
buttons=1
event1=EventStudyExpr9

[EventStudyExpr9]
comment=@(30, 26)
operations=EventStudyExpr9Temp,=,1
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerBeforeLet2

[EventStudyReadPageExploreStudyViaFoyerBeforeLet2]
comment=@(30, 2)
operations=exploredStudyViaFoyer,=,EventStudyExpr9Temp
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerDisplay

[EventStudyReadPageExploreStudyViaFoyerDisplay]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerBase

[EventStudyReadPageExploreStudyViaFoyerBase]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerTiePoint

[EventStudyReadPageExploreStudyViaFoyerTiePoint]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyerEnd

[EventStudyReadPageExploreStudyViaFoyerEnd]
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyReadPageExploreStudyXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventStudyReadPageExploreStudy

[EventStudyReadPageExploreStudy]
operations=readStudyPreviousPage,=,4 readStudyExploreStudy,=,1
display=false
buttons=1
event1=EventStudyReadPageExploreStudyBeforeAddRemove1

[EventStudyReadPageExploreStudyBeforeAddRemove1]
comment=@(39, 2)
display=false
buttons=1
event1=EventStudyReadPageExploreStudyBeforeAddRemove2
remove=TokenExploreStudyViaFoyer TokenExploreStudyViaHall2

[EventStudyReadPageExploreStudyBeforeAddRemove2]
comment=@(40, 2)
display=false
buttons=1
event1=EventStudyReadPageExploreStudyDisplay
add=TileStudy TokenDoorStudy

[EventStudyReadPageExploreStudyDisplay]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyBase

[EventStudyReadPageExploreStudyBase]
buttons=1
event1=EventStudyReadPageExploreStudyTiePoint

[EventStudyReadPageExploreStudyTiePoint]
display=false
buttons=1
event1=EventStudyExpr10

[EventStudyExpr10]
comment=@(50, 18)
operations=EventStudyExpr10Temp,=,1
display=false
buttons=1
event1=EventStudyReadPageExploreStudyAfterLet1

[EventStudyReadPageExploreStudyAfterLet1]
comment=@(50, 2)
operations=exploredStudy,=,EventStudyExpr10Temp
display=false
buttons=1
event1=EventStudyReadPageExploreStudyEnd

[EventStudyReadPageExploreStudyEnd]
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyReadPagePlaceExploreFoyerXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,5 
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyer

[EventStudyReadPagePlaceExploreFoyer]
operations=readStudyPreviousPage,=,5 readStudyPlaceExploreFoyer,=,1
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyerBeforeAddRemove1

[EventStudyReadPagePlaceExploreFoyerBeforeAddRemove1]
comment=@(56, 2)
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyerDisplay
add=TokenExploreFoyerViaStudy

[EventStudyReadPagePlaceExploreFoyerDisplay]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyerBase

[EventStudyReadPagePlaceExploreFoyerBase]
buttons=1
event1=EventStudyReadPagePlaceExploreFoyerTiePoint

[EventStudyReadPagePlaceExploreFoyerTiePoint]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyerEnd

[EventStudyReadPagePlaceExploreFoyerEnd]
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyReadPagePlaceExploreLibraryXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,6 
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibrary

[EventStudyReadPagePlaceExploreLibrary]
operations=readStudyPreviousPage,=,6 readStudyPlaceExploreLibrary,=,1
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibraryBeforeAddRemove1

[EventStudyReadPagePlaceExploreLibraryBeforeAddRemove1]
comment=@(65, 2)
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibraryDisplay
add=TokenExploreLibraryViaStudy

[EventStudyReadPagePlaceExploreLibraryDisplay]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibraryBase

[EventStudyReadPagePlaceExploreLibraryBase]
buttons=1
event1=EventStudyReadPagePlaceExploreLibraryTiePoint

[EventStudyReadPagePlaceExploreLibraryTiePoint]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibraryEnd

[EventStudyReadPagePlaceExploreLibraryEnd]
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyReadPagePlaceHealingStoneXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,7 
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStone

[EventStudyReadPagePlaceHealingStone]
operations=readStudyPreviousPage,=,7 readStudyPlaceHealingStone,=,1
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStoneBeforeAddRemove1

[EventStudyReadPagePlaceHealingStoneBeforeAddRemove1]
comment=@(74, 2)
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStoneDisplay
add=TokenSearchStudyHealingStone

[EventStudyReadPagePlaceHealingStoneDisplay]
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStoneBase

[EventStudyReadPagePlaceHealingStoneBase]
buttons=1
event1=EventStudyReadPagePlaceHealingStoneTiePoint

[EventStudyReadPagePlaceHealingStoneTiePoint]
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStoneAfterTrigger1

[EventStudyReadPagePlaceHealingStoneAfterTrigger1]
comment=@(81, 2)
operations=@MoveOnExplore,=,1
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStoneAfterGoto131

[EventStudyReadPagePlaceHealingStoneAfterGoto131]
comment=@(82, 2)
display=false
buttons=1
event1=EventStudyEnd

[EventStudyReadPageSearchHealingStoneXferIfTriggered]
operations=EventStudyTriggeredPageIndex,=,0
vartests=VarOperation:EventStudyTriggeredPageIndex,==,8 
display=false
buttons=1
event1=EventStudyReadPageSearchHealingStone

[EventStudyToc]
display=false
buttons=1
event1=EventStudyTocSelector

[EventStudyTocSelector]
display=false
buttons=1
event1=EventStudyTocPrologProxyExploreStudyViaHall2 EventStudyTocPrologProxyExploreStudyViaHall2NoSarah EventStudyTocPrologProxyExploreStudyViaFoyer EventStudyTocPrologProxyExploreStudy EventStudyTocPrologProxyPlaceExploreFoyer EventStudyTocPrologProxyPlaceExploreLibrary EventStudyTocPrologProxyPlaceHealingStone EventStudyTocPrologProxySearchHealingStone EventStudyTocNoPagesAvailable

[EventStudyTocPrologProxyExploreStudyViaHall2]
vartests=VarOperation:readStudyExploreStudyViaHall2,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyExploreStudyViaHall2,>,0 
display=false
buttons=1
event1=EventStudyTocPrologExploreStudyViaHall2

[EventStudyTocPrologExploreStudyViaHall2]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2

[EventStudyTocPrologProxyExploreStudyViaHall2NoSarah]
vartests=VarOperation:readStudyExploreStudyViaHall2NoSarah,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyExploreStudyViaHall2NoSarah,>,0 
display=false
buttons=1
event1=EventStudyTocPrologExploreStudyViaHall2NoSarah

[EventStudyTocPrologExploreStudyViaHall2NoSarah]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarah

[EventStudyTocPrologProxyExploreStudyViaFoyer]
vartests=VarOperation:readStudyExploreStudyViaFoyer,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyExploreStudyViaFoyer,>,0 
display=false
buttons=1
event1=EventStudyTocPrologExploreStudyViaFoyer

[EventStudyTocPrologExploreStudyViaFoyer]
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaFoyer

[EventStudyTocPrologProxyExploreStudy]
vartests=VarOperation:readStudyExploreStudy,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyExploreStudy,>,0 
display=false
buttons=1
event1=EventStudyTocPrologExploreStudy

[EventStudyTocPrologExploreStudy]
buttons=2
event1=EventStudyReadPageExploreStudy
event2=EventStudyEnd

[EventStudyTocPrologProxyPlaceExploreFoyer]
vartests=VarOperation:readStudyPlaceExploreFoyer,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyPlaceExploreFoyer,>,0 
display=false
buttons=1
event1=EventStudyTocPrologPlaceExploreFoyer

[EventStudyTocPrologPlaceExploreFoyer]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreFoyer

[EventStudyTocPrologProxyPlaceExploreLibrary]
vartests=VarOperation:readStudyPlaceExploreLibrary,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyPlaceExploreLibrary,>,0 
display=false
buttons=1
event1=EventStudyTocPrologPlaceExploreLibrary

[EventStudyTocPrologPlaceExploreLibrary]
display=false
buttons=1
event1=EventStudyReadPagePlaceExploreLibrary

[EventStudyTocPrologProxyPlaceHealingStone]
vartests=VarOperation:readStudyPlaceHealingStone,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudyPlaceHealingStone,>,0 
display=false
buttons=1
event1=EventStudyTocPrologPlaceHealingStone

[EventStudyTocPrologPlaceHealingStone]
display=false
buttons=1
event1=EventStudyReadPagePlaceHealingStone

[EventStudyTocPrologProxySearchHealingStone]
vartests=VarOperation:readStudySearchHealingStone,==,0 VarTestsLogicalOperator:AND VarOperation:visibleStudySearchHealingStone,>,0 
display=false
buttons=1
event1=EventStudyTocPrologSearchHealingStone

[EventStudyTocNoPagesAvailable]
operations=EventStudyExit,=,1
display=false
buttons=1
event1=EventStudyTiePoint

[EventStudyExpr21]
comment=@(54, 2)
operations=EventStudyExpr11Temp,=,0
display=false
buttons=1
event1=EventStudyExpr19

[EventStudyReadPageExploreStudyViaHall2Trigger]
operations=EventStudyTriggeredPageIndex,=,1
display=false
buttons=1
event1=EventStudyExpr1
trigger=VarExploreStudyViaHall2

[EventStudyExpr1]
comment=@(6, 42)
operations=EventStudyExpr1Temp,=,foundSarah
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2TriggerFail EventStudyInit

[EventStudyReadPageExploreStudyViaHall2TriggerFail]
vartests=VarOperation:EventStudyExpr1Temp,==,0 
display=false
buttons=1
event1=EventStudyEnd

[EventStudyReadPageExploreStudyViaHall2NoSarahTrigger]
operations=EventStudyTriggeredPageIndex,=,2
display=false
buttons=1
event1=EventStudyExpr4
trigger=VarExploreStudyViaHall2

[EventStudyExpr4]
comment=@(14, 46)
operations=EventStudyExpr4Temp,=,foundSarah
display=false
buttons=1
event1=EventStudyExpr6 EventStudyExpr7

[EventStudyExpr6]
comment=@(14, 42)
operations=EventStudyExpr4Temp,=,1
vartests=VarOperation:EventStudyExpr4Temp,==,0 
display=false
buttons=1
event1=EventStudyExpr5

[EventStudyExpr5]
comment=@(14, 42)
display=false
buttons=1
event1=EventStudyReadPageExploreStudyViaHall2NoSarahTriggerFail EventStudyInit

[EventStudyReadPageExploreStudyViaHall2NoSarahTriggerFail]
vartests=VarOperation:EventStudyExpr4Temp,==,0 
display=false
buttons=1
event1=EventStudyEnd

[EventStudyExpr7]
comment=@(14, 42)
operations=EventStudyExpr4Temp,=,0
display=false
buttons=1
event1=EventStudyExpr5

[EventStudyReadPageExploreStudyViaFoyerTrigger]
operations=EventStudyTriggeredPageIndex,=,3
display=false
buttons=1
event1=EventStudyInit
trigger=VarExploreStudyViaFoyer

[EventStudyReadPageSearchHealingStoneTrigger]
operations=EventStudyTriggeredPageIndex,=,8
display=false
buttons=1
event1=EventStudyInit
trigger=VarSearchStudyHealingStone
