; Saved by version: 3.10

[TokenSearchDrivewayJournal]
xposition=6.191895
yposition=3.210649
operations=@SearchOutsideJournal,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreDiningRoomViaBackyard]
xposition=-1.75
yposition=3.5
operations=@ExploreDiningRoomViaBackyard,=,1
display=false
buttons=1
event1=
type=TokenExplore

[TokenSearchBackyardRandom]
xposition=0.6820569
yposition=1.273813
operations=@SearchBackyardRandom,=,1
display=false
buttons=1
event1=
type=TokenSearch

[TokenDrivewayInvestigators]
xposition=5.25
yposition=5.25
display=false
buttons=0
type=TokenInvestigators

[TokenExploreKitchenViaDiningRoom]
xposition=-0.008407762
yposition=5.166533
operations=exploredKitchenViaDiningRoom,=,1 @ExploreKitchenViaDiningRoom,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreBasementFirst]
xposition=-1.75
yposition=10.5
buttons=2
event1=EventExploreBasementBrawnFirst
event2=EventExploreBasementBrainFirst
type=TokenExplore

[TokenSearchChapelViaCrypt]
xposition=-16.79732
yposition=15.71615
operations=exploredChapelViaCrypt,=,0
buttons=1
event1=EventExploreChapelViaCrypt
add=QItemKey
type=TokenSearch

[TokenWallHall1]
xposition=-8.75
yposition=3.5
buttons=1
event1=
type=TokenWallInside
rotation=180

[TokenExploreBasementSecond]
xposition=-1.75
yposition=10.5
buttons=2
event1=EventExploreBasementBrawnSecond
event2=EventExploreBasementBrainSecond
type=TokenExplore

[TokenExploreBasementThird]
xposition=-1.75
yposition=10.5
buttons=2
event1=EventExploreBasementBrawnThird
event2=EventExploreBasementBrainThird
type=TokenExplore

[TokenExploreBasementViaDiningRoom]
xposition=-1.75
yposition=10.5
operations=@ExploreBasementViaDiningRoom,=,1
display=false
buttons=1
event1=Event0
type=TokenSight

[TokenDiningRoomDarknessTop]
xposition=-1.75
yposition=8.75
buttons=1
event1=
type=TokenDarkness

[TokenDiningRoomDarknessBottom]
xposition=-1.75
yposition=5.25
buttons=1
event1=
type=TokenDarkness

[TokenExploreHall1ViaDiningRoom]
xposition=-3.5
yposition=5.25
operations=exploredHall1ViaDiningRoom,=,1 @ExploreHall1ViaDiningRoom,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchHall1Painting]
xposition=-8.74381
yposition=3.670119
operations=@SearchHall1Painting,=,0
buttons=1
event1=
type=TokenSearch

[TokenSearchHall1Rug]
xposition=-8.336265
yposition=4.565389
operations=@SearchHall1Rug,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreGalleryViaHall1]
xposition=-5.25
yposition=7
operations=@ExploreGalleryViaHall1,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchFoyerSpellLeft]
xposition=-18.90788
yposition=10.04326
operations=@SearchFoyerSpell,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenDrivewayBen]
xposition=6.212849
yposition=3.230453
display=false
buttons=2
event1=
event2=
type=TokenPurpleMan

[TokenExploreLibraryViaStudy]
xposition=-21
yposition=1.75
operations=@ExploreLibraryViaStudy,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreFoyerViaHall2]
xposition=-12.25
yposition=7
operations=@ExploreFoyerViaHall2,=,1
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchKitchenCutlery]
xposition=2.688401
yposition=7.943312
operations=@SearchKitchenCutlery,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenSearchDiningRoomPaper]
xposition=-0.6698923
yposition=9.053431
operations=@SearchDiningRoomPaper,=,1
display=false
buttons=0
type=TokenSearch

[TokenExploreKitchenViaDriveway]
xposition=3.5
yposition=5.25
buttons=1
event1=EventExploreKitchenViaDriveway
type=TokenExplore

[TokenSarah]
xposition=-5.25
yposition=5.25
operations=@TalkToSarah,=,1
display=false
buttons=1
event1=Event0
type=TokenGreenWoman

[TokenSearchLibraryBookcase]
xposition=-22.75
yposition=7
operations=@SearchLibraryBookcase,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenLibraryTrapDoor]
xposition=-22.73829
yposition=6.487503
buttons=1
event1=
type=TokenSecretInside

[TokenExploreChapelViaLibrary]
xposition=-22.75
yposition=7
operations=@ExploreChapelViaStudy,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchChapelRitualComponents]
xposition=-21.74766
yposition=14.98724
operations=@SearchChapelRitualComponents,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenSearchChapelWhiskey]
xposition=-22.6724
yposition=18.32393
operations=@SearchChapelWhiskey,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenChapelPriestAlive]
xposition=-19.25
yposition=15.75
operations=@TalkToChapelPriest,=,1
display=false
buttons=0
type=TokenWhiteMan

[TokenTestExploreStudyViaFoyer]
xposition=-19.29036
yposition=7.654779
operations=@ExploreStudyViaFoyer,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreDiningRoomViaBackyard]
xposition=-1.750001
yposition=2.929935
operations=talkedToBenCount,=,2 @TalkedToBackyardBen,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenPortal]
xposition=-1.75
yposition=19.25
buttons=1
event1=
type=TokenOrangeMan

[TokenSearchCryptPendant]
xposition=-12.94028
yposition=15.646
operations=@SearchCryptPendant,=,1
display=false
buttons=0
type=TokenSearch

[TokenTestExploreBasementViaDiningRoom]
xposition=-1.738045
yposition=9.881679
operations=@ExploreBasementViaDiningRoom,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreKitchenViaDiningRoom]
xposition=-0.5085647
yposition=5.201355
operations=@ExploreKitchenViaDiningRoom,=,1
buttons=2
event1=Event0
event2=
type=TokenClue

[TokenTestExploreHall2ViaHall1]
xposition=-9.967709
yposition=5.229212
operations=@ExploreHall2viaHall1,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreStudyViaHall2]
xposition=-16.96588
yposition=5.289395
operations=@ExploreStudyViaHall2,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreLibraryViaStudy]
xposition=-20.43945
yposition=1.799177
operations=@ExploreLibraryViaStudy,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreChapelViaLibrary]
xposition=-22.68889
yposition=6.455462
operations=@ExploreChapelViaLibrary,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreLibraryAfterCultist]
xposition=-19.9812
yposition=1.164665
operations=@DefeatedCustomMonsterLibraryCultist,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreDungeonCaveViaCrypt]
xposition=-11.00262
yposition=15.7141
operations=@ExploreDungeonCaveViaCrypt,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreCryptViaChapel]
xposition=-18.79905
yposition=16.71836
operations=@ExploreCryptViaChapel,=,0
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreCryptViaDungeonCave]
xposition=-9.937457
yposition=15.76596
operations=@ExploreCryptViaDungeonCave,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreTortureChamberViaDungeonCave]
xposition=-8.748171
yposition=16.89929
operations=@ExploreTortureChamberViaDungeonCave,=,1
display=false
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreDungeonCellViaTortureChamber]
xposition=-6.157285
yposition=19.12844
operations=@ExploreDungeonCellViaTortureChamber,=,1
buttons=1
event1=EventTestPlaceDungeonCellYes
type=TokenClue

[TokenTestExploreAltar]
xposition=-2.852954
yposition=18.26583
operations=@ExploreAltar,=,1
buttons=1
event1=EventPlaceAltar
type=TokenClue

[TokenDyingWoman]
xposition=0.597877
yposition=20.11226
buttons=1
event1=
type=TokenWhiteWoman

[TokenCellHoleInTheWall]
xposition=-3.776896
yposition=19.29408
buttons=1
event1=
type=TokenSecretOutside
rotation=270

[TokenExploreCellViaTortureChamber]
xposition=-5.553874
yposition=19.18092
display=false
buttons=1
event1=EventPlaceCell
type=TokenExplore

[TokenTestDWM]
xposition=-7.075813
yposition=-3.040935
display=false
buttons=0
type=TokenInteract

[TokenSearchCryptViaChapel]
xposition=-18.91576
yposition=15.45179
operations=@SearchCryptViaChapel,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreFoyerViaGallery]
xposition=-10.5
yposition=12.25
operations=@ExploreFoyerViaGallery,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreCoatRoomViaGallery]
xposition=-5.809877
yposition=11.74914
operations=@ExploreCoatRoomViaGallery,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchGalleryDvm]
xposition=-7.833254
yposition=9.129033
operations=@SearchGalleryDvm,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenHall1Investigators]
xposition=-8.75
yposition=5.25
display=false
buttons=0
type=TokenInvestigators

[TokenSearchCoatRoomEvidence]
xposition=-6.107967
yposition=13.19925
operations=@SearchCoatRoomEvidence,=,1
display=false
buttons=1
event1=
type=TokenSearch

[TokenSearchBasementTrapdoor]
xposition=-2.1444
yposition=15.72703
operations=@SearchBasementTrapdoor,=,1
display=false
buttons=0
type=TokenSearch

[TokenBasementDarkness1]
xposition=1.75
yposition=12.25
buttons=1
event1=
type=TokenDarkness

[TokenBasementDarkness2]
xposition=1.75
yposition=15.75
buttons=1
event1=
type=TokenDarkness

[TokenBasementDarkness3]
xposition=-1.75
yposition=15.75
buttons=1
event1=
type=TokenDarkness

[TokenBasementDarkness4]
xposition=-1.75
yposition=12.25
buttons=1
event1=
type=TokenDarkness

[TokenSearchBasementEvidence]
xposition=1.75
yposition=12.25
operations=@SearchBasementEvidence,=,1
display=false
buttons=0
type=TokenSearch

[TokenBasementWall]
xposition=-3.5
yposition=15.75
buttons=1
event1=
type=TokenWallOutside
rotation=90

[TokenExploreDungeonCaveViaBasement]
xposition=-3.5
yposition=15.75
operations=@ExploreDungeonCaveViaBasement,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreTortureChamberViaDungeonCave]
xposition=-8.75
yposition=17.5
operations=@ExploreTortureChamberViaDungeonCave,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenSearchTortureChamberRandom]
xposition=-6.815581
yposition=18.06973
operations=@SearchTortureChamberRandom,=,1
display=false
buttons=0
type=TokenSearch

[TokenTestTakeBooks]
xposition=-10.5
yposition=1.75
buttons=1
event1=EventTestTakeJournal
type=TokenBarricadeInside

[TokenSearchCellDavidsSon]
xposition=-4.712907
yposition=18.36265
operations=@SearchCellDavidsSon,=,1
buttons=1
event1=
type=TokenOrangeMan

[TokenTestStartRitual]
xposition=-7
yposition=1.75
buttons=2
event1=EventTestStartRitualYes
event2=
type=TokenSearch

[TokenTestRitualPreparations]
xposition=-5.808914
yposition=1.262633
buttons=1
event1=EventTestRitualPreparations
add=QItemDvm
type=TokenBarricadeOutside

[TokenAltarInvestigators]
xposition=-1.75
yposition=19.25
display=false
buttons=0
type=TokenInvestigators

[TokenChapelTrapdoor]
xposition=-23.16766
yposition=15.47866
buttons=1
event1=
type=TokenTrapdoor
rotation=270

[TokenTestRitualFinished]
xposition=-6.914196
yposition=0.4850351
buttons=1
event1=EventTestRitualFinishedYes
type=TokenSearch

[TokenSearchLibraryKey]
xposition=-22.83057
yposition=1.538146
operations=@SearchLibraryKey,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenWallLibrary]
xposition=-24.5
yposition=5.25
buttons=1
event1=
type=TokenWallInsideGreen
rotation=90

[TokenSearchStudyHealingStone]
xposition=-19.25622
yposition=3.183688
operations=@SearchFoyerHealingStone,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreFoyerViaStudy]
xposition=-19.25
yposition=7
operations=@ExploreFoyerViaStudy,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenDoorStudy]
xposition=-19.30459
yposition=7.229941
buttons=1
event1=
type=TokenDoorInside

[TokenExploreStudyViaFoyer]
xposition=-19.25
yposition=7
operations=@ExploreStudyViaFoyer,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenWallHall2]
xposition=-12.25744
yposition=3.545928
display=false
buttons=0
type=TokenWallInsideGreen
rotation=180

[TokenSearchFoyerRandom]
xposition=-13.72323
yposition=13.04985
operations=@SearchFoyerRandom,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenSearchDrivewayGardenTool]
xposition=6.239617
yposition=0.9080851
operations=@SearchDrivewayGardenTool,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenTestExploreDrivewayViaStartup]
xposition=5.25
yposition=7
operations=@ExploreDrivewayViaStartup,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenExploreBackyardViaDrivewayBlocked]
xposition=3.5
yposition=1.75
operations=@ExploreBackyardViaDrivewayBlocked,=,1
display=false
buttons=1
event1=Event0
quota=2
type=TokenExplore

[TokenExploreBackyardViaDriveway]
xposition=3.5
yposition=1.75
operations=@ExploreBackyardViaDriveway,=,1
display=false
buttons=1
event1=Event0
type=TokenSight

[TokenDoorBackyard]
xposition=3.735622
yposition=1.696659
display=false
buttons=0
type=TokenDoorOutside
rotation=270

[TokenSearchBackyard2x4]
xposition=2.586402
yposition=2.604879
operations=@SearchBackyard2x4,=,1
display=false
buttons=1
event1=
type=TokenSearch

[TokenSearchDiningRoomFluxStabilizer]
xposition=-1.61464
yposition=5.707043
operations=@SearchDiningRoomFluxStabilizer,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreCryptViaDungeonCave]
xposition=-10.5
yposition=15.75
operations=@ExploreCryptViaDungeonCave,=,1
display=false
buttons=1
event1=Event0
type=TokenSight

[TokenTestExploreGalleryViaHall1]
xposition=-5.242519
yposition=6.428629
operations=@ExploreGalleryViaHall1,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestInitChosenInvestigator]
xposition=-10.5
yposition=0
operations=testChosenInvestigator,=,1
display=false
buttons=1
event1=
type=TokenBlueWoman

[TokenTestExploreCoatRoomViaGallery]
xposition=-5.831838
yposition=11.19938
operations=@ExploreCoatRoomViaGallery,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreBackyardViaDriveway]
xposition=4.011311
yposition=1.761426
operations=backyardGateUnlocked,=,1 @ExploreBackyardViaDriveway,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreHall1ViaDiningRoom]
xposition=-2.980126
yposition=5.252882
operations=@ExploreHall1ViaDiningRoom,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreDungeonCaveViaBasement]
xposition=-3.006399
yposition=15.72731
operations=@ExploreDungeonCaveViaBasement,=,0
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreFoyerViaHall2]
xposition=-12.25727
yposition=6.334094
operations=@ExploreFoyerViaHall2,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreHall2ViaFoyer]
xposition=-12.2316
yposition=7.613987
operations=@ExploreHall2ViaFoyer,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreFoyerViaGallery]
xposition=-9.940687
yposition=12.25063
operations=@ExploreFoyerViaGallery,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenTestExploreFoyerViaStudy]
xposition=-19.28355
yposition=6.366255
operations=@ExploreFoyerViaStudy,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenSearchKitchenRandom]
xposition=1.909069
yposition=4.337167
operations=@SearchKitchenRandom,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenTestJournal2]
xposition=-7
yposition=-1.75
buttons=2
event1=EventJournalStart
event2=
type=TokenInteract

[TokenSearchFoyerCandles]
xposition=-11.13451
yposition=8.521326
operations=@SearchFoyerCandles,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenBackyardBenBefore]
xposition=-2.222815
yposition=2.618721
operations=@BenBefore,=,1
display=false
buttons=1
event1=Event0
type=TokenPurpleMan

[TokenTestBenTrigger]
xposition=-8.75
yposition=0
operations=@TalkedToBackyardBen,=,1
buttons=1
event1=
type=TokenEricColt

[TokenSearchCryptHenry]
xposition=-15.10962
yposition=15.77754
operations=@SearchCryptHenry,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenExploreEscapeViaChapelLocked]
xposition=-22.74345
yposition=20.83925
operations=@ExploreEscapeViaChapelLocked,=,1
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreEscapeViaChapelAjar]
xposition=-22.73807
yposition=20.85626
display=false
buttons=1
event1=EventExploreChapel2Escape
type=TokenExplore

[TokenInteractEscape]
xposition=-22.74562
yposition=20.87976
operations=escaped,+,1
buttons=1
event1=EventInteractEscape1 EventInteractEscape2 EventInteractEscape3 EventInteractEscape4 EventInteractEscape5
type=TokenInteract

[TokenDavidSmythesSonRescuable]
xposition=-4.715067
yposition=18.34968
buttons=1
event1=
type=TokenOrangeMan

[TokenDoorDiningRoom]
xposition=-3.5
yposition=5.25
display=false
buttons=0
type=TokenDoorInside
rotation=90

[TokenExploreFoyerFrontDoor]
xposition=-15.78244
yposition=13.4859
operations=@ExploreFoyerFrontDoor,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenDoorHall1]
xposition=-5.265403
yposition=7.005507
display=false
buttons=0
type=TokenDoorInside

[TokenInvestigatorsDiningRoom]
xposition=-1.75
yposition=5.25
display=false
buttons=0
type=TokenInvestigators

[TokenTestBackdoorLocked]
xposition=-14
yposition=-1.75
buttons=1
event1=EventBackDoorLockedStart
type=TokenSearch

[TokenExploreStudyViaHall2]
xposition=-17.5
yposition=5.25
operations=@ExploreStudyViaHall2,=,1
display=false
buttons=1
event1=Event0
type=TokenExplore

[TokenExploreHall1ViaDiningRoomLocked]
xposition=-3.5
yposition=5.25
operations=@ExploreHall1ViaDiningRoomLocked,=,1
display=false
buttons=0
type=TokenExplore

[TokenBackyardBenPassive]
xposition=-1.967565
yposition=2.341855
buttons=1
event1=
type=TokenPurpleMan

[TokenExploreAltarViaCell]
xposition=-3.5
yposition=19.25
operations=@ExploreAltarViaCell,=,1
display=false
buttons=1
event1=Event0
type=TokenSight

[TokenDiningRoomBen]
xposition=-2.624588
yposition=4.434726
operations=@BenAfter,=,1
display=false
buttons=1
event1=Event0
type=TokenPurpleMan

[Token0]
xposition=-5.25
yposition=-1.75
buttons=1
event1=PuzzleFluxStabilizer
type=TokenRedWoman

[TokenTestSearchFluxStabilizer]
xposition=-1.75
yposition=5.25
operations=@SearchDiningRoomFluxStabilizer,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenSearchHall2Evidence]
xposition=-16.68821
yposition=4.221417
operations=@SearchHall2Evidence,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenSearchFoyerSpellRight]
xposition=-12.61886
yposition=10.14136
operations=@SearchFoyerSpell,=,1
display=false
buttons=1
event1=Event0
type=TokenSearch

[TokenChapelWall]
xposition=-17.5
yposition=15.75
display=false
buttons=0
type=TokenWallInside
rotation=270

[TokenExploreDungeonCaveViaCrypt]
xposition=-10.5
yposition=15.75
operations=@ExploreDungeonCaveViaCrypt,=,1
display=false
buttons=1
event1=Event0
type=TokenSight

[TokenDungeonCaveWall]
xposition=-3.332885
yposition=15.77457
display=false
buttons=0
type=TokenWallOutside
rotation=270

[TokenTestExploreHall2ViaStudy]
xposition=-18.63199
yposition=5.349231
operations=@ExploreHall2ViaStudy,=,1
buttons=1
event1=Event0
type=TokenClue

[TokenExploreHall2ViaStudy]
xposition=-19.25
yposition=5.25
buttons=1
event1=
type=TokenExplore

[TokenExploreBackyardViaDiningRoomBlocked]
xposition=-1.75
yposition=3.5
buttons=1
event1=
type=TokenExplore

[TokenExploreGalleryViaHall1Sight]
xposition=-5.25
yposition=7
operations=@ExploreGalleryViaHall1,=,1
display=false
buttons=1
event1=Event0
type=TokenSight
