; Saved by version: 3.13

[EventTortureChamberStart]
operations=TortureChamberTriggeredPageIndex,=,0
display=false
buttons=1
event1=EventTortureChamberInit

[EventTortureChamberInit]
operations=EventTortureChamberExit,=,0
display=false
buttons=1
event1=EventTortureChamberFirstTimeInitializer EventTortureChamberExpr2

[EventTortureChamberFirstTimeInitializer]
operations=EventTortureChamberInitialized,=,1 visibleTortureChamberPlace,=,1 visibleTortureChamberPlaceRandom,=,1 visibleTortureChamberPlaceExploreCell,=,1 visibleTortureChamberSearchRandom,=,1
vartests=VarOperation:EventTortureChamberInitialized,==,0 
display=false
buttons=1
event1=EventTortureChamberExpr2

[EventTortureChamberExpr2]
comment=@(47, 2)
operations=EventTortureChamberReadPageSearchRandomExpr1TempA,=,0
display=false
buttons=1
event1=EventTortureChamberExpr3

[EventTortureChamberExpr3]
comment=@(47, 2)
operations=visibleTortureChamberSearchRandom,=,EventTortureChamberReadPageSearchRandomExpr1TempA
display=false
buttons=1
event1=EventTortureChamberTriggerPrologSelector

[EventTortureChamberTriggerPrologSelector]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceTriggeredPrologTarget EventTortureChamberReadPageSearchRandomTriggeredPrologTarget EventTortureChamberTriggerSelector

[EventTortureChamberReadPagePlaceTriggeredPrologTarget]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventTortureChamberTocPrologPlace

[EventTortureChamberTocPrologPlace]
buttons=2
event1=EventTortureChamberReadPagePlace
event2=EventTortureChamberEnd

[EventTortureChamberReadPagePlace]
operations=readTortureChamberPreviousPage,=,1 readTortureChamberPlace,=,1
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceDisplay

[EventTortureChamberReadPagePlaceDisplay]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceBase

[EventTortureChamberReadPagePlaceBase]
buttons=1
event1=EventTortureChamberReadPagePlaceTiePoint

[EventTortureChamberReadPagePlaceTiePoint]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceAfterAddRemove1

[EventTortureChamberReadPagePlaceAfterAddRemove1]
comment=@(23, 2)
display=false
buttons=1
event1=EventTortureChamberExpr1
remove=TokenExploreTortureChamberViaDungeonCave

[EventTortureChamberExpr1]
comment=@(25, 27)
operations=EventTortureChamberExpr1Temp,=,1
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceAfterLet2

[EventTortureChamberReadPagePlaceAfterLet2]
comment=@(25, 2)
operations=exploredTortureChamber,=,EventTortureChamberExpr1Temp
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceEnd

[EventTortureChamberReadPagePlaceEnd]
display=false
buttons=1
event1=EventTortureChamberTiePoint

[EventTortureChamberTiePoint]
display=false
buttons=1
event1=EventTortureChamberLoopBack EventTortureChamberEnd

[EventTortureChamberLoopBack]
vartests=VarOperation:EventTortureChamberExit,==,0 
display=false
buttons=1
event1=EventTortureChamberInit

[EventTortureChamberEnd]
display=false
buttons=1
event1=

[EventTortureChamberReadPageSearchRandomTriggeredPrologTarget]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventTortureChamberTocPrologSearchRandom

[EventTortureChamberTocPrologSearchRandom]
buttons=2
event1=EventTortureChamberReadPageSearchRandom
event2=EventTortureChamberEnd

[EventTortureChamberReadPageSearchRandom]
operations=readTortureChamberPreviousPage,=,4 readTortureChamberSearchRandom,=,1
display=false
buttons=1
event1=EventTortureChamberReadPageSearchRandomBeforeAddRemove1

[EventTortureChamberReadPageSearchRandomBeforeAddRemove1]
comment=@(53, 2)
display=false
buttons=1
event1=EventTortureChamberReadPageSearchRandomDisplay
remove=TokenSearchTortureChamberRandom

[EventTortureChamberReadPageSearchRandomDisplay]
display=false
buttons=1
event1=EventTortureChamberReadPageSearchRandomBase

[EventTortureChamberReadPageSearchRandomBase]
buttons=1
event1=EventTortureChamberReadPageSearchRandomTiePoint

[EventTortureChamberReadPageSearchRandomTiePoint]
display=false
buttons=1
event1=EventTortureChamberReadPageSearchRandomAfterGoto138

[EventTortureChamberReadPageSearchRandomAfterGoto138]
comment=@(61, 2)
display=false
buttons=1
event1=EventTortureChamberEnd

[EventTortureChamberTriggerSelector]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceXferIfTriggered EventTortureChamberReadPagePlaceRandomXferIfTriggered EventTortureChamberReadPagePlaceExploreCellXferIfTriggered EventTortureChamberReadPageSearchRandomXferIfTriggered EventTortureChamberToc

[EventTortureChamberReadPagePlaceXferIfTriggered]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,1 
display=false
buttons=1
event1=EventTortureChamberReadPagePlace

[EventTortureChamberReadPagePlaceRandomXferIfTriggered]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,2 
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandom

[EventTortureChamberReadPagePlaceRandom]
operations=readTortureChamberPreviousPage,=,2 readTortureChamberPlaceRandom,=,1
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandomBeforeAddRemove1

[EventTortureChamberReadPagePlaceRandomBeforeAddRemove1]
comment=@(29, 2)
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandomDisplay
add=TokenSearchTortureChamberRandom

[EventTortureChamberReadPagePlaceRandomDisplay]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandomBase

[EventTortureChamberReadPagePlaceRandomBase]
buttons=1
event1=EventTortureChamberReadPagePlaceRandomTiePoint

[EventTortureChamberReadPagePlaceRandomTiePoint]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandomEnd

[EventTortureChamberReadPagePlaceRandomEnd]
display=false
buttons=1
event1=EventTortureChamberTiePoint

[EventTortureChamberReadPagePlaceExploreCellXferIfTriggered]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,3 
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCell

[EventTortureChamberReadPagePlaceExploreCell]
operations=readTortureChamberPreviousPage,=,3 readTortureChamberPlaceExploreCell,=,1
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellBeforeAddRemove1

[EventTortureChamberReadPagePlaceExploreCellBeforeAddRemove1]
comment=@(38, 2)
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellDisplay
add=TokenExploreCellViaTortureChamber

[EventTortureChamberReadPagePlaceExploreCellDisplay]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellBase

[EventTortureChamberReadPagePlaceExploreCellBase]
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellTiePoint

[EventTortureChamberReadPagePlaceExploreCellTiePoint]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellAfterTrigger1

[EventTortureChamberReadPagePlaceExploreCellAfterTrigger1]
comment=@(42, 2)
operations=@MoveAfterExplore,=,1
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCellAfterGoto137

[EventTortureChamberReadPagePlaceExploreCellAfterGoto137]
comment=@(43, 2)
display=false
buttons=1
event1=EventTortureChamberEnd

[EventTortureChamberReadPageSearchRandomXferIfTriggered]
operations=EventTortureChamberTriggeredPageIndex,=,0
vartests=VarOperation:EventTortureChamberTriggeredPageIndex,==,4 
display=false
buttons=1
event1=EventTortureChamberReadPageSearchRandom

[EventTortureChamberToc]
display=false
buttons=1
event1=EventTortureChamberTocSelector

[EventTortureChamberTocSelector]
display=false
buttons=1
event1=EventTortureChamberTocPrologProxyPlace EventTortureChamberTocPrologProxyPlaceRandom EventTortureChamberTocPrologProxyPlaceExploreCell EventTortureChamberTocPrologProxySearchRandom EventTortureChamberTocNoPagesAvailable

[EventTortureChamberTocPrologProxyPlace]
vartests=VarOperation:readTortureChamberPlace,==,0 VarTestsLogicalOperator:AND VarOperation:visibleTortureChamberPlace,>,0 
display=false
buttons=1
event1=EventTortureChamberTocPrologPlace

[EventTortureChamberTocPrologProxyPlaceRandom]
vartests=VarOperation:readTortureChamberPlaceRandom,==,0 VarTestsLogicalOperator:AND VarOperation:visibleTortureChamberPlaceRandom,>,0 
display=false
buttons=1
event1=EventTortureChamberTocPrologPlaceRandom

[EventTortureChamberTocPrologPlaceRandom]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceRandom

[EventTortureChamberTocPrologProxyPlaceExploreCell]
vartests=VarOperation:readTortureChamberPlaceExploreCell,==,0 VarTestsLogicalOperator:AND VarOperation:visibleTortureChamberPlaceExploreCell,>,0 
display=false
buttons=1
event1=EventTortureChamberTocPrologPlaceExploreCell

[EventTortureChamberTocPrologPlaceExploreCell]
display=false
buttons=1
event1=EventTortureChamberReadPagePlaceExploreCell

[EventTortureChamberTocPrologProxySearchRandom]
vartests=VarOperation:readTortureChamberSearchRandom,==,0 VarTestsLogicalOperator:AND VarOperation:visibleTortureChamberSearchRandom,>,0 
display=false
buttons=1
event1=EventTortureChamberTocPrologSearchRandom

[EventTortureChamberTocNoPagesAvailable]
operations=EventTortureChamberExit,=,1
display=false
buttons=1
event1=EventTortureChamberTiePoint

[EventTortureChamberReadPagePlaceTrigger]
operations=EventTortureChamberTriggeredPageIndex,=,1
display=false
buttons=1
event1=EventTortureChamberInit
trigger=VarExploreTortureChamberViaDungeonCave

[EventTortureChamberReadPageSearchRandomTrigger]
operations=EventTortureChamberTriggeredPageIndex,=,4
display=false
buttons=1
event1=EventTortureChamberInit
trigger=VarSearchTortureChamberRandom
