; Saved by version: 3.15

[UIHighlightTokenExploreAltarViaCell]
xposition=-3.5
yposition=19.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenMatthias]
xposition=1.75
yposition=19.25
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenAltarInvestigators]
xposition=-1.75
yposition=19.25
display=false
buttons=0
image=H238x248.png
size=1

[UIHighlightTokenDungeonCellInvestigators]
xposition=-4.606136
yposition=19.28523
display=false
buttons=0
image=H238x248.png
size=1

[UIHighlightTokenLiveWoman]
xposition=0.6132717
yposition=20.16801
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDeadWoman]
xposition=0.597877
yposition=20.11226
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenAltarGate]
xposition=-0.8546592
yposition=20.1445
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreBackyardViaDriveway]
xposition=3.5
yposition=1.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDoorBackyard]
xposition=3.735622
yposition=1.696659
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenSearchBackyard2x4]
xposition=2.586402
yposition=2.604879
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenBackyardBenBefore]
xposition=-2.222815
yposition=2.618721
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreDiningRoomViaBackyard]
xposition=-1.75
yposition=3.5
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchBackyardRandom]
xposition=0.6820569
yposition=1.273813
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenBasementWall]
xposition=-3.5
yposition=15.75
display=false
buttons=0
image=H128x154.png
size=1

[UIHighlightTokenBasementDarkness1]
xposition=1.75
yposition=12.25
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenBasementDarkness2]
xposition=1.75
yposition=15.75
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenBasementDarkness3]
xposition=-1.75
yposition=15.75
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenBasementDarkness4]
xposition=-1.75
yposition=12.25
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenSearchBasementEvidence]
xposition=1.75
yposition=12.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchBasementTrapdoor]
xposition=-2.1444
yposition=15.72703
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDungeonCaveWall]
xposition=-3.332885
yposition=15.77457
display=false
buttons=0
image=H128x154.png
size=1

[UIHighlightTokenExploreDungeonCaveViaBasement]
xposition=-3.5
yposition=15.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreBackyardViaDiningRoomBlocked]
xposition=-1.75
yposition=3.5
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenInvestigatorsDiningRoom]
xposition=-1.75
yposition=5.25
display=false
buttons=0
image=H238x248.png
size=1

[UIHighlightTokenDiningRoomBen]
xposition=-2.624588
yposition=4.434726
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreChapelViaLibrary]
xposition=-22.75
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenChapelTrapdoor]
xposition=-23.16766
yposition=15.47866
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenChapelWall]
xposition=-17.5
yposition=15.75
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenExploreEscapeViaChapelLocked]
xposition=-22.74345
yposition=20.83925
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchChapelWhiskey]
xposition=-22.6724
yposition=18.32393
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchChapelRitualComponents]
xposition=-21.74766
yposition=14.98724
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenChapelPriestAlive]
xposition=-19.25
yposition=15.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchCryptViaChapel]
xposition=-18.91576
yposition=15.45179
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreCryptViaDungeonCave]
xposition=-10.5
yposition=15.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchCryptRandom]
xposition=-12.94028
yposition=15.646
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchCryptPeter]
xposition=-15.10962
yposition=15.77754
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchChapelViaCrypt]
xposition=-16.79732
yposition=15.71615
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreDungeonCaveViaCrypt]
xposition=-10.5
yposition=15.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDoorDiningRoom]
xposition=-3.5
yposition=5.25
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenExploreKitchenViaDiningRoom]
xposition=-0.008407762
yposition=5.166533
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreBasementViaDiningRoomBlocked]
xposition=-1.75
yposition=10.5
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreHall1ViaDiningRoomBlocked]
xposition=-3.5
yposition=5.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchDiningRoomFluxStabilizer]
xposition=-1.201353
yposition=6.182214
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchDiningRoomPaper]
xposition=-0.6698923
yposition=9.053431
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenBackyardBenPassive]
xposition=-1.967565
yposition=2.341855
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchKitchenCutlery]
xposition=2.688401
yposition=7.943312
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchKitchenRandom]
xposition=1.909069
yposition=4.337167
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDarknessDiningRoom1]
xposition=-1.767338
yposition=7.999224
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenDarknessDiningRoom2]
xposition=-1.570083
yposition=5.168945
display=false
buttons=0
image=H256x256.png
size=1

[UIHighlightTokenExploreBasementViaDiningRoom]
xposition=-1.75
yposition=10.5
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDrivewayInvestigators]
xposition=5.25
yposition=5.25
display=false
buttons=0
image=H238x248.png
size=1

[UIHighlightTokenExploreKitchenViaDriveway]
xposition=3.5
yposition=5.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreBackyardViaDrivewayBlocked]
xposition=3.5
yposition=1.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchDrivewayGardenTool]
xposition=6.239617
yposition=0.9080851
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchDrivewayJournal]
xposition=6.191895
yposition=3.210649
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDriveWayBen]
xposition=6.212849
yposition=3.230453
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDrivewayBen]
xposition=6.212849
yposition=3.230453
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreTortureChamberViaDungeonCave]
xposition=-8.75
yposition=17.5
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreCellViaTortureChamber]
xposition=-5.553874
yposition=19.18092
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenFeeder1]
xposition=-22.75
yposition=19.25
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder2]
xposition=-21
yposition=17.5
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder3]
xposition=-19.25
yposition=15.75
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder4]
xposition=-15.75
yposition=15.75
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder5]
xposition=-12.25
yposition=15.75
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder6]
xposition=-8.75
yposition=15.75
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder7]
xposition=-8.75
yposition=19.25
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder8]
xposition=-4.630488
yposition=19.29642
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenFeeder9]
xposition=-1.75
yposition=19.25
display=false
buttons=0
image=H512x512.png
size=1

[UIHighlightTokenExploreFoyerViaGallery]
xposition=-10.5
yposition=12.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreFoyerViaHall2]
xposition=-12.25
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreFoyerViaStudy]
xposition=-19.25
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreStudyViaFoyer]
xposition=-19.25
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchFoyerCandles]
xposition=-11.13451
yposition=8.521326
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchFoyerRandom]
xposition=-13.72323
yposition=13.04985
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreFoyerFrontDoor]
xposition=-15.78244
yposition=13.4859
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchFoyerSpellRight]
xposition=-12.61886
yposition=10.14136
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchFoyerSpellLeft]
xposition=-18.90788
yposition=10.04326
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreGalleryViaHall1]
xposition=-5.25
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreGalleryViaHall1Sight]
xposition=-5.25
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenHall1Investigators]
xposition=-8.75
yposition=5.25
display=false
buttons=0
image=H238x248.png
size=1

[UIHighlightTokenSearchHall1Painting]
xposition=-8.74381
yposition=3.670119
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreGalleryViaFoyer]
xposition=-10.50718
yposition=12.17408
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreCoatRoomViaGallery]
xposition=-5.809877
yposition=11.74914
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchGalleryDvm]
xposition=-7.833254
yposition=9.129033
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchCoatRoomEvidence]
xposition=-6.107967
yposition=13.19925
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDoorHall1]
xposition=-5.265403
yposition=7.005507
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenWallHall1]
xposition=-8.75
yposition=3.5
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenExploreHall1ViaDiningRoom]
xposition=-3.5
yposition=5.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchHall1Rug]
xposition=-8.336265
yposition=4.565389
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSarah]
xposition=-5.25
yposition=5.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenWallHall2]
xposition=-12.25744
yposition=3.545928
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenSearchHall2Evidence]
xposition=-16.68821
yposition=4.221417
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenWallLibrary]
xposition=-24.5
yposition=5.25
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenExploreLibraryViaStudy]
xposition=-21
yposition=1.75
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchLibraryKey]
xposition=-22.83057
yposition=1.538146
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchLibraryBookcase]
xposition=-22.75
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreChapelViaLibraryBlocked]
xposition=-22.75
yposition=7
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenExploreStudyViaHall2]
xposition=-17.5
yposition=5.25
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenDoorStudy]
xposition=-19.30459
yposition=7.229941
display=false
buttons=0
image=H129x154.png
size=1

[UIHighlightTokenSearchStudyHealingStone]
xposition=-19.25622
yposition=3.183688
display=false
buttons=0
image=H256x256-circle.png
size=1

[UIHighlightTokenSearchTortureChamberRandom]
xposition=-6.815581
yposition=18.06973
display=false
buttons=0
image=H256x256-circle.png
size=1
