; Saved by version: 3.15

[UI0]
xposition=0
yposition=0
buttons=1
event1=
image=
size=1
richText=True
vunits=True

[UIStoryBackground]
xposition=0
yposition=0
display=false
buttons=0
add=UIStoryImage
image=ImageCutsceneBG
size=1.12

[UIStoryImage]
xposition=0.29
yposition=0
display=false
buttons=1
event1=
image=Cover.png
size=0.92
vunits=True
halign=left

[UISplashFancyBar]
xposition=0.15
yposition=0.035
display=false
buttons=0
image=ImageCutsceneTextTopper
size=0.355
richText=True
halign=right
valign=top

[UIOpeningText]
xposition=0.15
yposition=-0.43
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right
valign=top

[UIStoryContinue]
xposition=0.15
yposition=0.05
operations=@SplashScreenClosed,=,1
display=false
buttons=1
event1=
image=
size=0.12
border=True
textaspect=4.5
halign=right
valign=bottom

[UIGameOverWinStopRitualText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopRitual VarTestsLogicalOperator:AND VarOperation:result,==,endWin 
display=false
buttons=0
add=UIGameOverButton
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverButton]
xposition=0.35
yposition=0.505
operations=$end,=,1
display=false
buttons=1
event1=
image=
size=0.12
border=True
textaspect=4.5

[UIGameOverHalfWinStopRitualText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopRitual VarTestsLogicalOperator:AND VarOperation:result,==,endPartialWin 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverLoseStopRitualText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopRitual VarTestsLogicalOperator:AND VarOperation:result,==,endFail 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverLoseRescueBoy]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalRescueBoy VarTestsLogicalOperator:AND VarOperation:result,==,endFail 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverWinRescueBoyText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalRescueBoy VarTestsLogicalOperator:AND VarOperation:result,==,endWin 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverHalfWinRescueBoyText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalRescueBoy VarTestsLogicalOperator:AND VarOperation:result,==,endPartialWin 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverWinStopCultistsText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopCultists VarTestsLogicalOperator:AND VarOperation:result,==,endWin 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverLoseStopCultistsText]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopCultists VarTestsLogicalOperator:AND VarOperation:result,==,endFail 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverHalfWinStopCultists]
xposition=0.1
yposition=-0.02
vartests=VarOperation:goal,==,goalStopCultists VarTestsLogicalOperator:AND VarOperation:result,==,endPartialWin 
display=false
buttons=0
image=
size=0.35
textsize=0.7
textaspect=0.25
halign=right

[UIGameOverContinue]
xposition=0
yposition=0
display=false
buttons=1
event1=EventGameDoneEnd
image=
size=1
