; Saved by version: 3.13

[EventRngStart]
comment=Generates a random number from 0 - (rngInput - 1); set that variable and then set VarCallRng = 1; the value will be returned in rngResult.
operations=rngBaseRange,=,10 rngK,=,1
display=false
buttons=1
event1=EventRngMinimum EventRngGetBaseRange EventRngMainLoop
trigger=VarCallRng

[EventRngMinimum]
comment=If a number below 1 is passed, always return 0
operations=rngResult,=,0
vartests=VarOperation:rngInput,<,1 
display=false
buttons=0

[EventRngGetBaseRange]
comment=find the smallest 10^k >= input
operations=rngBaseRange,*,10 rngK,+,1
vartests=VarOperation:rngBaseRange,<,rngInput 
display=false
buttons=1
event1=EventRngGetBaseRange EventRngMainLoop

[EventRngMainLoop]
comment=rngLimit is to make sure we are within a multiple of rngInput, but avoiding modulo bias
operations=rngLimit,=,rngBaseRange rngLimit,/,rngInput rngLimit,*,rngInput rngLimit,-,1 rngI,=,0 rngResult,=,0
display=false
buttons=1
event1=EventRngBuildNumber

[EventRngBuildNumber]
comment=calculate each digit from largest to smallest; #rand10 returns 1 -10 so we have to subtract 1; if the number is too big, retry it. Again. And again.
operations=rngI,+,1 rngResult,*,10 rngResult,+,#rand10 rngResult,-,1
vartests=VarOperation:rngI,<,rngK 
display=false
buttons=1
event1=EventRngBuildNumber EventRngFinalize EventRngMainLoop

[EventRngFinalize]
comment=guarantee 0 <= result and result < input; return result if true
operations=rngResult,%,rngInput
vartests=VarOperation:rngResult,<=,rngLimit 
display=false
buttons=0

[EventRngInit]
comment=This is sloppy, but we want to crate the VarRng variable so it can be used to trigger the function. This will never be called.
operations=@CallRng,=,0
display=false
buttons=0

[EventTestRng]
operations=rngInput,=,25 @CallRng,=,1
buttons=2
event1=EventTestRng
event2=

[EventClearAllMythosFlags]
operations=mythosHelp,=,0 $mythosFlavor,=,0 $mythosMinor,=,0 $mythosMajor,=,0 $mythosDeadly,=,0 $mythosIndoors,=,0 $mythosOutdoors,=,0 $mythosStreetCorner,=,0 $mythosAlleyCorner,=,0 $mythosAlley,=,0 $mythosStreet,=,0 $mythosHall,=,0 $mythosLibrary,=,0 $mythosKitchen,=,0 $mythosBallroom,=,0 $mythosCrypt,=,0 $mythosGraveyard,=,0 $mythosMorgue,=,0 $mythosBeach,=,0 $mythosDoc,=,0 $mythosPier,=,0 $mythosBathroom,=,0 $mythosOffice,=,0 $mythosStudy,=,0 $mythosTownSquare,=,0 $mythosLounge,=,0 $mythosStairs,=,0 $mythosRiver,=,0 $mythosDiningRoom,=,0 $mythosBedroom,=,0 $mythosStorageRoom,=,0 $mythosHallStairs,=,0 $mythosAtticStorage,=,0 $mythosClassroom,=,0 $mythosChapel,=,0 $mythosExhibit,=,0 $mythosDarkness,=,0 $mythosDiscardItem,=,0 $mythosKey,=,0
display=false
buttons=1
event1=
trigger=VarClearAllMythosFlags
