; Saved by version: 3.11

[TokenInvestigatorsUpperLeft]
xposition=1.75
yposition=-1.75
display=false
buttons=0
type=TokenInvestigators

[TokenInvestigatorsLowerRight]
xposition=5.25
yposition=-5.25
display=false
buttons=0
type=TokenInvestigators
